// Generated by harpia Stage 10 (YAML adapter). Do not edit.
#ifndef HARPIA_YAML_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_YAML_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "yaml/harpia_yaml.h"
#include "protofiles/vip_users_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// YAML for vip_users is provided by the generic reflection-based runtime:
//   std::string yaml = harpia::yaml::to_yaml(msg);   // vip_users -> YAML
//   harpia::yaml::from_yaml(yaml, &msg);             // YAML -> vip_users
//
// This wrapper exists only to pull the runtime in alongside the message's
// protobuf header, matching the JSON/XML adapters' per-message shape.

#endif  // HARPIA_YAML_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
