// Generated by harpia Stage 10 (YAML adapter). Do not edit.
#ifndef HARPIA_YAML_VITALS_PUBLICATION_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_YAML_VITALS_PUBLICATION_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "yaml/harpia_yaml.h"
#include "protofiles/vitals_publication_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// YAML for vitals_publication is provided by the generic reflection-based runtime:
//   std::string yaml = harpia::yaml::to_yaml(msg);   // vitals_publication -> YAML
//   harpia::yaml::from_yaml(yaml, &msg);             // YAML -> vitals_publication
//
// This wrapper exists only to pull the runtime in alongside the message's
// protobuf header, matching the JSON/XML adapters' per-message shape.

#endif  // HARPIA_YAML_VITALS_PUBLICATION_3ac5d8b36fc7dcfb70888145147ddfb7
