"""REST CRUD routes for ``crew`` (table ``crew_table``).

Generated by harpia (python target), the Python side of the C++
``rest/crew_3ac5d8b36fc7dcfb70888145147ddfb7_rest.h``. Do not edit. Routes, status codes, bodies and
pagination are documented in :mod:`harpia_runtime.http.rest`.

Access gate: the flat generated credential -- ``X-User: crew`` and ``X-Pswd: <hash>``, else 401.
"""
from harpia_generated.db.crew_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    crew_dao,
)
from harpia_generated.protofiles.crew_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    crew,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.rest import flat_gate, register_crud
from harpia_runtime.http.router import Router

#: default page size of ``GET <base>/crew`` (0: unpaginated unless ?limit=)
DEFAULT_LIMIT = 0

#: the flat generated credential (X-User / X-Pswd)
GATE = flat_gate('crew', '3ac5d8b36fc7dcfb70888145147ddfb7')


def register(router: Router, pool: ConnectionPool, base: str = "") -> None:
    """Register ``crew``'s CRUD routes under ``base`` on ``router``."""
    register_crud(router, pool, base, 'crew', crew_dao, crew, GATE, DEFAULT_LIMIT)
