"""REST CRUD routes for ``shipment`` (table ``shipment_table``).

Generated by harpia (python target), the Python side of the C++
``rest/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_rest.h``. Do not edit. Routes, status codes, bodies and
pagination are documented in :mod:`harpia_runtime.http.rest`.

Access gate: RBAC (``protected``, or hardened and not ``open``) -- the verified client-certificate CN mapped to a role by ``HARPIA_RBAC_MAP`` (:mod:`harpia_runtime.rbac`); 401 without an identity, 403 when its role may not perform the operation.
"""
from harpia_generated.db.shipment_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    shipment_dao,
)
from harpia_generated.protofiles.shipment_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    shipment,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.rest import register_crud
from harpia_runtime.http.router import Router
from harpia_runtime.rbac_gates import rest_rbac_gate

#: default page size of ``GET <base>/shipment`` (0: unpaginated unless ?limit=)
DEFAULT_LIMIT = 0

#: RBAC on the verified client-certificate CN (harpia_runtime.rbac_gates)
GATE = rest_rbac_gate('shipment')


def register(router: Router, pool: ConnectionPool, base: str = "") -> None:
    """Register ``shipment``'s CRUD routes under ``base`` on ``router``."""
    register_crud(router, pool, base, 'shipment', shipment_dao, shipment, GATE, DEFAULT_LIMIT)
