// Generated by harpia Stage 8 (CRUDL). Do not edit.
#ifndef HARPIA_CRUDL_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_CRUDL_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7

#include <cstdint>
#include <string>
#include <vector>

#include <soci/soci.h>
#include "protofiles/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"
#include "crypto/harpia_encrypted_column.h"
#include "events/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_events.h"

namespace harpia {
namespace db {

// Data-access object for alarm_event over the "alarm_event_table" table. Wraps a soci::session
// the caller owns; being SOCI-based it runs on any backend (SQLite, PostgreSQL,
// ...). Scalar/enum fields, singular FKs to table-bearing messages, the
// flattened sub-fields of a non-table composed field, and map<K,V> + repeated
// scalar fields (as child tables keyed by the primary key) are persisted.
//
// Every method returns false instead of throwing: SOCI signals errors with
// exceptions, so each body is wrapped in try/catch. use()/into() bind by
// reference, so bound values are copied into named locals first; nullable reads
// are guarded by an indicator.
class alarm_event_dao {
public:
    explicit alarm_event_dao(::soci::session& db, ::harpia::crypto::KeyProvider& kp = ::harpia::crypto::default_key_provider(), ::harpia::compliance::AuditSink& audit = ::harpia::compliance::default_audit_sink()) : db_(db), kp_(kp), audit_(audit) {}

    bool create_table() {
        try {
            db_ << "CREATE TABLE IF NOT EXISTS \"alarm_event_table\" (\"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" INTEGER PRIMARY KEY, \"patient_id\" TEXT, \"alarm_type\" TEXT, \"severity\" INTEGER, \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT, \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT, \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT);";
            return true;
        } catch (const std::exception&) { return false; }
    }
    bool drop_table() {
        try {
            db_ << "DROP TABLE IF EXISTS \"alarm_event_table\";";
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool create(const ::alarm_event& msg) {
        try {
            int c0 = msg.id_3ac5d8b36fc7dcfb70888145147ddfb7();
            std::string c1 = ::harpia::crypto::encrypt_field(kp_, msg.patient_id());
            std::string c2 = msg.alarm_type();
            int c3 = msg.severity();
            std::string c4 = msg.status_3ac5d8b36fc7dcfb70888145147ddfb7();
            std::string c5 = msg.error_3ac5d8b36fc7dcfb70888145147ddfb7();
            std::string c6 = msg.originator_3ac5d8b36fc7dcfb70888145147ddfb7();
            db_ << "INSERT INTO \"alarm_event_table\" (\"ID_3ac5d8b36fc7dcfb70888145147ddfb7\", \"patient_id\", \"alarm_type\", \"severity\", \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\") VALUES (:c0, :c1, :c2, :c3, :c4, :c5, :c6)",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(c5), ::soci::use(c6);
            audit_.record("phi_create", "alarm_event_table", "patient_id");
            ::harpia::events::alarm_event_channel().publish(msg);
            audit_.record("phi_event_onchange", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool read(std::int64_t id, ::alarm_event* msg) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            std::string l2; ::soci::indicator n2;
            int l3 = 0; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            std::string l6; ::soci::indicator n6;
            db_ << "SELECT \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\", \"patient_id\", \"alarm_type\", \"severity\", \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\" FROM \"alarm_event_table\" WHERE \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" = :id", ::soci::use(id),
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5), ::soci::into(l6, n6);
            if (!db_.got_data()) return false;
                msg->set_id_3ac5d8b36fc7dcfb70888145147ddfb7(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_patient_id(::harpia::crypto::decrypt_field(kp_, n1 == ::soci::i_ok ? l1 : std::string()));
                msg->set_alarm_type(n2 == ::soci::i_ok ? l2 : std::string());
                msg->set_severity(n3 == ::soci::i_ok ? l3 : 0);
                msg->set_status_3ac5d8b36fc7dcfb70888145147ddfb7(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_error_3ac5d8b36fc7dcfb70888145147ddfb7(n5 == ::soci::i_ok ? l5 : std::string());
                msg->set_originator_3ac5d8b36fc7dcfb70888145147ddfb7(n6 == ::soci::i_ok ? l6 : std::string());
            audit_.record("phi_read", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool update(const ::alarm_event& msg) {
        try {
            std::string c0 = ::harpia::crypto::encrypt_field(kp_, msg.patient_id());
            std::string c1 = msg.alarm_type();
            int c2 = msg.severity();
            std::string c3 = msg.status_3ac5d8b36fc7dcfb70888145147ddfb7();
            std::string c4 = msg.error_3ac5d8b36fc7dcfb70888145147ddfb7();
            std::string c5 = msg.originator_3ac5d8b36fc7dcfb70888145147ddfb7();
            long long cid = msg.id_3ac5d8b36fc7dcfb70888145147ddfb7();
            db_ << "UPDATE \"alarm_event_table\" SET \"patient_id\" = :c0, \"alarm_type\" = :c1, \"severity\" = :c2, \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\" = :c3, \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\" = :c4, \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\" = :c5 WHERE \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" = :cid",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(c5), ::soci::use(cid);
            audit_.record("phi_update", "alarm_event_table", "patient_id");
            ::harpia::events::alarm_event_channel().publish(msg);
            audit_.record("phi_event_onchange", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool remove(std::int64_t id) {
        try {
            db_ << "DELETE FROM \"alarm_event_table\" WHERE \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" = :id", ::soci::use(id);
            audit_.record("phi_delete", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool list(std::vector<::alarm_event>* out) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            std::string l2; ::soci::indicator n2;
            int l3 = 0; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            std::string l6; ::soci::indicator n6;
            ::soci::statement st = (db_.prepare << "SELECT \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\", \"patient_id\", \"alarm_type\", \"severity\", \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\" FROM \"alarm_event_table\"",
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5), ::soci::into(l6, n6));
            st.execute();
            while (st.fetch()) {
                ::alarm_event row;
                ::alarm_event* msg = &row;
                msg->set_id_3ac5d8b36fc7dcfb70888145147ddfb7(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_patient_id(::harpia::crypto::decrypt_field(kp_, n1 == ::soci::i_ok ? l1 : std::string()));
                msg->set_alarm_type(n2 == ::soci::i_ok ? l2 : std::string());
                msg->set_severity(n3 == ::soci::i_ok ? l3 : 0);
                msg->set_status_3ac5d8b36fc7dcfb70888145147ddfb7(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_error_3ac5d8b36fc7dcfb70888145147ddfb7(n5 == ::soci::i_ok ? l5 : std::string());
                msg->set_originator_3ac5d8b36fc7dcfb70888145147ddfb7(n6 == ::soci::i_ok ? l6 : std::string());
                out->push_back(row);
            }
            audit_.record("phi_list", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

    // Paginated list: LIMIT/OFFSET applied server-side. offset is 0-based.
    bool list(std::vector<::alarm_event>* out, long long offset, long long limit) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            std::string l2; ::soci::indicator n2;
            int l3 = 0; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            std::string l6; ::soci::indicator n6;
            ::soci::statement st = (db_.prepare << "SELECT \"ID_3ac5d8b36fc7dcfb70888145147ddfb7\", \"patient_id\", \"alarm_type\", \"severity\", \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7\" FROM \"alarm_event_table\" LIMIT :lim OFFSET :off", ::soci::use(limit), ::soci::use(offset),
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5), ::soci::into(l6, n6));
            st.execute();
            while (st.fetch()) {
                ::alarm_event row;
                ::alarm_event* msg = &row;
                msg->set_id_3ac5d8b36fc7dcfb70888145147ddfb7(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_patient_id(::harpia::crypto::decrypt_field(kp_, n1 == ::soci::i_ok ? l1 : std::string()));
                msg->set_alarm_type(n2 == ::soci::i_ok ? l2 : std::string());
                msg->set_severity(n3 == ::soci::i_ok ? l3 : 0);
                msg->set_status_3ac5d8b36fc7dcfb70888145147ddfb7(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_error_3ac5d8b36fc7dcfb70888145147ddfb7(n5 == ::soci::i_ok ? l5 : std::string());
                msg->set_originator_3ac5d8b36fc7dcfb70888145147ddfb7(n6 == ::soci::i_ok ? l6 : std::string());
                out->push_back(row);
            }
            audit_.record("phi_list", "alarm_event_table", "patient_id");
            return true;
        } catch (const std::exception&) { return false; }
    }

private:
    ::soci::session& db_;
    ::harpia::crypto::KeyProvider& kp_;
    ::harpia::compliance::AuditSink& audit_;
};

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_CRUDL_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7
