// Generated by harpia (multi-system-reference / db-concurrency task 1a).
// Copied verbatim into generated/cpp/db/. Do not edit.
//
// PooledSession -- the one way a generated server handler (gRPC today, REST /
// SOAP in db-concurrency task 2) gets a database session when it was built
// over a ::soci::connection_pool. A soci::session is not thread-safe, and
// gRPC / Crow run handlers on many threads, so a server shared by many
// clients must hand each call its own connection. The five rules this RAII
// type enforces, so handlers never call lease()/give_back() themselves:
//
//   1. Borrow with a deadline, never block forever. On timeout outcome() ==
//      Outcome::exhausted (gRPC maps it to RESOURCE_EXHAUSTED "db pool
//      exhausted"). The deadline is kept here on the MONOTONIC clock and SOCI
//      is called in short slices: SOCI 4.0.x's POSIX try_lease() computes its
//      absolute deadline from gettimeofday() (the wall clock), so a forward
//      wall-clock step -- an NTP step, a VM resume, WSL2's periodic resync --
//      makes every thread waiting at that instant "time out" after ~0 ms.
//      Slicing confines a step to the slice in flight. (A BACKWARD step can
//      still stretch one slice by the size of the step; a slot freed in the
//      meantime is still handed over, since give_back() signals waiters.)
//   2. Exactly one borrow per call. The handler passes session() down to every
//      DAO it uses. A second PooledSession on the same thread while one is
//      held can deadlock at saturation (every thread waits for a slot only a
//      waiting thread can free), so it asserts in debug builds.
//   3. Reconnect on borrow: a borrowed session that is !is_connected() gets
//      one reconnect(). If that fails, outcome() == Outcome::reconnect_failed
//      (gRPC: UNAVAILABLE "db reconnect failed") and the slot goes back.
//      Note: SOCI's PostgreSQL is_connected() pings the server, so this costs
//      one round trip per borrow -- the price of never handing out a dead
//      connection (e.g. after a server restart or pg_terminate_backend).
//   4. Clean state on return. If the handler exits by exception, the session
//      is rolled back (errors ignored) before it goes back to the pool, so a
//      throw mid-transaction never leaks an open transaction to the next
//      borrower. Generated code only ever opens a transaction through
//      ::soci::transaction (RAII: rolls back unless committed), which makes a
//      *normal* exit with an open transaction impossible there; SOCI 4 has no
//      portable "is a transaction open?" query to check it after the fact.
//      Hand-written code borrowing a PooledSession must follow the same rule.
//   5. Always give back: the destructor returns the slot on every path.
//
// Single-session mode (the pre-pool constructors of every generated server):
// PooledSession(&db, nullptr, ...) just wraps that session -- no lease, no
// ping, no rollback, identical behavior to before this header existed.
//
// Pool sizing is the caller's: they construct and open the pool. Keep it under
// PostgreSQL's max_connections (default 100) minus admin headroom; each
// PostgreSQL connection is a server process (heavier on Windows). Tens of
// connections serve hundreds of clients when calls are short; beyond that put
// PgBouncer in front. See USAGE.md.
//
// SQLite under a pool (db-concurrency task 1b):
//   * `:memory:` is refused. Every pooled `:memory:` connection is its own,
//     separate, empty database, so a pooled server would silently scatter rows
//     across N invisible databases. Generated servers' pool constructors call
//     refuse_sqlite_memory_pool(), which throws std::invalid_argument; the
//     single-session constructors still accept `:memory:`.
//   * open_sqlite_pool() opens a FILE database on every slot with
//     `PRAGMA journal_mode=WAL` (readers never block the writer) and
//     `PRAGMA busy_timeout` (a writer that finds the database locked waits
//     instead of failing with "database is locked"). SQLite still runs one
//     writer at a time -- that serialization is why PostgreSQL, not SQLite,
//     is the target for many concurrent clients.
#ifndef HARPIA_DB_POOL_H
#define HARPIA_DB_POOL_H

#include <algorithm>
#include <cassert>
#include <chrono>
#include <cstddef>
#include <exception>
#include <stdexcept>
#include <string>
#include <thread>

#include <soci/soci.h>
#include <soci/connection-pool.h>

namespace harpia {
namespace db {

// Default borrow deadline for generated servers built over a pool.
inline constexpr int kDefaultLeaseTimeoutMs = 2000;

class PooledSession {
public:
    enum class Outcome { ok, exhausted, reconnect_failed };

    // `pool` non-null -> borrow from it (rules 1-5); otherwise wrap `single`.
    PooledSession(::soci::session* single, ::soci::connection_pool* pool,
                  int lease_timeout_ms = kDefaultLeaseTimeoutMs)
        : pool_(pool), session_(single) {
        if (!pool_) return;                      // single-session mode
        assert(!holding() && "second PooledSession borrow on one thread (rule 2)");
        if (!lease_within(*pool_, pos_, lease_timeout_ms)) {
            outcome_ = Outcome::exhausted;
            pool_ = nullptr;                     // nothing to give back
            session_ = nullptr;
            return;
        }
        session_ = &pool_->at(pos_);
        if (!alive(*session_)) {
            try {
                session_->reconnect();
            } catch (...) {
            }
            if (!alive(*session_)) {
                outcome_ = Outcome::reconnect_failed;
                pool_->give_back(pos_);
                pool_ = nullptr;
                session_ = nullptr;
                return;
            }
        }
        holding() = true;
        exceptions_at_borrow_ = std::uncaught_exceptions();
    }

    ~PooledSession() {
        if (!pool_) return;
        if (std::uncaught_exceptions() > exceptions_at_borrow_) {
            try {
                session_->rollback();            // rule 4, errors ignored
            } catch (...) {
            }
        }
        holding() = false;
        pool_->give_back(pos_);                  // rule 5
    }

    PooledSession(const PooledSession&) = delete;
    PooledSession& operator=(const PooledSession&) = delete;

    Outcome outcome() const { return outcome_; }
    bool ok() const { return outcome_ == Outcome::ok; }
    ::soci::session& session() { return *session_; }

    // Rule 1 without trusting the wall clock (see the header comment).
    static bool lease_within(::soci::connection_pool& pool, std::size_t& pos,
                             int timeout_ms) {
        using Clock = std::chrono::steady_clock;
        using std::chrono::milliseconds;
        const auto deadline = Clock::now() + milliseconds(timeout_ms);
        for (;;) {
            const long long remaining =
                std::chrono::duration_cast<milliseconds>(deadline - Clock::now()).count();
            if (remaining <= 0) return pool.try_lease(pos, 0);   // last, non-blocking
            const int slice = static_cast<int>(std::min<long long>(remaining, 250));
            const auto t0 = Clock::now();
            if (pool.try_lease(pos, slice)) return true;
            // A slice that "timed out" well before its length means the wall
            // clock moved under SOCI; pause briefly instead of spinning.
            if (Clock::now() - t0 < milliseconds(slice / 2)) {
                std::this_thread::sleep_for(milliseconds(std::min<long long>(remaining, 5)));
            }
        }
    }

private:
    static bool alive(::soci::session& s) {
        try {
            return s.is_connected();
        } catch (...) {
            return false;
        }
    }

    // Per-thread "already holding a pooled session" flag (rule 2).
    static bool& holding() {
        thread_local bool h = false;
        return h;
    }

    ::soci::connection_pool* pool_;
    ::soci::session* session_;
    std::size_t pos_ = 0;
    int exceptions_at_borrow_ = 0;
    Outcome outcome_ = Outcome::ok;
};

// Default busy timeout for open_sqlite_pool(): how long a writer waits for
// SQLite's write lock before giving up.
inline constexpr int kDefaultSqliteBusyTimeoutMs = 5000;

// True when `path` names an in-memory SQLite database (`:memory:`, the empty
// string = a private temporary database, or a `file:` URI asking for memory).
inline bool is_sqlite_memory_path(const std::string& path) {
    return path.empty() || path == ":memory:" ||
           path.rfind("file::memory:", 0) == 0 ||
           path.find("mode=memory") != std::string::npos;
}

// True when `s` is a SQLite connection to a private in-memory (or temporary)
// database: SQLite reports an empty file name for the "main" schema then.
inline bool is_sqlite_memory(::soci::session& s) {
    if (s.get_backend_name() != "sqlite3") return false;
    std::string file;
    ::soci::indicator ind = ::soci::i_ok;
    s << "SELECT file FROM pragma_database_list WHERE name = 'main'",
        ::soci::into(file, ind);
    return ind != ::soci::i_ok || file.empty();
}

// Throws std::invalid_argument when `pool` holds SQLite `:memory:`
// connections (see the header comment). Inspects one borrowed slot; if every
// slot is busy for `lease_timeout_ms` it cannot look and does not throw.
inline void refuse_sqlite_memory_pool(::soci::connection_pool& pool,
                                      int lease_timeout_ms = kDefaultLeaseTimeoutMs) {
    bool memory = false;
    {
        PooledSession probe(nullptr, &pool, lease_timeout_ms);
        if (!probe.ok()) return;
        memory = is_sqlite_memory(probe.session());
    }
    if (memory) {
        throw std::invalid_argument(
            "harpia: a SQLite :memory: database cannot back a connection pool -- "
            "every pooled connection would be its own empty database. Use a "
            "database file path (harpia::db::open_sqlite_pool), or the "
            "single-session constructor for an in-memory database.");
    }
}

// Opens all `size` slots of `pool` on the SQLite FILE `path` through the
// `sqlite` backend factory (pass ::soci::sqlite3 from
// <soci/sqlite3/soci-sqlite3.h>), each with WAL journaling and a busy
// timeout. `size` must be the size the pool was constructed with. Throws
// std::invalid_argument for an in-memory path, std::runtime_error if WAL
// cannot be enabled (e.g. a filesystem without shared-memory support), and
// lets SOCI's own errors (can't open the file) propagate.
inline void open_sqlite_pool(::soci::connection_pool& pool, std::size_t size,
                             const ::soci::backend_factory& sqlite,
                             const std::string& path,
                             int busy_timeout_ms = kDefaultSqliteBusyTimeoutMs) {
    if (is_sqlite_memory_path(path)) {
        throw std::invalid_argument(
            "harpia: open_sqlite_pool needs a database file path, not an "
            "in-memory database (\"" + path + "\")");
    }
    for (std::size_t i = 0; i < size; ++i) {
        ::soci::session& s = pool.at(i);
        s.open(sqlite, path);
        std::string mode;
        s << "PRAGMA journal_mode=WAL", ::soci::into(mode);
        if (mode != "wal") {
            throw std::runtime_error(
                "harpia: could not enable WAL journaling on \"" + path +
                "\" (journal_mode is \"" + mode + "\")");
        }
        int applied = 0;
        s << "PRAGMA busy_timeout=" + std::to_string(busy_timeout_ms),
            ::soci::into(applied);
    }
}

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_DB_POOL_H
