"""Stage 13 (ZMQ/socket transport) -- raw-socket alternative to the gRPC path.

For each message that declares a transport modifier, emit a header-only C++ ZMQ
transport over cppzmq that moves the message as a serialized-protobuf frame:

  - PUSH/PULL  (spec 12.1, push/pull functions)  when the message is push/pull
        <name>_sender    : PUSH socket, connect(endpoint), send(const Msg&)
        <name>_receiver  : PULL socket, bind(endpoint),    recv(Msg*)

  - PUB/SUB    (spec 12.2, streaming functions)  when the message is event/stream
        <name>_publisher : PUB socket,  bind(endpoint),    publish(const Msg&)
        <name>_subscriber: SUB socket,  connect(endpoint), receive(Msg*)

The choice of classes follows the message's harpia access modifiers
(pull/push -> PUSH/PULL, event/stream -> PUB/SUB). Plain messages (no transport
modifier) and enums get no transport. Output lands at
<dest>/generated/cpp/zmq/<name>_<hash>_zmq.h and includes the Stage 7 message
header through the shared include root (-I <dest>/generated/cpp).

The wire format is intentionally minimal: a single frame holding
msg.SerializeToString(). The harpia "originator / unique sender number" concept
(process.md 1.3.1.1) is not modelled yet -- this is the transport core.
"""
import os

from Logger.logger import logger
from Errors.Error import Error, Types, Classes

ZMQ_EXT = "_zmq.h"


class ZmqAdapter:
    def __init__(self, messages, dest) -> None:
        self.messages = messages
        self.dest = dest
        self.outDir = os.path.join(dest, "generated", "cpp", "zmq")
        self.log = logger(outFile=None, moduleName="ZmqAdapter")

    @staticmethod
    def _modifiers(msg):
        mods = getattr(msg, "access_modifiers", None) or []
        return {m[0] for m in mods}

    def Process(self):
        os.makedirs(self.outDir, exist_ok=True)
        written = 0
        for msg in self.messages:
            if getattr(msg, "isEnum", False):
                continue
            mods = self._modifiers(msg)
            push_pull = bool(mods & {"PUSH", "PULL"})
            pub_sub = bool(mods & {"EVENT", "STREAM"})
            if not (push_pull or pub_sub):
                continue
            header = self._render(msg, push_pull, pub_sub)
            fileName = "{}_{}{}".format(msg.name, msg.md5Hash, ZMQ_EXT)
            with open(os.path.join(self.outDir, fileName), "w") as out:
                out.write(header)
            written += 1

        if written == 0:
            self.log.print("no transport-bearing messages; no ZMQ adapters")
            return Error(errCl=Classes.MESSAGES,
                         errTp=Types.NOTHING_TO_REPORT,
                         FileName=self.outDir)

        self.log.print("generated {} ZMQ transport(s) into {}".format(
            written, self.outDir))
        return None

    def _render(self, msg, push_pull, pub_sub):
        cls = "::{}".format(msg.name)
        guard = "HARPIA_ZMQ_{}_{}".format(msg.name.upper(), msg.md5Hash)
        pb = "protofiles/{}_{}.pb.h".format(msg.name, msg.md5Hash)
        body = ""
        if push_pull:
            body += _PUSH_PULL.format(name=msg.name, cls=cls)
        if pub_sub:
            body += _PUB_SUB.format(name=msg.name, cls=cls)
        return _HEADER.format(guard=guard, pb_header=pb, body=body)


_HEADER = """\
// Generated by harpia Stage 13 (ZMQ transport). Do not edit.
#ifndef {guard}
#define {guard}

#include <cstring>
#include <string>
#include <zmq.hpp>
#include "{pb_header}"

namespace harpia {{
namespace zmq_transport {{

{body}}}  // namespace zmq_transport
}}  // namespace harpia

#endif  // {guard}
"""

_PUSH_PULL = """\
// push/pull: {name}_sender pushes, {name}_receiver pulls.
class {name}_sender {{
public:
    {name}_sender(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::push) {{ socket_.connect(endpoint); }}
    bool send(const {cls}& msg) {{
        std::string bytes;
        if (!msg.SerializeToString(&bytes)) return false;
        ::zmq::message_t frame(bytes.size());
        std::memcpy(frame.data(), bytes.data(), bytes.size());
        return socket_.send(frame, ::zmq::send_flags::none).has_value();
    }}
    ::zmq::socket_t& socket() {{ return socket_; }}
private:
    ::zmq::socket_t socket_;
}};

class {name}_receiver {{
public:
    {name}_receiver(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::pull) {{ socket_.bind(endpoint); }}
    bool recv({cls}* msg) {{
        ::zmq::message_t frame;
        if (!socket_.recv(frame, ::zmq::recv_flags::none).has_value()) return false;
        return msg->ParseFromArray(frame.data(), static_cast<int>(frame.size()));
    }}
    ::zmq::socket_t& socket() {{ return socket_; }}
private:
    ::zmq::socket_t socket_;
}};

"""

_PUB_SUB = """\
// pub/sub (streaming/event): {name}_publisher publishes, {name}_subscriber receives.
class {name}_publisher {{
public:
    {name}_publisher(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::pub) {{ socket_.bind(endpoint); }}
    bool publish(const {cls}& msg) {{
        std::string bytes;
        if (!msg.SerializeToString(&bytes)) return false;
        ::zmq::message_t frame(bytes.size());
        std::memcpy(frame.data(), bytes.data(), bytes.size());
        return socket_.send(frame, ::zmq::send_flags::none).has_value();
    }}
    ::zmq::socket_t& socket() {{ return socket_; }}
private:
    ::zmq::socket_t socket_;
}};

class {name}_subscriber {{
public:
    {name}_subscriber(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::sub) {{
        socket_.connect(endpoint);
        socket_.set(::zmq::sockopt::subscribe, "");
    }}
    bool receive({cls}* msg) {{
        ::zmq::message_t frame;
        if (!socket_.recv(frame, ::zmq::recv_flags::none).has_value()) return false;
        return msg->ParseFromArray(frame.data(), static_cast<int>(frame.size()));
    }}
    ::zmq::socket_t& socket() {{ return socket_; }}
private:
    ::zmq::socket_t socket_;
}};

"""
