// Generated by harpia Stage 11 (SDC / WS-Discovery). Do not edit.
#ifndef HARPIA_SDC_BEACON_LOG_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_SDC_BEACON_LOG_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "sdc/harpia_wsdiscovery.h"

/// \file
/// \brief WS-Discovery participant descriptor for beacon_log.
///
/// Advertises the existing Stage 11 SOAP endpoint (POST &lt;xaddr_base&gt;/beacon_log)
/// for zero-config discovery by an SDC/DPWS-aware client. Additive: the SOAP
/// endpoint itself is unchanged -- this only makes it findable via a multicast
/// WS-Discovery Probe.

namespace harpia {
namespace wsdiscovery {

/// The advertised endpoint for beacon_log: a fixed generic DPWS device type, a
/// Harpia-namespaced per-project scope, and the SOAP endpoint URL completed
/// from \p xaddr_base at call time (\p xaddr_base is the deployment's SOAP
/// base URL, e.g. "http://host:8080/soap").
inline Endpoint beacon_log_wsdiscovery_endpoint(const std::string& xaddr_base) {
    Endpoint ep;
    ep.endpoint_reference = "urn:uuid:7897e0ed-b7f1-5166-afc8-d5ed22d73556";
    ep.types = { "dpws:Device" };
    ep.scopes = { "https://harpia.dev/sdc/scope/default/beacon_log" };
    ep.xaddrs = xaddr_base + "/beacon_log";
    return ep;
}

/// Register beacon_log's endpoint with a WS-Discovery \ref Responder. Call before
/// Responder::start().
inline void register_beacon_log_wsdiscovery(Responder& responder,
                                        const std::string& xaddr_base) {
    responder.add(beacon_log_wsdiscovery_endpoint(xaddr_base));
}

}  // namespace wsdiscovery
}  // namespace harpia

#endif  // HARPIA_SDC_BEACON_LOG_3ac5d8b36fc7dcfb70888145147ddfb7
