// Generated by harpia Stage 11 (SDC / WS-Discovery). Do not edit.
#ifndef HARPIA_SDC_CREW_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_SDC_CREW_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "sdc/harpia_wsdiscovery.h"

/// \file
/// \brief WS-Discovery participant descriptor for crew.
///
/// Advertises the existing Stage 11 SOAP endpoint (POST &lt;xaddr_base&gt;/crew)
/// for zero-config discovery by an SDC/DPWS-aware client. Additive: the SOAP
/// endpoint itself is unchanged -- this only makes it findable via a multicast
/// WS-Discovery Probe.

namespace harpia {
namespace wsdiscovery {

/// The advertised endpoint for crew: a fixed generic DPWS device type, a
/// Harpia-namespaced per-project scope, and the SOAP endpoint URL completed
/// from \p xaddr_base at call time (\p xaddr_base is the deployment's SOAP
/// base URL, e.g. "http://host:8080/soap").
inline Endpoint crew_wsdiscovery_endpoint(const std::string& xaddr_base) {
    Endpoint ep;
    ep.endpoint_reference = "urn:uuid:ad1a4a8a-ca9d-58d2-8503-4c85b1e774a8";
    ep.types = { "dpws:Device" };
    ep.scopes = { "https://harpia.dev/sdc/scope/default/crew" };
    ep.xaddrs = xaddr_base + "/crew";
    return ep;
}

/// Register crew's endpoint with a WS-Discovery \ref Responder. Call before
/// Responder::start().
inline void register_crew_wsdiscovery(Responder& responder,
                                        const std::string& xaddr_base) {
    responder.add(crew_wsdiscovery_endpoint(xaddr_base));
}

}  // namespace wsdiscovery
}  // namespace harpia

#endif  // HARPIA_SDC_CREW_3ac5d8b36fc7dcfb70888145147ddfb7
