// Generated by harpia Stage 9 (JSON adapter). Do not edit.
#ifndef HARPIA_JSON_CREW_QUARTERS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_JSON_CREW_QUARTERS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>
#include <google/protobuf/util/json_util.h>
#include "protofiles/crew_quarters_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

namespace harpia {
namespace json {

// message -> JSON
inline bool to_json(const ::crew_quarters& msg, std::string* out) {
    return ::google::protobuf::util::MessageToJsonString(msg, out).ok();
}

// JSON -> message. Ignores keys the schema doesn't recognize (a newer peer's
// added field) so parsing degrades the way proto3 binary/XML already do,
// rather than hard-erroring on exactly the case forward-compatibility exists
// for -- see plans/message-versioning.md S4.
inline bool from_json(const std::string& in, ::crew_quarters* msg) {
    ::google::protobuf::util::JsonParseOptions opts;
    opts.ignore_unknown_fields = true;
    return ::google::protobuf::util::JsonStringToMessage(in, msg, opts).ok();
}

// is the JSON a valid crew_quarters message? (same unknown-field tolerance as from_json)
inline bool is_valid_json(const std::string& in) {
    ::crew_quarters probe;
    ::google::protobuf::util::JsonParseOptions opts;
    opts.ignore_unknown_fields = true;
    return ::google::protobuf::util::JsonStringToMessage(in, &probe, opts).ok();
}

}  // namespace json
}  // namespace harpia

#endif  // HARPIA_JSON_CREW_QUARTERS_3ac5d8b36fc7dcfb70888145147ddfb7
