// Generated by harpia Stage 9 (JSON adapter). Do not edit.
#ifndef HARPIA_JSON_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_JSON_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>
#include <google/protobuf/util/json_util.h>
#include "protofiles/patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

namespace harpia {
namespace json {

// message -> JSON
inline bool to_json(const ::patient_vitals& msg, std::string* out) {
    return ::google::protobuf::util::MessageToJsonString(msg, out).ok();
}

// JSON -> message. Ignores keys the schema doesn't recognize (a newer peer's
// added field) so parsing degrades the way proto3 binary/XML already do,
// rather than hard-erroring on exactly the case forward-compatibility exists
// for -- see plans/message-versioning.md S4.
inline bool from_json(const std::string& in, ::patient_vitals* msg) {
    ::google::protobuf::util::JsonParseOptions opts;
    opts.ignore_unknown_fields = true;
    return ::google::protobuf::util::JsonStringToMessage(in, msg, opts).ok();
}

// is the JSON a valid patient_vitals message? (same unknown-field tolerance as from_json)
//
// The trailing defaulted, unused ::patient_vitals* makes this an overload keyed on the
// message type, not a plain free function: a translation unit that includes
// several <name>_json.h headers at once (e.g. the generated
// http/http_server_bringup.h, which pulls in every REST binding) then has one
// distinct is_valid_json per message rather than an ODR clash. Existing
// single-header callers -- `harpia::json::is_valid_json(js)` -- resolve through
// the default argument exactly as before.
inline bool is_valid_json(const std::string& in, const ::patient_vitals* = nullptr) {
    ::patient_vitals probe;
    ::google::protobuf::util::JsonParseOptions opts;
    opts.ignore_unknown_fields = true;
    return ::google::protobuf::util::JsonStringToMessage(in, &probe, opts).ok();
}

}  // namespace json
}  // namespace harpia

#endif  // HARPIA_JSON_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7
