"""Schema migration for ``journey`` (table ``journey_table``) to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

Generated by harpia (python target), the port of the C++
``migrate_journey``. Do not edit. Steps and their order are documented in
``harpia_runtime.db.migrate``; every SQL statement comes from the
``sqlite`` ``DbBackend`` the C++ migration uses.
"""
from collections.abc import Callable

from harpia_generated.db.journey_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    journey_dao,
)
from harpia_runtime.db.dao import Connection
from harpia_runtime.db.migrate import MigrationSpec, migrate

#: the schema version this migration targets
VERSION = '3ac5d8b36fc7dcfb70888145147ddfb7'

SPEC = MigrationSpec(
    table='journey_table',
    version=VERSION,
    version_table_sql='CREATE TABLE IF NOT EXISTS "_harpia_schema_version" ("name" TEXT PRIMARY KEY, "version" TEXT);',
    list_child_tables_sql='SELECT "name" FROM sqlite_master WHERE type = \'table\' AND substr("name", 1, 15) = \'journey_table__\';',
    child_renames=(),
    list_columns_sql='SELECT "name" FROM pragma_table_info(\'journey_table\');',
    renames=(),
    adds=(('path_start_city', 'ALTER TABLE "journey_table" ADD COLUMN "path_start_city" TEXT;'), ('path_start_elevation', 'ALTER TABLE "journey_table" ADD COLUMN "path_start_elevation" INTEGER;'), ('path_label', 'ALTER TABLE "journey_table" ADD COLUMN "path_label" TEXT;'), ('vessel', 'ALTER TABLE "journey_table" ADD COLUMN "vessel" TEXT;'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "journey_table" ADD COLUMN "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "journey_table" ADD COLUMN "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ORIGINATOR', 'ALTER TABLE "journey_table" ADD COLUMN "ORIGINATOR" TEXT;')),
    current_columns=('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'path_start_city', 'path_start_elevation', 'path_label', 'vessel', 'STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ORIGINATOR'),
    drop_column_sql='ALTER TABLE "journey_table" DROP COLUMN "<<NAME>>";',
    retype={'types_sql': 'SELECT "name", "type" FROM pragma_table_info(\'journey_table\');', 'steps': [([('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'INTEGER'), ('path_start_city', 'TEXT'), ('path_start_elevation', 'INTEGER'), ('path_label', 'TEXT'), ('vessel', 'TEXT'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ORIGINATOR', 'TEXT')], ['CREATE TABLE "journey_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "path_start_city" TEXT, "path_start_elevation" INTEGER, "path_label" TEXT, "vessel" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);', 'INSERT INTO "journey_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "path_start_city", "path_start_elevation", "path_label", "vessel", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") SELECT CAST("ID_3ac5d8b36fc7dcfb70888145147ddfb7" AS INTEGER), CAST("path_start_city" AS TEXT), CAST("path_start_elevation" AS INTEGER), CAST("path_label" AS TEXT), CAST("vessel" AS TEXT), CAST("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ORIGINATOR" AS TEXT) FROM "journey_table";', 'DROP TABLE "journey_table";', 'ALTER TABLE "journey_table__retype_tmp" RENAME TO "journey_table";'])]},
    child_current=(),
    drop_table_sql='DROP TABLE "<<NAME>>";',
    child_plans=(),
    stamp_sql='INSERT OR REPLACE INTO "_harpia_schema_version" ("name", "version") VALUES (\'journey_table\', \'3ac5d8b36fc7dcfb70888145147ddfb7\');',
)


def migrate_journey(conn: Connection,
                    data_transform: Callable[[Connection], None] | None = None) -> bool:
    """Bring an existing database's ``journey_table`` up to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

    Args:
        conn: A DB-API connection (``sqlite3`` / ``psycopg``).
        data_transform: Optional cross-version data hook, run after new
            columns are added and before retired ones are dropped. Should
            be idempotent.

    Returns:
        ``True``; a database error raises and rolls the migration back.
    """
    return migrate(conn, SPEC, journey_dao, data_transform)
