"""Schema migration for ``outpost`` (table ``outpost_table``) to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

Generated by harpia (python target), the port of the C++
``migrate_outpost``. Do not edit. Steps and their order are documented in
``harpia_runtime.db.migrate``; every SQL statement comes from the
``sqlite`` ``DbBackend`` the C++ migration uses.
"""
from collections.abc import Callable

from harpia_generated.db.outpost_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    outpost_dao,
)
from harpia_runtime.db.dao import Connection
from harpia_runtime.db.migrate import MigrationSpec, migrate

#: the schema version this migration targets
VERSION = '3ac5d8b36fc7dcfb70888145147ddfb7'

SPEC = MigrationSpec(
    table='outpost_table',
    version=VERSION,
    version_table_sql='CREATE TABLE IF NOT EXISTS "_harpia_schema_version" ("name" TEXT PRIMARY KEY, "version" TEXT);',
    list_child_tables_sql='SELECT "name" FROM sqlite_master WHERE type = \'table\' AND substr("name", 1, 15) = \'outpost_table__\';',
    child_renames=(),
    list_columns_sql='SELECT "name" FROM pragma_table_info(\'outpost_table\');',
    renames=(),
    adds=(('commander', 'ALTER TABLE "outpost_table" ADD COLUMN "commander" TEXT;'), ('berth_label', 'ALTER TABLE "outpost_table" ADD COLUMN "berth_label" TEXT;'), ('berth_skipper', 'ALTER TABLE "outpost_table" ADD COLUMN "berth_skipper" INTEGER;'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "outpost_table" ADD COLUMN "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "outpost_table" ADD COLUMN "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ORIGINATOR', 'ALTER TABLE "outpost_table" ADD COLUMN "ORIGINATOR" TEXT;')),
    current_columns=('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'commander', 'berth_label', 'berth_skipper', 'STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ORIGINATOR'),
    drop_column_sql='ALTER TABLE "outpost_table" DROP COLUMN "<<NAME>>";',
    retype={'types_sql': 'SELECT "name", "type" FROM pragma_table_info(\'outpost_table\');', 'steps': [([('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'INTEGER'), ('commander', 'TEXT'), ('berth_label', 'TEXT'), ('berth_skipper', 'INTEGER'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ORIGINATOR', 'TEXT')], ['CREATE TABLE "outpost_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "commander" TEXT, "berth_label" TEXT, "berth_skipper" INTEGER, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);', 'INSERT INTO "outpost_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "commander", "berth_label", "berth_skipper", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") SELECT CAST("ID_3ac5d8b36fc7dcfb70888145147ddfb7" AS INTEGER), CAST("commander" AS TEXT), CAST("berth_label" AS TEXT), CAST("berth_skipper" AS INTEGER), CAST("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ORIGINATOR" AS TEXT) FROM "outpost_table";', 'DROP TABLE "outpost_table";', 'ALTER TABLE "outpost_table__retype_tmp" RENAME TO "outpost_table";'])]},
    child_current=(),
    drop_table_sql='DROP TABLE "<<NAME>>";',
    child_plans=(),
    stamp_sql='INSERT OR REPLACE INTO "_harpia_schema_version" ("name", "version") VALUES (\'outpost_table\', \'3ac5d8b36fc7dcfb70888145147ddfb7\');',
)


def migrate_outpost(conn: Connection,
                    data_transform: Callable[[Connection], None] | None = None) -> bool:
    """Bring an existing database's ``outpost_table`` up to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

    Args:
        conn: A DB-API connection (``sqlite3`` / ``psycopg``).
        data_transform: Optional cross-version data hook, run after new
            columns are added and before retired ones are dropped. Should
            be idempotent.

    Returns:
        ``True``; a database error raises and rolls the migration back.
    """
    return migrate(conn, SPEC, outpost_dao, data_transform)
