"""Schema migration for ``reception_desk`` (table ``reception_desk_table``) to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

Generated by harpia (python target), the port of the C++
``migrate_reception_desk``. Do not edit. Steps and their order are documented in
``harpia_runtime.db.migrate``; every SQL statement comes from the
``sqlite`` ``DbBackend`` the C++ migration uses.
"""
from collections.abc import Callable

from harpia_generated.db.reception_desk_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    reception_desk_dao,
)
from harpia_runtime.db.dao import Connection
from harpia_runtime.db.migrate import MigrationSpec, migrate

#: the schema version this migration targets
VERSION = '3ac5d8b36fc7dcfb70888145147ddfb7'

SPEC = MigrationSpec(
    table='reception_desk_table',
    version=VERSION,
    version_table_sql='CREATE TABLE IF NOT EXISTS "_harpia_schema_version" ("name" TEXT PRIMARY KEY, "version" TEXT);',
    list_child_tables_sql='SELECT "name" FROM sqlite_master WHERE type = \'table\' AND substr("name", 1, 22) = \'reception_desk_table__\';',
    child_renames=(),
    list_columns_sql='SELECT "name" FROM pragma_table_info(\'reception_desk_table\');',
    renames=(),
    adds=(('visitor_name', 'ALTER TABLE "reception_desk_table" ADD COLUMN "visitor_name" TEXT;'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "reception_desk_table" ADD COLUMN "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "reception_desk_table" ADD COLUMN "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ORIGINATOR', 'ALTER TABLE "reception_desk_table" ADD COLUMN "ORIGINATOR" TEXT;')),
    current_columns=('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'visitor_name', 'STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ORIGINATOR'),
    drop_column_sql='ALTER TABLE "reception_desk_table" DROP COLUMN "<<NAME>>";',
    retype={'types_sql': 'SELECT "name", "type" FROM pragma_table_info(\'reception_desk_table\');', 'steps': [([('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'INTEGER'), ('visitor_name', 'TEXT'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ORIGINATOR', 'TEXT')], ['CREATE TABLE "reception_desk_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "visitor_name" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);', 'INSERT INTO "reception_desk_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "visitor_name", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") SELECT CAST("ID_3ac5d8b36fc7dcfb70888145147ddfb7" AS INTEGER), CAST("visitor_name" AS TEXT), CAST("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ORIGINATOR" AS TEXT) FROM "reception_desk_table";', 'DROP TABLE "reception_desk_table";', 'ALTER TABLE "reception_desk_table__retype_tmp" RENAME TO "reception_desk_table";'])]},
    child_current=(),
    drop_table_sql='DROP TABLE "<<NAME>>";',
    child_plans=(),
    stamp_sql='INSERT OR REPLACE INTO "_harpia_schema_version" ("name", "version") VALUES (\'reception_desk_table\', \'3ac5d8b36fc7dcfb70888145147ddfb7\');',
)


def migrate_reception_desk(conn: Connection,
                           data_transform: Callable[[Connection], None] | None = None) -> bool:
    """Bring an existing database's ``reception_desk_table`` up to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

    Args:
        conn: A DB-API connection (``sqlite3`` / ``psycopg``).
        data_transform: Optional cross-version data hook, run after new
            columns are added and before retired ones are dropped. Should
            be idempotent.

    Returns:
        ``True``; a database error raises and rolls the migration back.
    """
    return migrate(conn, SPEC, reception_desk_dao, data_transform)
