"""Schema migration for ``telemetry`` (table ``telemetry_table``) to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

Generated by harpia (python target), the port of the C++
``migrate_telemetry``. Do not edit. Steps and their order are documented in
``harpia_runtime.db.migrate``; every SQL statement comes from the
``sqlite`` ``DbBackend`` the C++ migration uses.
"""
from collections.abc import Callable

from harpia_generated.db.telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    telemetry_dao,
)
from harpia_runtime.db.dao import Connection
from harpia_runtime.db.migrate import MigrationSpec, migrate

#: the schema version this migration targets
VERSION = '3ac5d8b36fc7dcfb70888145147ddfb7'

SPEC = MigrationSpec(
    table='telemetry_table',
    version=VERSION,
    version_table_sql='CREATE TABLE IF NOT EXISTS "_harpia_schema_version" ("name" TEXT PRIMARY KEY, "version" TEXT);',
    list_child_tables_sql='SELECT "name" FROM sqlite_master WHERE type = \'table\' AND substr("name", 1, 17) = \'telemetry_table__\';',
    child_renames=(),
    list_columns_sql='SELECT "name" FROM pragma_table_info(\'telemetry_table\');',
    renames=(),
    adds=(('label', 'ALTER TABLE "telemetry_table" ADD COLUMN "label" TEXT;'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "telemetry_table" ADD COLUMN "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "telemetry_table" ADD COLUMN "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ORIGINATOR', 'ALTER TABLE "telemetry_table" ADD COLUMN "ORIGINATOR" TEXT;')),
    current_columns=('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'label', 'STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ORIGINATOR'),
    drop_column_sql='ALTER TABLE "telemetry_table" DROP COLUMN "<<NAME>>";',
    retype={'types_sql': 'SELECT "name", "type" FROM pragma_table_info(\'telemetry_table\');', 'steps': [([('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'INTEGER'), ('label', 'TEXT'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ORIGINATOR', 'TEXT')], ['CREATE TABLE "telemetry_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "label" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);', 'INSERT INTO "telemetry_table__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") SELECT CAST("ID_3ac5d8b36fc7dcfb70888145147ddfb7" AS INTEGER), CAST("label" AS TEXT), CAST("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ORIGINATOR" AS TEXT) FROM "telemetry_table";', 'DROP TABLE "telemetry_table";', 'ALTER TABLE "telemetry_table__retype_tmp" RENAME TO "telemetry_table";'])]},
    child_current=None,
    drop_table_sql='DROP TABLE "<<NAME>>";',
    child_plans=(),
    stamp_sql='INSERT OR REPLACE INTO "_harpia_schema_version" ("name", "version") VALUES (\'telemetry_table\', \'3ac5d8b36fc7dcfb70888145147ddfb7\');',
)


def migrate_telemetry(conn: Connection,
                      data_transform: Callable[[Connection], None] | None = None) -> bool:
    """Bring an existing database's ``telemetry_table`` up to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

    Args:
        conn: A DB-API connection (``sqlite3`` / ``psycopg``).
        data_transform: Optional cross-version data hook, run after new
            columns are added and before retired ones are dropped. Should
            be idempotent.

    Returns:
        ``True``; a database error raises and rolls the migration back.
    """
    return migrate(conn, SPEC, telemetry_dao, data_transform)
