"""Schema migration for ``vip_users`` (table ``table_vip_users``) to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

Generated by harpia (python target), the port of the C++
``migrate_vip_users``. Do not edit. Steps and their order are documented in
``harpia_runtime.db.migrate``; every SQL statement comes from the
``sqlite`` ``DbBackend`` the C++ migration uses.
"""
from collections.abc import Callable

from harpia_generated.db.vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    vip_users_dao,
)
from harpia_runtime.db.dao import Connection
from harpia_runtime.db.migrate import MigrationSpec, migrate

#: the schema version this migration targets
VERSION = '3ac5d8b36fc7dcfb70888145147ddfb7'

SPEC = MigrationSpec(
    table='table_vip_users',
    version=VERSION,
    version_table_sql='CREATE TABLE IF NOT EXISTS "_harpia_schema_version" ("name" TEXT PRIMARY KEY, "version" TEXT);',
    list_child_tables_sql='SELECT "name" FROM sqlite_master WHERE type = \'table\' AND substr("name", 1, 17) = \'table_vip_users__\';',
    child_renames=(),
    list_columns_sql='SELECT "name" FROM pragma_table_info(\'table_vip_users\');',
    renames=(),
    adds=(('name', 'ALTER TABLE "table_vip_users" ADD COLUMN "name" TEXT;'), ('family', 'ALTER TABLE "table_vip_users" ADD COLUMN "family" TEXT;'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "table_vip_users" ADD COLUMN "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "table_vip_users" ADD COLUMN "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;'), ('ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ALTER TABLE "table_vip_users" ADD COLUMN "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT;')),
    current_columns=('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'name', 'family', 'STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7'),
    drop_column_sql='ALTER TABLE "table_vip_users" DROP COLUMN "<<NAME>>";',
    retype={'types_sql': 'SELECT "name", "type" FROM pragma_table_info(\'table_vip_users\');', 'steps': [([('ID_3ac5d8b36fc7dcfb70888145147ddfb7', 'INTEGER'), ('name', 'TEXT'), ('family', 'TEXT'), ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT'), ('ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7', 'TEXT')], ['CREATE TABLE "table_vip_users__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "name" TEXT, "family" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT);', 'INSERT INTO "table_vip_users__retype_tmp" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "name", "family", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7") SELECT CAST("ID_3ac5d8b36fc7dcfb70888145147ddfb7" AS INTEGER), CAST("name" AS TEXT), CAST("family" AS TEXT), CAST("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT), CAST("ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" AS TEXT) FROM "table_vip_users";', 'DROP TABLE "table_vip_users";', 'ALTER TABLE "table_vip_users__retype_tmp" RENAME TO "table_vip_users";'])]},
    child_current=(),
    drop_table_sql='DROP TABLE "<<NAME>>";',
    child_plans=(),
    stamp_sql='INSERT OR REPLACE INTO "_harpia_schema_version" ("name", "version") VALUES (\'table_vip_users\', \'3ac5d8b36fc7dcfb70888145147ddfb7\');',
)


def migrate_vip_users(conn: Connection,
                      data_transform: Callable[[Connection], None] | None = None) -> bool:
    """Bring an existing database's ``table_vip_users`` up to version ``3ac5d8b36fc7dcfb70888145147ddfb7``.

    Args:
        conn: A DB-API connection (``sqlite3`` / ``psycopg``).
        data_transform: Optional cross-version data hook, run after new
            columns are added and before retired ones are dropped. Should
            be idempotent.

    Returns:
        ``True``; a database error raises and rolls the migration back.
    """
    return migrate(conn, SPEC, vip_users_dao, data_transform)
