// Generated by harpia Stage 13 (ZMQ transport). Do not edit.
#ifndef HARPIA_ZMQ_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_ZMQ_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <atomic>
#include <cstdint>
#include <cstring>
#include <random>
#include <sstream>
#include <string>
#include <unistd.h>
#include <zmq.hpp>
#include "protofiles/top_users_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

namespace harpia {
namespace zmq_transport {

// Runtime-unique sender id for many-to-* (push/pushpull) publishers, where a
// shared compile-time id would make every "many" sender indistinguishable
// (process.md 1.3.1.1). Combines the process id, a per-process monotonic
// counter, and random bits, so concurrent senders across processes and
// within one process never collide -- no coordinating broker/service needed.
inline std::string runtime_origin_id() {
    static std::atomic<std::uint64_t> counter{0};
    std::random_device rd;
    std::uint64_t r = (static_cast<std::uint64_t>(rd()) << 32) | rd();
    std::ostringstream oss;
    oss << ::getpid() << "-" << counter.fetch_add(1) << "-" << std::hex << r;
    return oss.str();
}

// push/pull: top_users_sender pushes (stamping origin), top_users_receiver pulls.
class top_users_sender {
public:
    top_users_sender(::zmq::context_t& ctx, const std::string& endpoint)
        : top_users_sender(ctx, endpoint, origin_id()) {}
    // explicit-origin constructor: pass any externally-sourced id (e.g. if a
    // future broker hands one out); the default constructor above already
    // supplies a runtime-unique id for many-to-* senders on its own.
    top_users_sender(::zmq::context_t& ctx, const std::string& endpoint,
                  const std::string& origin)
        : origin_(origin), socket_(ctx, ::zmq::socket_type::push) {
        socket_.connect(endpoint);
    }
    // compile-time unique sender number (one-to-*): hash(file)+message
    static const std::string& origin_id() {
        static const std::string id = "254102251027472133";
        return id;
    }
    const std::string& origin() const { return origin_; }
    bool send(const ::top_users& msg) {
        ::top_users stamped = msg;
        stamped.set_originator_c96f8fd7f45108efee5a8ecb43eab1da(origin_);
        std::string bytes;
        if (!stamped.SerializeToString(&bytes)) return false;
        ::zmq::message_t frame(bytes.size());
        std::memcpy(frame.data(), bytes.data(), bytes.size());
        return socket_.send(frame, ::zmq::send_flags::none).has_value();
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    std::string origin_;
    ::zmq::socket_t socket_;
};

class top_users_receiver {
public:
    top_users_receiver(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::pull) { socket_.bind(endpoint); }
    bool recv(::top_users* msg) {
        ::zmq::message_t frame;
        if (!socket_.recv(frame, ::zmq::recv_flags::none).has_value()) return false;
        return msg->ParseFromArray(frame.data(), static_cast<int>(frame.size()));
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    ::zmq::socket_t socket_;
};

// pub/sub (streaming/event): top_users_publisher publishes (stamping origin), top_users_subscriber receives.
class top_users_publisher {
public:
    top_users_publisher(::zmq::context_t& ctx, const std::string& endpoint)
        : top_users_publisher(ctx, endpoint, origin_id()) {}
    // explicit-origin constructor: pass any externally-sourced id (e.g. if a
    // future broker hands one out); the default constructor above already
    // supplies a runtime-unique id for many-to-* senders on its own.
    top_users_publisher(::zmq::context_t& ctx, const std::string& endpoint,
                  const std::string& origin)
        : origin_(origin), socket_(ctx, ::zmq::socket_type::pub) {
        socket_.bind(endpoint);
    }
    // compile-time unique sender number (one-to-*): hash(file)+message
    static const std::string& origin_id() {
        static const std::string id = "254102251027472133";
        return id;
    }
    const std::string& origin() const { return origin_; }
    bool publish(const ::top_users& msg) {
        ::top_users stamped = msg;
        stamped.set_originator_c96f8fd7f45108efee5a8ecb43eab1da(origin_);
        std::string bytes;
        if (!stamped.SerializeToString(&bytes)) return false;
        ::zmq::message_t frame(bytes.size());
        std::memcpy(frame.data(), bytes.data(), bytes.size());
        return socket_.send(frame, ::zmq::send_flags::none).has_value();
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    std::string origin_;
    ::zmq::socket_t socket_;
};

class top_users_subscriber {
public:
    top_users_subscriber(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::sub) { socket_.connect(endpoint);
        socket_.set(::zmq::sockopt::subscribe, ""); }
    bool receive(::top_users* msg) {
        ::zmq::message_t frame;
        if (!socket_.recv(frame, ::zmq::recv_flags::none).has_value()) return false;
        return msg->ParseFromArray(frame.data(), static_cast<int>(frame.size()));
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    ::zmq::socket_t socket_;
};

}  // namespace zmq_transport
}  // namespace harpia

#endif  // HARPIA_ZMQ_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
