// Generated by harpia Stage 13 (ZMQ transport). Do not edit.
#ifndef HARPIA_ZMQ_VIP_USERS_734126ee6efdfbd64a1678bf49ee9683
#define HARPIA_ZMQ_VIP_USERS_734126ee6efdfbd64a1678bf49ee9683

#include <cstring>
#include <string>
#include <zmq.hpp>
#include "protofiles/vip_users_734126ee6efdfbd64a1678bf49ee9683.pb.h"

namespace harpia {
namespace zmq_transport {

// pub/sub (streaming/event): vip_users_publisher publishes, vip_users_subscriber receives.
class vip_users_publisher {
public:
    vip_users_publisher(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::pub) { socket_.bind(endpoint); }
    bool publish(const ::vip_users& msg) {
        std::string bytes;
        if (!msg.SerializeToString(&bytes)) return false;
        ::zmq::message_t frame(bytes.size());
        std::memcpy(frame.data(), bytes.data(), bytes.size());
        return socket_.send(frame, ::zmq::send_flags::none).has_value();
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    ::zmq::socket_t socket_;
};

class vip_users_subscriber {
public:
    vip_users_subscriber(::zmq::context_t& ctx, const std::string& endpoint)
        : socket_(ctx, ::zmq::socket_type::sub) {
        socket_.connect(endpoint);
        socket_.set(::zmq::sockopt::subscribe, "");
    }
    bool receive(::vip_users* msg) {
        ::zmq::message_t frame;
        if (!socket_.recv(frame, ::zmq::recv_flags::none).has_value()) return false;
        return msg->ParseFromArray(frame.data(), static_cast<int>(frame.size()));
    }
    ::zmq::socket_t& socket() { return socket_; }
private:
    ::zmq::socket_t socket_;
};

}  // namespace zmq_transport
}  // namespace harpia

#endif  // HARPIA_ZMQ_VIP_USERS_734126ee6efdfbd64a1678bf49ee9683
