"""The project's HTTP server: every REST binding (and every SOAP endpoint)
on one threaded server.

Generated by harpia (python target), the Python side of the C++
``http/http_server_bringup.h``. Do not edit::

    pool = sqlite_pool("app.db")
    server = HttpServer(pool, port=8080)
    server.start()
    ...
    server.stop()

When some message is RBAC-gated the server also issues bearer session tokens
(``POST <rest_base>/session`` / ``POST <soap_base>/session``, see
:func:`harpia_runtime.rbac_gates.register_session_routes`).
"""
from harpia_generated.capability import (
    capabilities_3ac5d8b36fc7dcfb70888145147ddfb7_http,
)
from harpia_generated.rest import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    beacon_log_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    crew_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    data_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    journey_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    outpost_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    reception_desk_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    shipment_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    top_users_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    users_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    vault_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
    vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_rest,
)
from harpia_generated.soap import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    beacon_log_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    crew_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    data_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    journey_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    outpost_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    reception_desk_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    shipment_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    top_users_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    users_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    vault_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
    vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_soap,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.router import Router, Server
from harpia_runtime.rbac_gates import register_session_routes
from harpia_runtime.tls import MtlsFiles, http_server_context

#: every message with REST routes
REST_MESSAGES = ('data', 'users', 'vip_users', 'top_users', 'shipment', 'journey', 'crew', 'outpost', 'beacon_log', 'patient_vitals', 'alarm_event', 'telemetry', 'reception_desk', 'vault')
#: transport_hardening_required(compliance), evaluated at generation time:
#: when true the server only speaks mTLS (incomplete files → SecurityRefused)
HARDENING_REQUIRED = True
#: protected/open messages diverge from the project default
#: (Database.auth_gate.transport_mode)
EMIT_TLS = True
CLIENT_CERT_REQUIRED = False


class HttpServer:
    """REST routes under ``rest_base`` (and SOAP under ``soap_base``) on one
    :class:`~harpia_runtime.http.router.Server`; each request borrows its own
    connection from ``pool``."""

    def __init__(self, pool: ConnectionPool, host: str = "127.0.0.1", port: int = 0,
                 rest_base: str = "", soap_base: str = "/soap",
                 mtls: MtlsFiles | None = None) -> None:
        if rest_base == soap_base:
            raise ValueError("rest_base and soap_base must differ")
        self.router = Router()
        data_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        data_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        users_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        users_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        top_users_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        top_users_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        shipment_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        shipment_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        journey_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        journey_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        crew_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        crew_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        outpost_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        outpost_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        beacon_log_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        beacon_log_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        reception_desk_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        reception_desk_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        vault_3ac5d8b36fc7dcfb70888145147ddfb7_rest.register(self.router, pool, rest_base)
        vault_3ac5d8b36fc7dcfb70888145147ddfb7_soap.register(self.router, pool, soap_base)
        # capability handshake (ungated, like heartBeat)
        capabilities_3ac5d8b36fc7dcfb70888145147ddfb7_http.register_capabilities(self.router, rest_base)
        # bearer-session issuance (RBAC-gated messages exist)
        register_session_routes(self.router, rest_base, soap_base)
        tls = http_server_context(EMIT_TLS, mtls, CLIENT_CERT_REQUIRED)
        self._server = Server(self.router, host, port, tls)

    @property
    def port(self) -> int:
        """The bound port."""
        return self._server.port

    def start(self) -> None:
        """Serve on a background thread."""
        self._server.start()

    def stop(self) -> None:
        """Stop serving."""
        self._server.stop()
