// Generated by harpia Stage 11 (SOAP) + Stage 5 (access rights). Do not edit.
#ifndef HARPIA_SOAP_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_SOAP_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <cstdlib>
#include <string>

// Crow's own HTTPMethod enum guards its ALL-CAPS members (DELETE/GET/HEAD/
// POST/PUT/...) with a single `#ifndef DELETE` around the WHOLE block -- if
// DELETE is a macro by the time crow.h's own enum is reached, Crow silently
// falls back to TitleCase members only (Delete/Get/Post/Put), and the
// crow::HTTPMethod::POST reference below stops existing. The trouble is
// crow.h itself (line ~915) does `#include <asio.hpp>` long before its own
// enum (~line 2112), and asio.hpp pulls in <windows.h> (which #defines
// DELETE, winnt.h's generic-access-rights macro) internally -- undefining
// DELETE before `#include "crow.h"` doesn't survive that internal
// re-inclusion. Force <windows.h> in ourselves first and undef DELETE right
// after: windows.h's own include guard then makes crow.h/asio's later
// `#include <windows.h>` a no-op, so our undef sticks.
#ifdef _WIN32
#include <windows.h>
#undef DELETE
#endif

#include "crow.h"
#include "db/vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"
#include "xml/vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_xml.h"   // brings tinyxml2 + the XML runtime
#include "http/harpia_rbac.h"
// Minimal SOAP-over-HTTP access for vip_users, backed by the CRUDL DAO. Register on
// a crow::SimpleApp with a base path; POST a SOAP envelope to <base>/vip_users:
//   <soap:Body><get><id>N</id></get></soap:Body>          -> the vip_users as XML
//   <soap:Body><set><vip_users>...</vip_users></set></soap:Body>       -> create
//   <soap:Body><update><vip_users>...</vip_users></update></soap:Body> -> update
//   <soap:Body><delete><id>N</id></delete></soap:Body>    -> delete
//
// Access gate (compiled in at generation time; which variant depends on
// transport_hardening_required(compliance) -- transport-authn epic, tasks 3+4):
//   hardened  -> a three-role RBAC check (admin / main / guest), run once the
//               operation element has been parsed: the verified mTLS client-
//               certificate subject CommonName (crow::request::client_cert_cn)
//               is resolved to a role via the HARPIA_RBAC_MAP file and checked
//               against the operation (get -> read, set -> create, update ->
//               update, delete -> remove). No / unverifiable identity -> a
//               401 SOAP Fault; valid identity, wrong role -> a 403 SOAP
//               Fault. Every denial emits exactly one AuditSink "rbac_denied"
//               record (names only, never a credential value). See generated
//               http/harpia_rbac.h.
//   otherwise -> the flat generated access credential in the SOAP Header, or
//               the request is rejected with a SOAP Fault (HTTP 401):
//   <soap:Header><credentials><user>vip_users</user><pswd>3ac5d8b36fc7dcfb70888145147ddfb7</pswd></credentials></soap:Header>
// (WSDL generation is deferred.)
//
// The crow::SimpleApp itself is stood up by the generated
// http/http_server_bringup.h (transport-authn epic, task 3) -- its
// harpia::http_transport::HttpServer registers this endpoint and the matching
// REST binding on one app and, when transport_hardening_required(compliance)
// was true at generation time, configures it for mTLS (client cert required
// AND verified, harpia_http_mtls.h) with plaintext refused.
namespace harpia {
namespace soap {

// Shared XML helpers, defined once across all generated SOAP headers.
#ifndef HARPIA_SOAP_DETAIL
#define HARPIA_SOAP_DETAIL
namespace detail {

// element name without its namespace prefix ("soap:Body" -> "Body")
inline std::string local_name(const ::tinyxml2::XMLElement* e) {
    std::string n = e->Name();
    const auto pos = n.find(':');
    return pos == std::string::npos ? n : n.substr(pos + 1);
}

// first child element whose local (prefix-stripped) name matches
inline const ::tinyxml2::XMLElement* find_child(
        const ::tinyxml2::XMLElement* parent, const char* local) {
    if (!parent) return nullptr;
    for (auto* c = parent->FirstChildElement(); c; c = c->NextSiblingElement())
        if (local_name(c) == local) return c;
    return nullptr;
}

inline std::string child_text(const ::tinyxml2::XMLElement* parent,
                              const char* local) {
    const auto* c = find_child(parent, local);
    return (c && c->GetText()) ? c->GetText() : std::string();
}

}  // namespace detail
#endif  // HARPIA_SOAP_DETAIL

inline std::string envelope_vip_users(const std::string& body) {
    return "<?xml version=\"1.0\"?>"
           "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
           "<soap:Body>" + body + "</soap:Body></soap:Envelope>";
}

inline void register_vip_users_soap(crow::SimpleApp& app, ::soci::session& db,
                                 const std::string& base) {
    // capture a session pointer (soci::session is non-copyable); the caller must
    // keep the session alive for the lifetime of the registered route.
    ::soci::session* dbp = &db;
    app.route_dynamic(base + "/vip_users").methods(crow::HTTPMethod::POST)(
             [dbp](const crow::request& req, crow::response& res) {
        // all SOAP replies carry an XML body; set the content type once
        auto reply = [&res](const std::string& xml) {
            res.set_header("Content-Type", "text/xml");
            res.body = xml;
        };
        ::harpia::db::vip_users_dao dao(*dbp);
        ::tinyxml2::XMLDocument doc;
        if (doc.Parse(req.body.c_str()) != ::tinyxml2::XML_SUCCESS) {
            res.code = 400; res.end(); return;
        }

        const auto* env = doc.RootElement();                  // soap:Envelope
        const auto* body = ::harpia::soap::detail::find_child(env, "Body");
        const auto* op = body ? body->FirstChildElement() : nullptr;   // operation
        if (!op) { res.code = 400; res.end(); return; }
        const std::string name = ::harpia::soap::detail::local_name(op);
        ::harpia::rbac::Operation rbac_op = ::harpia::rbac::Operation::read;
        bool rbac_known = true;
        if (name == "get") rbac_op = ::harpia::rbac::Operation::read;
        else if (name == "set") rbac_op = ::harpia::rbac::Operation::create;
        else if (name == "update") rbac_op = ::harpia::rbac::Operation::update;
        else if (name == "delete") rbac_op = ::harpia::rbac::Operation::remove;
        else rbac_known = false;
        if (rbac_known) {
            const auto rbac_d =
                ::harpia::rbac::decide(req.client_cert_cn, rbac_op, "vip_users");
            if (rbac_d != ::harpia::rbac::Decision::allow) {
                res.code = (rbac_d == ::harpia::rbac::Decision::unauthenticated)
                               ? 401 : 403;
                reply(envelope_vip_users(
                    "<soap:Fault><faultcode>Client.Authentication</faultcode>"
                    "<faultstring>" +
                    std::string(
                        rbac_d == ::harpia::rbac::Decision::unauthenticated
                            ? "unauthenticated" : "forbidden") +
                    "</faultstring></soap:Fault>"));
                res.end(); return;
            }
        }
        if (name == "get") {
            const auto* idEl = op->FirstChildElement("id");
            const long long id =
                (idEl && idEl->GetText()) ? ::atoll(idEl->GetText()) : 0;
            ::vip_users msg;
            if (!dao.read(id, &msg)) {
                reply(envelope_vip_users(
                    "<soap:Fault><faultstring>not found</faultstring></soap:Fault>"));
                res.end(); return;
            }
            reply(envelope_vip_users(
                "<getResponse>" + ::harpia::xml::to_xml(msg) + "</getResponse>"));
        } else if (name == "set") {
            const auto* m = op->FirstChildElement();          // the vip_users element
            ::vip_users msg;
            if (!m || !::harpia::xml::from_xml_element(m, &msg)) {
                res.code = 400; res.end(); return;
            }
            const bool ok = dao.create(msg);
            reply(envelope_vip_users(
                std::string("<setResponse><ok>") + (ok ? "true" : "false") +
                "</ok></setResponse>"));
        } else if (name == "update") {
            const auto* m = op->FirstChildElement();          // the vip_users element
            ::vip_users msg;
            if (!m || !::harpia::xml::from_xml_element(m, &msg)) {
                res.code = 400; res.end(); return;
            }
            const bool ok = dao.update(msg);
            reply(envelope_vip_users(
                std::string("<updateResponse><ok>") + (ok ? "true" : "false") +
                "</ok></updateResponse>"));
        } else if (name == "delete") {
            const auto* idEl = op->FirstChildElement("id");
            const long long id =
                (idEl && idEl->GetText()) ? ::atoll(idEl->GetText()) : 0;
            const bool ok = dao.remove(id);
            reply(envelope_vip_users(
                std::string("<deleteResponse><ok>") + (ok ? "true" : "false") +
                "</ok></deleteResponse>"));
        } else {
            reply(envelope_vip_users(
                "<soap:Fault><faultstring>unknown operation</faultstring></soap:Fault>"));
        }
        res.end();
    });
}

}  // namespace soap
}  // namespace harpia

#endif  // HARPIA_SOAP_VIP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
