"""CRUDL data-access object for ``journey`` (table ``journey_table``).

Generated by harpia (python target) from the ``.harpia`` schema. Do not
edit. SQL dialect: ``sqlite`` (placeholder ``?``). The table
DDL is the one the C++ target declares for this message.

Deferred (not persisted by this DAO yet): none
"""
from harpia_generated.protofiles.journey_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    journey,
)
from harpia_runtime.db.dao import Column, Dao


class journey_dao(Dao[journey]):
    """CRUDL over table ``journey_table`` for :class:`journey` messages."""

    MESSAGE = journey
    TABLE = 'journey_table'
    PK = 'ID_3ac5d8b36fc7dcfb70888145147ddfb7'
    COLUMNS = (
        Column('ID_3ac5d8b36fc7dcfb70888145147ddfb7', ('ID_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('path_start_city', ('path', 'start', 'city')),
        Column('path_start_elevation', ('path', 'start', 'elevation')),
        Column('path_label', ('path', 'label')),
        Column('vessel', ('vessel',)),
        Column('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ORIGINATOR', ('ORIGINATOR',)),
    )
    CHILDREN = (
    )
    CREATE_TABLE_SQL = (
        'CREATE TABLE IF NOT EXISTS "journey_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "path_start_city" TEXT, "path_start_elevation" INTEGER, "path_label" TEXT, "vessel" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);',
    )
    DROP_TABLE_SQL = (
        'DROP TABLE IF EXISTS "journey_table";',
    )
    INSERT_SQL = 'INSERT INTO "journey_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "path_start_city", "path_start_elevation", "path_label", "vessel", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
    SELECT_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "path_start_city", "path_start_elevation", "path_label", "vessel", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "journey_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    UPDATE_SQL = 'UPDATE "journey_table" SET "path_start_city" = ?, "path_start_elevation" = ?, "path_label" = ?, "vessel" = ?, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ORIGINATOR" = ? WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    DELETE_SQL = 'DELETE FROM "journey_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    LIST_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "path_start_city", "path_start_elevation", "path_label", "vessel", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "journey_table" ORDER BY "ID_3ac5d8b36fc7dcfb70888145147ddfb7"'
    LIST_PAGE_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "path_start_city", "path_start_elevation", "path_label", "vessel", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "journey_table" ORDER BY "ID_3ac5d8b36fc7dcfb70888145147ddfb7" LIMIT ? OFFSET ?'
