"""CRUDL data-access object for ``patient_vitals`` (table ``patient_vitals_table``).

Generated by harpia (python target) from the ``.harpia`` schema. Do not
edit. SQL dialect: ``sqlite`` (placeholder ``?``). The table
DDL is the one the C++ target declares for this message.

Deferred (not persisted by this DAO yet): none
"""
from harpia_generated.protofiles.patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    patient_vitals,
)
from harpia_runtime.db.dao import Column, Dao


class patient_vitals_dao(Dao[patient_vitals]):
    """CRUDL over table ``patient_vitals_table`` for :class:`patient_vitals` messages."""

    MESSAGE = patient_vitals
    TABLE = 'patient_vitals_table'
    PK = 'ID_3ac5d8b36fc7dcfb70888145147ddfb7'
    COLUMNS = (
        Column('ID_3ac5d8b36fc7dcfb70888145147ddfb7', ('ID_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('patient_id', ('patient_id',)),
        Column('heart_rate', ('heart_rate',)),
        Column('device_note', ('device_note',)),
        Column('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ORIGINATOR', ('ORIGINATOR',)),
    )
    CREATE_TABLE_SQL = (
        'CREATE TABLE IF NOT EXISTS "patient_vitals_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "patient_id" TEXT, "heart_rate" REAL NOT NULL, "device_note" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);',
    )
    DROP_TABLE_SQL = (
        'DROP TABLE IF EXISTS "patient_vitals_table";',
    )
    INSERT_SQL = 'INSERT INTO "patient_vitals_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "patient_id", "heart_rate", "device_note", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") VALUES (?, ?, ?, ?, ?, ?, ?)'
    SELECT_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "patient_id", "heart_rate", "device_note", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "patient_vitals_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    UPDATE_SQL = 'UPDATE "patient_vitals_table" SET "patient_id" = ?, "heart_rate" = ?, "device_note" = ?, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ORIGINATOR" = ? WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    DELETE_SQL = 'DELETE FROM "patient_vitals_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    LIST_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "patient_id", "heart_rate", "device_note", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "patient_vitals_table"'
    LIST_PAGE_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "patient_id", "heart_rate", "device_note", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "patient_vitals_table" LIMIT ? OFFSET ?'
