"""CRUDL data-access object for ``telemetry`` (table ``telemetry_table``).

Generated by harpia (python target) from the ``.harpia`` schema. Do not
edit. SQL dialect: ``sqlite`` (placeholder ``?``). The table
DDL is the one the C++ target declares for this message.

Deferred (not persisted by this DAO yet): none
"""
from harpia_generated.protofiles.telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    telemetry,
)
from harpia_runtime.db.dao import ChildTable, Column, Dao


class telemetry_dao(Dao[telemetry]):
    """CRUDL over table ``telemetry_table`` for :class:`telemetry` messages."""

    MESSAGE = telemetry
    TABLE = 'telemetry_table'
    PK = 'ID_3ac5d8b36fc7dcfb70888145147ddfb7'
    COLUMNS = (
        Column('ID_3ac5d8b36fc7dcfb70888145147ddfb7', ('ID_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('label', ('label',)),
        Column('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ORIGINATOR', ('ORIGINATOR',)),
    )
    CHILDREN = (
        ChildTable(
            'map', ('gauges',),
            'INSERT INTO "telemetry_table__gauges" ("owner", "key", "value") VALUES (?, ?, ?)',
            'SELECT "key", "value" FROM "telemetry_table__gauges" WHERE "owner" = ?',
            'DELETE FROM "telemetry_table__gauges" WHERE "owner" = ?'),
        ChildTable(
            'map', ('flags',),
            'INSERT INTO "telemetry_table__flags" ("owner", "key", "value") VALUES (?, ?, ?)',
            'SELECT "key", "value" FROM "telemetry_table__flags" WHERE "owner" = ?',
            'DELETE FROM "telemetry_table__flags" WHERE "owner" = ?'),
        ChildTable(
            'repeated', ('samples',),
            'INSERT INTO "telemetry_table__samples" ("owner", "ordinal", "value") VALUES (?, ?, ?)',
            'SELECT "value" FROM "telemetry_table__samples" WHERE "owner" = ? ORDER BY "ordinal"',
            'DELETE FROM "telemetry_table__samples" WHERE "owner" = ?'),
        ChildTable(
            'repeated', ('notes',),
            'INSERT INTO "telemetry_table__notes" ("owner", "ordinal", "value") VALUES (?, ?, ?)',
            'SELECT "value" FROM "telemetry_table__notes" WHERE "owner" = ? ORDER BY "ordinal"',
            'DELETE FROM "telemetry_table__notes" WHERE "owner" = ?'),
        ChildTable(
            'composed', ('traces',),
            'INSERT INTO "telemetry_table__traces" ("owner", "ordinal", "kind", "weight") VALUES (?, ?, ?, ?)',
            'SELECT "kind", "weight" FROM "telemetry_table__traces" WHERE "owner" = ? ORDER BY "ordinal"',
            'DELETE FROM "telemetry_table__traces" WHERE "owner" = ?', columns=(Column('kind', ('kind',)), Column('weight', ('weight',)),)),
    )
    CREATE_TABLE_SQL = (
        'CREATE TABLE IF NOT EXISTS "telemetry_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "label" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);',
        'CREATE TABLE IF NOT EXISTS "telemetry_table__gauges" ("owner" INTEGER, "key" TEXT, "value" INTEGER, PRIMARY KEY("owner", "key"));',
        'CREATE TABLE IF NOT EXISTS "telemetry_table__flags" ("owner" INTEGER, "key" INTEGER, "value" TEXT, PRIMARY KEY("owner", "key"));',
        'CREATE TABLE IF NOT EXISTS "telemetry_table__samples" ("owner" INTEGER, "ordinal" INTEGER, "value" INTEGER, PRIMARY KEY("owner", "ordinal"));',
        'CREATE TABLE IF NOT EXISTS "telemetry_table__notes" ("owner" INTEGER, "ordinal" INTEGER, "value" TEXT, PRIMARY KEY("owner", "ordinal"));',
        'CREATE TABLE IF NOT EXISTS "telemetry_table__traces" ("owner" INTEGER, "ordinal" INTEGER, "kind" TEXT, "weight" INTEGER, PRIMARY KEY("owner", "ordinal"));',
    )
    DROP_TABLE_SQL = (
        'DROP TABLE IF EXISTS "telemetry_table__gauges";',
        'DROP TABLE IF EXISTS "telemetry_table__flags";',
        'DROP TABLE IF EXISTS "telemetry_table__samples";',
        'DROP TABLE IF EXISTS "telemetry_table__notes";',
        'DROP TABLE IF EXISTS "telemetry_table__traces";',
        'DROP TABLE IF EXISTS "telemetry_table";',
    )
    INSERT_SQL = 'INSERT INTO "telemetry_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") VALUES (?, ?, ?, ?, ?)'
    SELECT_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    UPDATE_SQL = 'UPDATE "telemetry_table" SET "label" = ?, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ORIGINATOR" = ? WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    DELETE_SQL = 'DELETE FROM "telemetry_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    LIST_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table"'
    LIST_PAGE_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table" LIMIT ? OFFSET ?'
