"""CRUDL data-access object for ``telemetry`` (table ``telemetry_table``).

Generated by harpia (python target) from the ``.harpia`` schema. Do not
edit. SQL dialect: ``sqlite`` (placeholder ``?``). The table
DDL is the one the C++ target declares for this message.

Deferred (not persisted by this DAO yet): telemetry_table__gauges, telemetry_table__flags, telemetry_table__samples, telemetry_table__notes, telemetry_table__traces
"""
from harpia_generated.protofiles.telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    telemetry,
)
from harpia_runtime.db.dao import Column, Dao


class telemetry_dao(Dao[telemetry]):
    """CRUDL over table ``telemetry_table`` for :class:`telemetry` messages."""

    MESSAGE = telemetry
    TABLE = 'telemetry_table'
    PK = 'ID_3ac5d8b36fc7dcfb70888145147ddfb7'
    COLUMNS = (
        Column('ID_3ac5d8b36fc7dcfb70888145147ddfb7', ('ID_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('label', ('label',)),
        Column('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ORIGINATOR', ('ORIGINATOR',)),
    )
    CREATE_TABLE_SQL = (
        'CREATE TABLE IF NOT EXISTS "telemetry_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "label" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR" TEXT);',
    )
    DROP_TABLE_SQL = (
        'DROP TABLE IF EXISTS "telemetry_table";',
    )
    INSERT_SQL = 'INSERT INTO "telemetry_table" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR") VALUES (?, ?, ?, ?, ?)'
    SELECT_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    UPDATE_SQL = 'UPDATE "telemetry_table" SET "label" = ?, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ORIGINATOR" = ? WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    DELETE_SQL = 'DELETE FROM "telemetry_table" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    LIST_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table"'
    LIST_PAGE_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" FROM "telemetry_table" LIMIT ? OFFSET ?'
