"""CRUDL data-access object for ``vip_users`` (table ``table_vip_users``).

Generated by harpia (python target) from the ``.harpia`` schema. Do not
edit. SQL dialect: ``sqlite`` (placeholder ``?``). The table
DDL is the one the C++ target declares for this message.

Deferred (not persisted by this DAO yet): none
"""
from harpia_generated.protofiles.vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    vip_users,
)
from harpia_runtime.db.dao import Column, Dao


class vip_users_dao(Dao[vip_users]):
    """CRUDL over table ``table_vip_users`` for :class:`vip_users` messages."""

    MESSAGE = vip_users
    TABLE = 'table_vip_users'
    PK = 'ID_3ac5d8b36fc7dcfb70888145147ddfb7'
    COLUMNS = (
        Column('ID_3ac5d8b36fc7dcfb70888145147ddfb7', ('ID_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('name', ('name',)),
        Column('family', ('family',)),
        Column('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7', ('STATUS_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ERROR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
        Column('ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7', ('ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7',)),
    )
    CREATE_TABLE_SQL = (
        'CREATE TABLE IF NOT EXISTS "table_vip_users" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY, "name" TEXT, "family" TEXT, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT, "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT);',
    )
    DROP_TABLE_SQL = (
        'DROP TABLE IF EXISTS "table_vip_users";',
    )
    INSERT_SQL = 'INSERT INTO "table_vip_users" ("ID_3ac5d8b36fc7dcfb70888145147ddfb7", "name", "family", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7") VALUES (?, ?, ?, ?, ?, ?)'
    SELECT_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "name", "family", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" FROM "table_vip_users" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    UPDATE_SQL = 'UPDATE "table_vip_users" SET "name" = ?, "family" = ?, "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" = ?, "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" = ? WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    DELETE_SQL = 'DELETE FROM "table_vip_users" WHERE "ID_3ac5d8b36fc7dcfb70888145147ddfb7" = ?'
    LIST_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "name", "family", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" FROM "table_vip_users"'
    LIST_PAGE_SQL = 'SELECT "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "name", "family", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" FROM "table_vip_users" LIMIT ? OFFSET ?'
