// station -- the reference system's DB server (multi-system-reference /
// reference-system task 3). The only program that owns the database.
//
//   station --listen 0.0.0.0:50051 --db "host=... dbname=..." --pool 16 \
//           --certs <dir with ca.pem server.pem server_key.pem>
//   station --listen 127.0.0.1:50051 --db sqlite:/var/lib/ms/station.db ...
//
// Environment (read by the generated gate at startup): HARPIA_RBAC_MAP (CN ->
// role), HARPIA_SESSION_KEY (bearer-token signing key), optionally
// HARPIA_SESSION_TTL / HARPIA_SESSION_REVOCATIONS. See README.md.
//
// What is generated and what is this program's own code:
//   generated  -- every <name>_service (CRUDL over the pool, the RBAC +
//                 bearer-session gate, PooledSession borrowing), the mTLS
//                 server credentials (fail-safe: incomplete PEM files throw),
//                 the schema migrations, open_sqlite_pool /
//                 refuse_sqlite_memory_pool.
//   here       -- argument parsing, opening the pool, the ServerBuilder, the
//                 shutdown handling and the stats line. station registers the
//                 generated services on its own grpc::ServerBuilder (the
//                 USAGE.md section 7.5 alternative to the generated
//                 GrpcServer) for one reason: the per-10 s stats need a gRPC
//                 server interceptor, and GrpcServer keeps its builder private.
//
// Portability: no POSIX-only API outside #ifdef. The only platform-specific
// code is the shutdown hook (SetConsoleCtrlHandler on Windows, SIGINT/SIGTERM
// elsewhere); see README.md "Windows notes".
#include "harpia_ms_server.h"   // generated by CMake: the hash-named headers

#include <atomic>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <string>
#include <thread>
#include <vector>

#include <grpcpp/grpcpp.h>
#include <grpcpp/support/server_interceptor.h>
#include <soci/soci.h>
#ifdef HARPIA_MS_WITH_POSTGRESQL
#include <soci/postgresql/soci-postgresql.h>
#endif
#ifdef HARPIA_MS_WITH_SQLITE
#include <soci/sqlite3/soci-sqlite3.h>
#endif

#ifdef _WIN32
#include <windows.h>
#else
#include <csignal>
#endif

namespace {

std::atomic<bool> g_stop{false};

#ifdef _WIN32
BOOL WINAPI on_console_event(DWORD) {
    g_stop = true;
    return TRUE;
}
void install_shutdown_hook() { SetConsoleCtrlHandler(on_console_event, TRUE); }
#else
extern "C" void on_signal(int) { g_stop = true; }
void install_shutdown_hook() {
    std::signal(SIGINT, on_signal);
    std::signal(SIGTERM, on_signal);
}
#endif

// ---- stats -----------------------------------------------------------------
// calls   = RPCs that reached the server in the window
// errors  = RPCs answered with a non-OK status in the window
// sessions = distinct bearer tokens presented in the window (tokens are
//            stateless, so "active" means "used in the last 10 s")
struct Stats {
    std::atomic<long long> calls{0}, errors{0}, total_calls{0}, total_errors{0};
    std::mutex mu;
    std::set<std::string> tokens;

    void call(const std::string& token) {
        ++calls;
        ++total_calls;
        if (!token.empty()) {
            std::lock_guard<std::mutex> lk(mu);
            tokens.insert(token);
        }
    }
    void error() { ++errors; ++total_errors; }
    std::string line(int seconds) {
        std::size_t sessions;
        {
            std::lock_guard<std::mutex> lk(mu);
            sessions = tokens.size();
            tokens.clear();
        }
        return "station: last " + std::to_string(seconds) + "s calls=" +
               std::to_string(calls.exchange(0)) + " sessions=" +
               std::to_string(sessions) + " errors=" + std::to_string(errors.exchange(0)) +
               " (total calls=" + std::to_string(total_calls.load()) +
               " errors=" + std::to_string(total_errors.load()) + ")";
    }
};

class CountingInterceptor : public ::grpc::experimental::Interceptor {
public:
    explicit CountingInterceptor(Stats& s) : s_(s) {}
    void Intercept(::grpc::experimental::InterceptorBatchMethods* m) override {
        using HP = ::grpc::experimental::InterceptionHookPoints;
        if (m->QueryInterceptionHookPoint(HP::POST_RECV_INITIAL_METADATA)) {
            std::string token;
            if (auto* md = m->GetRecvInitialMetadata()) {
                auto it = md->find("authorization");
                if (it != md->end()) token.assign(it->second.data(), it->second.size());
            }
            s_.call(token);
        }
        if (m->QueryInterceptionHookPoint(HP::PRE_SEND_STATUS)) {
            if (m->GetSendStatus().error_code() != ::grpc::StatusCode::OK) s_.error();
        }
        m->Proceed();
    }

private:
    Stats& s_;
};

class CountingFactory : public ::grpc::experimental::ServerInterceptorFactoryInterface {
public:
    explicit CountingFactory(Stats& s) : s_(s) {}
    ::grpc::experimental::Interceptor* CreateServerInterceptor(
            ::grpc::experimental::ServerRpcInfo*) override {
        return new CountingInterceptor(s_);
    }

private:
    Stats& s_;
};

// ---- arguments ---------------------------------------------------------------
struct Args {
    std::string listen = "0.0.0.0:50051";
    std::string db;
    int pool = 16;
    std::string certs;            // dir with ca.pem / server.pem / server_key.pem
    int lease_timeout_ms = 2000;
    int stats_every_s = 10;
};

int usage(const char* why) {
    std::cerr << "station: " << why << "\n"
              << "usage: station --db <\"postgres conninfo\" | sqlite:<file>> "
                 "--certs <dir> [--listen host:port] [--pool N] "
                 "[--lease-timeout-ms N] [--stats-every S]\n";
    return 2;
}

bool parse(int argc, char** argv, Args* a, std::string* err) {
    for (int i = 1; i < argc; ++i) {
        const std::string k = argv[i];
        auto val = [&](std::string* out) {
            if (i + 1 >= argc) { *err = k + " needs a value"; return false; }
            *out = argv[++i];
            return true;
        };
        std::string v;
        if (k == "--listen") { if (!val(&a->listen)) return false; }
        else if (k == "--db") { if (!val(&a->db)) return false; }
        else if (k == "--certs") { if (!val(&a->certs)) return false; }
        else if (k == "--pool") { if (!val(&v)) return false; a->pool = std::atoi(v.c_str()); }
        else if (k == "--lease-timeout-ms") { if (!val(&v)) return false; a->lease_timeout_ms = std::atoi(v.c_str()); }
        else if (k == "--stats-every") { if (!val(&v)) return false; a->stats_every_s = std::atoi(v.c_str()); }
        else { *err = "unknown argument " + k; return false; }
    }
    if (a->db.empty()) { *err = "--db is required"; return false; }
    if (a->pool < 1) { *err = "--pool must be >= 1"; return false; }
    if (a->stats_every_s < 1) a->stats_every_s = 10;
    return true;
}

bool open_pool(::soci::connection_pool& pool, const Args& a, std::string* err) {
    const std::string kSqlite = "sqlite:";
    if (a.db.compare(0, kSqlite.size(), kSqlite) == 0) {
#ifdef HARPIA_MS_WITH_SQLITE
        if (std::strcmp(HARPIA_MS_DB_DIALECT, "sqlite") != 0) {
            *err = "this station was generated for " + std::string(HARPIA_MS_DB_DIALECT) +
                   " (HARPIA_DB_BACKEND); its migrations can't run on SQLite";
            return false;
        }
        ::harpia::db::open_sqlite_pool(pool, static_cast<std::size_t>(a.pool),
                                       ::soci::sqlite3, a.db.substr(kSqlite.size()));
        return true;
#else
        *err = "built without SQLite support";
        return false;
#endif
    }
#ifdef HARPIA_MS_WITH_POSTGRESQL
    if (std::strcmp(HARPIA_MS_DB_DIALECT, "postgresql") != 0) {
        *err = "this station was generated for " + std::string(HARPIA_MS_DB_DIALECT) +
               " (HARPIA_DB_BACKEND); regenerate with HARPIA_DB_BACKEND=postgresql "
               "for a PostgreSQL --db";
        return false;
    }
    for (int i = 0; i < a.pool; ++i) pool.at(static_cast<std::size_t>(i)).open(::soci::postgresql, a.db);
    return true;
#else
    *err = "built without PostgreSQL support";
    return false;
#endif
}

}  // namespace

int main(int argc, char** argv) {
    Args a;
    std::string err;
    if (!parse(argc, argv, &a, &err)) return usage(err.c_str());
    if (std::getenv("HARPIA_RBAC_MAP") == nullptr)
        std::cerr << "station: warning: HARPIA_RBAC_MAP is not set -- every identity is denied\n";
    if (std::getenv("HARPIA_SESSION_KEY") == nullptr)
        std::cerr << "station: warning: HARPIA_SESSION_KEY is not set -- no session tokens can be issued\n";

    ::soci::connection_pool pool(static_cast<std::size_t>(a.pool));
    try {
        if (!open_pool(pool, a, &err)) return usage(err.c_str());
        ::harpia::db::refuse_sqlite_memory_pool(pool, a.lease_timeout_ms);
        ::harpia::db::PooledSession s(nullptr, &pool, a.lease_timeout_ms);
        if (!s.ok()) { std::cerr << "station: no database session for the migrations\n"; return 3; }
        if (!harpia_ms::migrate_all(s.session())) { std::cerr << "station: migration failed\n"; return 3; }
    } catch (const std::exception& e) {
        std::cerr << "station: database: " << e.what() << "\n";
        return 3;
    }

    Stats stats;
    std::vector<std::unique_ptr<::grpc::Service>> services;
    harpia_ms::make_services(pool, a.lease_timeout_ms, &services);

    ::grpc::ServerBuilder builder;
    const std::string dir = a.certs.empty() ? std::string(".") : a.certs;
    try {
        builder.AddListeningPort(
            a.listen,
            ::harpia::grpc_transport::server_credentials(
                ::harpia::grpc_transport::kHardeningRequired,
                {dir + "/ca.pem", dir + "/server.pem", dir + "/server_key.pem"}));
    } catch (const std::exception& e) {
        std::cerr << "station: " << e.what() << "\n";
        return 4;
    }
    for (auto& svc : services) builder.RegisterService(svc.get());
    std::vector<std::unique_ptr<::grpc::experimental::ServerInterceptorFactoryInterface>> creators;
    creators.push_back(std::make_unique<CountingFactory>(stats));
    builder.experimental().SetInterceptorCreators(std::move(creators));

    std::unique_ptr<::grpc::Server> server = builder.BuildAndStart();
    if (!server) {
        std::cerr << "station: could not listen on " << a.listen << "\n";
        return 5;
    }
    install_shutdown_hook();
    std::cout << "station: listening on " << a.listen << " (mTLS "
              << (::harpia::grpc_transport::kHardeningRequired ? "required" : "OFF")
              << ", pool " << a.pool << ", " << HARPIA_MS_DB_DIALECT << ")" << std::endl;

    auto next = std::chrono::steady_clock::now() + std::chrono::seconds(a.stats_every_s);
    while (!g_stop) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        if (std::chrono::steady_clock::now() >= next) {
            std::cout << stats.line(a.stats_every_s) << std::endl;
            next += std::chrono::seconds(a.stats_every_s);
        }
    }
    std::cout << "station: shutting down" << std::endl;
    server->Shutdown(std::chrono::system_clock::now() + std::chrono::seconds(5));
    std::cout << stats.line(a.stats_every_s) << std::endl;
    return 0;
}
