"""SOAP endpoint for ``alarm_event`` (table ``alarm_event_table``): ``POST <base>/alarm_event``.

Generated by harpia (python target), the Python side of the C++
``soap/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_soap.h``. Do not edit. Operations ``get`` / ``set`` /
``update`` / ``delete``; envelopes and status codes are documented in
:mod:`harpia_runtime.http.soap_endpoint`. The WSDL is the language-neutral
``wsdl/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl`` the generator already emits.

Access gate: the flat generated credential -- ``<credentials><user>alarm_event</user><pswd>hash</pswd></credentials>`` in the SOAP Header, else a 401 Fault.
"""
from harpia_generated.db.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    alarm_event_dao,
)
from harpia_generated.protofiles.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    alarm_event,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.router import Router
from harpia_runtime.http.soap_endpoint import flat_soap_gate, register_soap

#: the WSDL describing this endpoint (relative to the generation output dir)
WSDL = 'wsdl/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl'

#: the flat generated credential (SOAP Header <credentials>)
EARLY_GATE = flat_soap_gate('alarm_event', '3ac5d8b36fc7dcfb70888145147ddfb7')


def register(router: Router, pool: ConnectionPool, base: str = "/soap") -> None:
    """Register ``alarm_event``'s SOAP endpoint under ``base`` on ``router``."""
    register_soap(router, pool, base, 'alarm_event', alarm_event_dao, alarm_event, early_gate=EARLY_GATE)
