"""SOAP endpoint for ``telemetry`` (table ``telemetry_table``): ``POST <base>/telemetry``.

Generated by harpia (python target), the Python side of the C++
``soap/telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_soap.h``. Do not edit. Operations ``get`` / ``set`` /
``update`` / ``delete``; envelopes and status codes are documented in
:mod:`harpia_runtime.http.soap_endpoint`. The WSDL is the language-neutral
``wsdl/telemetry_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl`` the generator already emits.

Access gate: the flat generated credential -- ``<credentials><user>telemetry</user><pswd>hash</pswd></credentials>`` in the SOAP Header, else a 401 Fault.
"""
from harpia_generated.db.telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    telemetry_dao,
)
from harpia_generated.protofiles.telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    telemetry,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.router import Router
from harpia_runtime.http.soap_endpoint import flat_soap_gate, register_soap

#: the WSDL describing this endpoint (relative to the generation output dir)
WSDL = 'wsdl/telemetry_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl'

#: the flat generated credential (SOAP Header <credentials>)
EARLY_GATE = flat_soap_gate('telemetry', '3ac5d8b36fc7dcfb70888145147ddfb7')


def register(router: Router, pool: ConnectionPool, base: str = "/soap") -> None:
    """Register ``telemetry``'s SOAP endpoint under ``base`` on ``router``."""
    register_soap(router, pool, base, 'telemetry', telemetry_dao, telemetry, early_gate=EARLY_GATE)
