"""SOAP endpoint for ``vault`` (table ``vault_table``): ``POST <base>/vault``.

Generated by harpia (python target), the Python side of the C++
``soap/vault_3ac5d8b36fc7dcfb70888145147ddfb7_soap.h``. Do not edit. Operations ``get`` / ``set`` /
``update`` / ``delete``; envelopes and status codes are documented in
:mod:`harpia_runtime.http.soap_endpoint`. The WSDL is the language-neutral
``wsdl/vault_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl`` the generator already emits.

Access gate: RBAC (``protected``, or hardened and not ``open``) -- the verified client-certificate CN mapped to a role by ``HARPIA_RBAC_MAP`` (:mod:`harpia_runtime.rbac`); checked once the operation is parsed; a 401 / 403 ``Client.Authentication`` Fault.
"""
from harpia_generated.db.vault_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    vault_dao,
)
from harpia_generated.protofiles.vault_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    vault,
)
from harpia_runtime.db.pool import ConnectionPool
from harpia_runtime.http.router import Router
from harpia_runtime.http.soap_endpoint import register_soap
from harpia_runtime.rbac_gates import soap_rbac_gate

#: the WSDL describing this endpoint (relative to the generation output dir)
WSDL = 'wsdl/vault_3ac5d8b36fc7dcfb70888145147ddfb7.wsdl'

#: RBAC on the verified client-certificate CN, checked after the operation
#: is parsed (harpia_runtime.rbac_gates)
OP_GATE = soap_rbac_gate('vault')


def register(router: Router, pool: ConnectionPool, base: str = "/soap") -> None:
    """Register ``vault``'s SOAP endpoint under ``base`` on ``router``."""
    register_soap(router, pool, base, 'vault', vault_dao, vault, op_gate=OP_GATE)
