// Generated by harpia Stage 14 (unit tests). Do not edit.
//
// Unit tests for the generated top_users message, CRUDL DAO and SOAP access:
//   14.1 simple access     -- setter/getter round-trips for every scalar field
//   14.2 database          -- create/read/update/list/remove over in-memory SQLite
//   14.3 access rights      -- the SOAP credential gate accepts the right password
//                             and rejects a wrong/absent one
//   14.4 access modifiers   -- schema constraints from the modifiers are enforced
//                             (PRIMARY KEY uniqueness rejects a duplicate row)
//   14.5 json parser        -- to_json/from_json round-trips the message and
//                             is_valid_json accepts good JSON, rejects garbage
//   14.6 xml parser         -- to_xml/from_xml round-trips the message and
//                             from_xml rejects garbage
//
// Each check returns a distinct non-zero code so a CTest failure points at the
// exact assertion; main() returns 0 only when every check passes.
#include "db/top_users_734126ee6efdfbd64a1678bf49ee9683_crudl.h"
#include "soap/top_users_734126ee6efdfbd64a1678bf49ee9683_soap.h"
#include "json/top_users_734126ee6efdfbd64a1678bf49ee9683_json.h"
#include "xml/top_users_734126ee6efdfbd64a1678bf49ee9683_xml.h"

#include <cstdint>
#include <string>
#include <vector>

namespace {

int simple_access() {
    ::top_users m;
    m.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    m.set_sponsor("sponsor_a");
    m.set_name("name_a");
    m.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_a");
    m.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_a");
    m.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_a");
    if (m.id_734126ee6efdfbd64a1678bf49ee9683() != 1) return 10;
    if (m.sponsor() != "sponsor_a") return 11;
    if (m.name() != "name_a") return 12;
    if (m.status_734126ee6efdfbd64a1678bf49ee9683() != "status_734126ee6efdfbd64a1678bf49ee9683_a") return 13;
    if (m.error_734126ee6efdfbd64a1678bf49ee9683() != "error_734126ee6efdfbd64a1678bf49ee9683_a") return 14;
    if (m.originator_734126ee6efdfbd64a1678bf49ee9683() != "originator_734126ee6efdfbd64a1678bf49ee9683_a") return 15;
    return 0;
}

int database_roundtrip() {
    ::sqlite3* db = nullptr;
    if (::sqlite3_open(":memory:", &db) != SQLITE_OK) return 20;
    harpia::db::top_users_dao dao(db);
    if (!dao.create_table()) return 21;

    // create + read back row 1
    ::top_users a;
    a.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    a.set_sponsor("sponsor_a");
    a.set_name("name_a");
    a.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_a");
    if (!dao.create(a)) return 22;
    ::top_users got;
    if (!dao.read(1, &got)) return 23;
    if (got.sponsor() != "sponsor_a") return 24;
    if (got.name() != "name_a") return 24;
    if (got.status_734126ee6efdfbd64a1678bf49ee9683() != "status_734126ee6efdfbd64a1678bf49ee9683_a") return 24;
    if (got.error_734126ee6efdfbd64a1678bf49ee9683() != "error_734126ee6efdfbd64a1678bf49ee9683_a") return 24;
    if (got.originator_734126ee6efdfbd64a1678bf49ee9683() != "originator_734126ee6efdfbd64a1678bf49ee9683_a") return 24;

    // update an existing row
    ::top_users upd = a;
    upd.set_sponsor("sponsor_u");
    if (!dao.update(upd)) return 25;
    ::top_users got2;
    if (!dao.read(1, &got2)) return 26;
    if (got2.sponsor() != "sponsor_u") return 27;

    // a second row, then list + delete
    ::top_users b;
    b.set_id_734126ee6efdfbd64a1678bf49ee9683(2);
    b.set_sponsor("sponsor_b");
    b.set_name("name_b");
    b.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_b");
    b.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_b");
    b.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_b");
    if (!dao.create(b)) return 28;
    std::vector<::top_users> all;
    if (!dao.list(&all) || all.size() != 2) return 29;
    if (!dao.remove(1)) return 30;
    ::top_users gone;
    if (dao.read(1, &gone)) return 31;

    ::sqlite3_close(db);
    return 0;
}

int access_rights() {
    const std::string good = "<soap:Envelope><soap:Header><credentials><user>top_users</user><pswd>734126ee6efdfbd64a1678bf49ee9683</pswd></credentials></soap:Header><soap:Body/></soap:Envelope>";
    const std::string wrong = "<soap:Envelope><soap:Header><credentials><user>top_users</user><pswd>wrong-password</pswd></credentials></soap:Header><soap:Body/></soap:Envelope>";
    const std::string none = "<soap:Envelope><soap:Body/></soap:Envelope>";
    if (!harpia::soap::authorized_top_users(good)) return 50;
    if (harpia::soap::authorized_top_users(wrong)) return 51;
    if (harpia::soap::authorized_top_users(none)) return 52;
    return 0;
}

int access_modifiers() {
    ::sqlite3* db = nullptr;
    if (::sqlite3_open(":memory:", &db) != SQLITE_OK) return 40;
    harpia::db::top_users_dao dao(db);
    if (!dao.create_table()) return 41;
    ::top_users a;
    a.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    a.set_sponsor("sponsor_a");
    a.set_name("name_a");
    a.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_a");
    if (!dao.create(a)) return 42;
    // PRIMARY KEY is unique: a duplicate key must be rejected
    ::top_users dup;
    dup.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    dup.set_sponsor("sponsor_b");
    dup.set_name("name_b");
    dup.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_b");
    dup.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_b");
    dup.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_b");
    if (dao.create(dup)) return 43;
    ::sqlite3_close(db);
    return 0;
}

int json_parser() {
    ::top_users a;
    a.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    a.set_sponsor("sponsor_a");
    a.set_name("name_a");
    a.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_a");
    std::string js;
    if (!harpia::json::to_json(a, &js)) return 60;
    ::top_users b;
    if (!harpia::json::from_json(js, &b)) return 61;
    if (b.id_734126ee6efdfbd64a1678bf49ee9683() != 1) return 62;
    if (b.sponsor() != "sponsor_a") return 62;
    if (b.name() != "name_a") return 62;
    if (b.status_734126ee6efdfbd64a1678bf49ee9683() != "status_734126ee6efdfbd64a1678bf49ee9683_a") return 62;
    if (b.error_734126ee6efdfbd64a1678bf49ee9683() != "error_734126ee6efdfbd64a1678bf49ee9683_a") return 62;
    if (b.originator_734126ee6efdfbd64a1678bf49ee9683() != "originator_734126ee6efdfbd64a1678bf49ee9683_a") return 62;
    if (!harpia::json::is_valid_json(js)) return 63;
    if (harpia::json::is_valid_json("this is not json")) return 64;
    return 0;
}

int xml_parser() {
    ::top_users a;
    a.set_id_734126ee6efdfbd64a1678bf49ee9683(1);
    a.set_sponsor("sponsor_a");
    a.set_name("name_a");
    a.set_status_734126ee6efdfbd64a1678bf49ee9683("status_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_error_734126ee6efdfbd64a1678bf49ee9683("error_734126ee6efdfbd64a1678bf49ee9683_a");
    a.set_originator_734126ee6efdfbd64a1678bf49ee9683("originator_734126ee6efdfbd64a1678bf49ee9683_a");
    const std::string xs = ::harpia::xml::to_xml(a);
    if (xs.empty()) return 70;
    ::top_users b;
    if (!::harpia::xml::from_xml(xs, &b)) return 71;
    if (b.id_734126ee6efdfbd64a1678bf49ee9683() != 1) return 72;
    if (b.sponsor() != "sponsor_a") return 72;
    if (b.name() != "name_a") return 72;
    if (b.status_734126ee6efdfbd64a1678bf49ee9683() != "status_734126ee6efdfbd64a1678bf49ee9683_a") return 72;
    if (b.error_734126ee6efdfbd64a1678bf49ee9683() != "error_734126ee6efdfbd64a1678bf49ee9683_a") return 72;
    if (b.originator_734126ee6efdfbd64a1678bf49ee9683() != "originator_734126ee6efdfbd64a1678bf49ee9683_a") return 72;
    ::top_users c;
    if (::harpia::xml::from_xml("not xml at all", &c)) return 73;
    return 0;
}

}  // namespace

int main() {
    if (int rc = simple_access()) return rc;
    if (int rc = database_roundtrip()) return rc;
    if (int rc = access_rights()) return rc;
    if (int rc = access_modifiers()) return rc;
    if (int rc = json_parser()) return rc;
    if (int rc = xml_parser()) return rc;
    return 0;
}
