// Generated by harpia Stage 8 (schema migration / version transforms). Do not edit.
#ifndef HARPIA_MIGRATE_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_MIGRATE_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7

#include <functional>
#include <map>
#include <set>
#include <string>

#include <soci/soci.h>
#include "db/telemetry_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"

// Schema migration for telemetry (spec 8 / 7.2 "validation/transformative functions
// for versions"). Brings an existing database up to the current schema version
// (3ac5d8b36fc7dcfb70888145147ddfb7) and records it in "_harpia_schema_version":
//   - RENAMEs a "<table>__<old>" repeated/map child table to "<table>__<new>"
//     when the field carries renamed_from[<old>] -- FIRST, so create_table
//     below finds the populated table instead of making an empty new one,
//   - ensures the table (and its map/repeated child tables) exist,
//   - RENAMEs a column carrying the DSL's renamed_from[<old>] modifier (both
//     names are known at generation time), before anything else runs,
//   - adds any column present in the current schema but missing from a live table
//     an older generated version created (additive evolution via ALTER TABLE),
//   - runs the caller-supplied data_transform hook, if any (see below),
//   - DROPs any column a live table has that the current schema no longer
//     declares. This is an IMPLICIT, UNCONDITIONAL diff, not a marker-driven
//     one: there is no schema history, so any unrecognized live column is
//     dropped, including one added out-of-band.
//   - RETYPEs any column whose live SQL type no longer matches the current
//     schema's declared type for that same name. Unlike a rename, this needs
//     no DSL marker -- the name is unchanged, so a mismatch is unambiguous.
//     Runs last among the structural steps, against the table already
//     stabilized by the rename/add/drop steps above.
//   - DROPs any "<table>__*" child table the current schema no longer declares
//     (a repeated/map field removed between versions) -- same implicit,
//     no-schema-history diff as the column drop -- and RETYPEs a repeated-
//     scalar child table's "value" column when its element type changed.
//   - stamps the current version hash.
// Cross-version DATA transforms (deriving one column's value from another,
// not just moving/CASTing structure) are handled via an optional
// data_transform hook -- harpia has no schema history, so it cannot know
// what a transform should compute, only guarantee a stable extension point
// and when it runs. It runs AFTER add (so any new destination column already
// exists) and BEFORE drop (so an old source column being retired is still
// there to read) -- e.g. splitting a retiring "full_name" into new
// "first_name"/"last_name" columns needs exactly this ordering. Pass
// nothing for today's plaintext behavior; the caller's lambda should be
// idempotent (e.g. guard with a WHERE clause) since migrate_telemetry may run
// on every startup.
//
// SOCI-based (works on any backend); the SQL dialect (version table, column
// introspection, ALTER/RENAME/DROP/RETYPE, version-stamp upsert) comes from
// the harpia DbBackend.
namespace harpia {
namespace db {

inline bool migrate_telemetry(::soci::session& db,
                           std::function<void(::soci::session&)> data_transform = nullptr) {
    try {
        db << "CREATE TABLE IF NOT EXISTS \"_harpia_schema_version\" (\"name\" TEXT PRIMARY KEY, \"version\" TEXT);";

        // child tables ("<table>__*", one per repeated/map field) the live
        // database currently has -- for the child-table rename below and the
        // orphan reap further down (Track H.1). Same dialect-uniform shape
        // as the column introspection: one selected column, a table name.
        std::set<std::string> _child_have;
        {
            std::string _ctn; ::soci::indicator _ctni;
            ::soci::statement _cts = (db.prepare << "SELECT \"name\" FROM sqlite_master WHERE type = 'table' AND substr(\"name\", 1, 17) = 'telemetry_table__';",
                                     ::soci::into(_ctn, _ctni));
            _cts.execute();
            while (_cts.fetch()) { if (_ctni == ::soci::i_ok) _child_have.insert(_ctn); }
        }
        // child-table renames: a repeated/map field carrying renamed_from[<old>]
        // moves its "<table>__<old>" child table to "<table>__<new>" BEFORE
        // create_table's CREATE IF NOT EXISTS would leave an empty new one
        // beside the populated old. Idempotent, like the column rename above.
        if (_child_have.count("telemetry_table__old_notes") && !_child_have.count("telemetry_table__notes")) {
            db << "ALTER TABLE \"telemetry_table__old_notes\" RENAME TO \"telemetry_table__notes\";";
            _child_have.erase("telemetry_table__old_notes"); _child_have.insert("telemetry_table__notes");
        }
        // ensure the table + its map/repeated child tables exist at the current schema
        ::harpia::db::telemetry_dao dao(db);
        if (!dao.create_table()) return false;

        // columns the live table currently has (dialect-uniform: the query's one
        // selected column is each existing column's name)
        std::set<std::string> have;
        {
            std::string _cn; ::soci::indicator _ci;
            ::soci::statement _cs = (db.prepare << "SELECT \"name\" FROM pragma_table_info('telemetry_table');",
                                     ::soci::into(_cn, _ci));
            _cs.execute();
            while (_cs.fetch()) { if (_ci == ::soci::i_ok) have.insert(_cn); }
        }

        // renames: old column name -> new, ahead of add/drop so they see the
        // corrected column set. Idempotent: a no-op once the old name is gone
        // (a second migrate_telemetry call, or a table that never had it).

        // additive migration: add any column missing from an older table version
        if (!have.count("label")) {
            db << "ALTER TABLE \"telemetry_table\" ADD COLUMN \"label\" TEXT;";
        }
        if (!have.count("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7")) {
            db << "ALTER TABLE \"telemetry_table\" ADD COLUMN \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT;";
        }
        if (!have.count("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7")) {
            db << "ALTER TABLE \"telemetry_table\" ADD COLUMN \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT;";
        }
        if (!have.count("ORIGINATOR")) {
            db << "ALTER TABLE \"telemetry_table\" ADD COLUMN \"ORIGINATOR\" TEXT;";
        }
        // caller-supplied cross-version data transform (see the header
        // comment above for why this runs here: after add, before drop).
        // No-op when not supplied.
        if (data_transform) data_transform(db);
        // non-additive: drop any live column the current schema no longer
        // declares (see the header comment above for the implicit-diff caveat)
        {
            static const std::set<std::string> _current = { "ID_3ac5d8b36fc7dcfb70888145147ddfb7", "label", "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7", "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7", "ORIGINATOR" };
            for (auto _hit = have.begin(); _hit != have.end(); ) {
                if (!_current.count(*_hit)) {
                    const std::string& _dc = *_hit;
                    db << "ALTER TABLE \"telemetry_table\" DROP COLUMN \"" + _dc + "\";";
                    _hit = have.erase(_hit);
                } else {
                    ++_hit;
                }
            }
        }
        // live column TYPES (dialect-uniform: two selected columns, name then
        // type), queried AFTER the rename/add/drop steps above so it reflects
        // the table's now-stabilized current column set -- a mismatch here
        // can only be a stale type on a pre-existing column.
        std::map<std::string, std::string> have_types;
        {
            std::string _tn, _tt; ::soci::indicator _tni, _tti;
            ::soci::statement _ts = (db.prepare << "SELECT \"name\", \"type\" FROM pragma_table_info('telemetry_table');",
                                     ::soci::into(_tn, _tni), ::soci::into(_tt, _tti));
            _ts.execute();
            while (_ts.fetch()) {
                if (_tni == ::soci::i_ok && _tti == ::soci::i_ok) have_types[_tn] = _tt;
            }
        }
        // non-additive: bring any column whose live type differs from the
        // current schema to the current type (see the header comment above)
        {
        bool _needs_retype = false;
            if (have_types.count("ID_3ac5d8b36fc7dcfb70888145147ddfb7") && have_types["ID_3ac5d8b36fc7dcfb70888145147ddfb7"] != "INTEGER") _needs_retype = true;
            if (have_types.count("label") && have_types["label"] != "TEXT") _needs_retype = true;
            if (have_types.count("STATUS_3ac5d8b36fc7dcfb70888145147ddfb7") && have_types["STATUS_3ac5d8b36fc7dcfb70888145147ddfb7"] != "TEXT") _needs_retype = true;
            if (have_types.count("ERROR_3ac5d8b36fc7dcfb70888145147ddfb7") && have_types["ERROR_3ac5d8b36fc7dcfb70888145147ddfb7"] != "TEXT") _needs_retype = true;
            if (have_types.count("ORIGINATOR") && have_types["ORIGINATOR"] != "TEXT") _needs_retype = true;
        if (_needs_retype) {
            db << "CREATE TABLE \"telemetry_table__retype_tmp\" (\"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" INTEGER PRIMARY KEY, \"label\" TEXT, \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT, \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\" TEXT, \"ORIGINATOR\" TEXT);";
            db << "INSERT INTO \"telemetry_table__retype_tmp\" (\"ID_3ac5d8b36fc7dcfb70888145147ddfb7\", \"label\", \"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\", \"ORIGINATOR\") SELECT CAST(\"ID_3ac5d8b36fc7dcfb70888145147ddfb7\" AS INTEGER), CAST(\"label\" AS TEXT), CAST(\"STATUS_3ac5d8b36fc7dcfb70888145147ddfb7\" AS TEXT), CAST(\"ERROR_3ac5d8b36fc7dcfb70888145147ddfb7\" AS TEXT), CAST(\"ORIGINATOR\" AS TEXT) FROM \"telemetry_table\";";
            db << "DROP TABLE \"telemetry_table\";";
            db << "ALTER TABLE \"telemetry_table__retype_tmp\" RENAME TO \"telemetry_table\";";
        }
        }
        // non-additive (child tables, Track H.1): reap any "<table>__*" child
        // table the current schema no longer declares -- a repeated/map field
        // removed between versions -- then bring a repeated-scalar child
        // table's "value" column to the current element type. Implicit,
        // unconditional diff, same no-schema-history caveat as the column
        // drop above; runs after the main table has been stabilized.
        {
            static const std::set<std::string> _child_current = { "telemetry_table__samples", "telemetry_table__notes" };
            for (auto _cit = _child_have.begin(); _cit != _child_have.end(); ) {
                if (!_child_current.count(*_cit)) {
                    const std::string& _dct = *_cit;
                    db << "DROP TABLE \"" + _dct + "\";";
                    _cit = _child_have.erase(_cit);
                } else {
                    ++_cit;
                }
            }
        }
        {
            std::map<std::string, std::string> _rct;
            {
                std::string _rn, _rt; ::soci::indicator _rni, _rti;
                ::soci::statement _rs = (db.prepare << "SELECT \"name\", \"type\" FROM pragma_table_info('telemetry_table__samples');",
                                         ::soci::into(_rn, _rni), ::soci::into(_rt, _rti));
                _rs.execute();
                while (_rs.fetch()) { if (_rni == ::soci::i_ok && _rti == ::soci::i_ok) _rct[_rn] = _rt; }
            }
            if (_rct.count("value") && _rct["value"] != "INTEGER") {
                db << "CREATE TABLE \"telemetry_table__samples__retype_tmp\" (\"owner\" INTEGER, \"ordinal\" INTEGER, \"value\" INTEGER, PRIMARY KEY(\"owner\", \"ordinal\"));";
                db << "INSERT INTO \"telemetry_table__samples__retype_tmp\" (\"owner\", \"ordinal\", \"value\") SELECT \"owner\", \"ordinal\", CAST(\"value\" AS INTEGER) FROM \"telemetry_table__samples\";";
                db << "DROP TABLE \"telemetry_table__samples\";";
                db << "ALTER TABLE \"telemetry_table__samples__retype_tmp\" RENAME TO \"telemetry_table__samples\";";
            }
        }
        {
            std::map<std::string, std::string> _rct;
            {
                std::string _rn, _rt; ::soci::indicator _rni, _rti;
                ::soci::statement _rs = (db.prepare << "SELECT \"name\", \"type\" FROM pragma_table_info('telemetry_table__notes');",
                                         ::soci::into(_rn, _rni), ::soci::into(_rt, _rti));
                _rs.execute();
                while (_rs.fetch()) { if (_rni == ::soci::i_ok && _rti == ::soci::i_ok) _rct[_rn] = _rt; }
            }
            if (_rct.count("value") && _rct["value"] != "TEXT") {
                db << "CREATE TABLE \"telemetry_table__notes__retype_tmp\" (\"owner\" INTEGER, \"ordinal\" INTEGER, \"value\" TEXT, PRIMARY KEY(\"owner\", \"ordinal\"));";
                db << "INSERT INTO \"telemetry_table__notes__retype_tmp\" (\"owner\", \"ordinal\", \"value\") SELECT \"owner\", \"ordinal\", CAST(\"value\" AS TEXT) FROM \"telemetry_table__notes\";";
                db << "DROP TABLE \"telemetry_table__notes\";";
                db << "ALTER TABLE \"telemetry_table__notes__retype_tmp\" RENAME TO \"telemetry_table__notes\";";
            }
        }
        // stamp the current version
        db << "INSERT OR REPLACE INTO \"_harpia_schema_version\" (\"name\", \"version\") VALUES ('telemetry_table', '3ac5d8b36fc7dcfb70888145147ddfb7');";
        return true;
    } catch (const std::exception&) { return false; }
}

// The version hash this migration targets.
inline const char* version_telemetry() { return "3ac5d8b36fc7dcfb70888145147ddfb7"; }

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_MIGRATE_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7
