// Generated by harpia Stage 13 (gRPC service impl). Do not edit.
#ifndef HARPIA_GRPC_OUTPOST_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_GRPC_OUTPOST_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>
#include <vector>

#include <grpcpp/grpcpp.h>
#include <soci/soci.h>
#include "protofiles/outpost_3ac5d8b36fc7dcfb70888145147ddfb7_service.grpc.pb.h"
#include "db/outpost_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"

// gRPC service implementation for outpost, backed by the CRUDL DAO -- the RPCs of
// the generated outpost_Service are wired to create/read/list over SQLite:
//   push(msg)      -> dao.create(msg)             -> errorCode
//   pullByID(id)   -> dao.read(id)                -> outpost_Message (NOT_FOUND)
//   streamSrc()    -> dao.list() streamed back    -> stream outpost_Message
//                     (paginated via the request's offset/limit when limit>0)
//   heartBeat(hb)  -> echo                         (no CRUDL, unauthenticated)
// Construct with a soci::session the caller owns; register with a grpc::ServerBuilder,
// or let the generated grpc/grpc_server_bringup.h do it -- its
// harpia::grpc_transport::GrpcServer registers every service and picks mTLS vs
// insecure transport credentials from transport_hardening_required(compliance)
// at generation time (transport-authn epic, task 2; harpia_grpc_mtls.h).
//
// The data operations enforce the generated access credential (Stage 5): the
// call must carry x-user: outpost and x-pswd: 3ac5d8b36fc7dcfb70888145147ddfb7 metadata, or it is rejected
// with UNAUTHENTICATED (mirrors the SOAP <credentials> / REST X-User headers).
// heartBeat stays open as a liveness probe.
namespace harpia {
namespace grpc_svc {

class outpost_service final
    : public ::frameworkProtos::outpost_Service::Service {
public:
    explicit outpost_service(::soci::session& db) : db_(db) {}

    // True iff the call carries the correct credential metadata for outpost. A
    // null context (direct in-process call, no wire) is allowed; the wire path
    // always supplies a context.
    static bool authorized(::grpc::ServerContext* ctx) {
        if (!ctx) return true;
        const auto& md = ctx->client_metadata();
        auto u = md.find("x-user");
        auto p = md.find("x-pswd");
        return u != md.end() && p != md.end() &&
               ::std::string(u->second.data(), u->second.length()) == "outpost" &&
               ::std::string(p->second.data(), p->second.length()) == "3ac5d8b36fc7dcfb70888145147ddfb7";
    }

    ::grpc::Status push(::grpc::ServerContext* context,
                        const ::frameworkProtos::outpost_Message* request,
                        ::frameworkProtos::errorCode* response) override {
        if (!authorized(context)) {
            return ::grpc::Status(::grpc::StatusCode::UNAUTHENTICATED, "unauthorized");
        }
        ::harpia::db::outpost_dao dao(db_);
        const bool ok = dao.create(request->msg());
        response->set_code(ok ? 0 : 1);
        response->set_message(ok ? "ok" : "create failed");
        return ::grpc::Status::OK;
    }

    ::grpc::Status pullByID(::grpc::ServerContext* context,
                            const ::frameworkProtos::outpost_ID* request,
                            ::frameworkProtos::outpost_Message* response) override {
        if (!authorized(context)) {
            return ::grpc::Status(::grpc::StatusCode::UNAUTHENTICATED, "unauthorized");
        }
        ::harpia::db::outpost_dao dao(db_);
        if (!dao.read(request->id(), response->mutable_msg())) {
            return ::grpc::Status(::grpc::StatusCode::NOT_FOUND, "not found");
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status streamSrc(
            ::grpc::ServerContext* context,
            const ::frameworkProtos::outpost_Stream* request,
            ::grpc::ServerWriter< ::frameworkProtos::outpost_Message>* writer) override {
        if (!authorized(context)) {
            return ::grpc::Status(::grpc::StatusCode::UNAUTHENTICATED, "unauthorized");
        }
        ::harpia::db::outpost_dao dao(db_);
        std::vector< ::outpost> rows;
        // limit <= 0 (proto3 default / not set) means unbounded, matching
        // pre-pagination behavior.
        const bool paginated = request->limit() > 0;
        const bool ok = paginated
            ? dao.list(&rows, request->offset(), request->limit())
            : dao.list(&rows);
        if (!ok) {
            return ::grpc::Status(::grpc::StatusCode::INTERNAL, "list failed");
        }
        for (const auto& r : rows) {
            ::frameworkProtos::outpost_Message m;
            *m.mutable_msg() = r;
            writer->Write(m);
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status heartBeat(::grpc::ServerContext*,
                             const ::frameworkProtos::outpost_HeartBeat* request,
                             ::frameworkProtos::outpost_HeartBeat* response) override {
        *response = *request;
        return ::grpc::Status::OK;
    }

private:
    ::soci::session& db_;
};

}  // namespace grpc_svc
}  // namespace harpia

#endif  // HARPIA_GRPC_OUTPOST_3ac5d8b36fc7dcfb70888145147ddfb7
