// Generated by harpia Stage 13 (gRPC service impl). Do not edit.
#ifndef HARPIA_GRPC_TOP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_GRPC_TOP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>
#include <vector>

#include <grpcpp/grpcpp.h>
#include <soci/soci.h>
#include "protofiles/top_users_3ac5d8b36fc7dcfb70888145147ddfb7_service.grpc.pb.h"
#include "db/top_users_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"
#include <grpcpp/security/auth_context.h>
#include "grpc/harpia_rbac.h"
#include "grpc/harpia_session.h"
// gRPC service implementation for top_users, backed by the CRUDL DAO -- the RPCs of
// the generated top_users_Service are wired to create/read/list over SQLite:
//   push(msg)      -> dao.create(msg)             -> errorCode
//   pullByID(id)   -> dao.read(id)                -> top_users_Message (NOT_FOUND)
//   streamSrc()    -> dao.list() streamed back    -> stream top_users_Message
//                     (paginated via the request's offset/limit when limit>0)
//   heartBeat(hb)  -> echo                         (no CRUDL, unauthenticated)
// Construct with a soci::session the caller owns; register with a grpc::ServerBuilder,
// or let the generated grpc/grpc_server_bringup.h do it -- its
// harpia::grpc_transport::GrpcServer registers every service and picks mTLS vs
// insecure transport credentials from transport_hardening_required(compliance)
// at generation time (transport-authn epic, task 2; harpia_grpc_mtls.h).
//
// Access gate (compiled in at generation time; which variant depends on
// transport_hardening_required(compliance) -- transport-authn epic, tasks 2+4):
//   hardened  -> a three-role RBAC check (admin / main / guest). The x509
//               subject CommonName from ServerContext::auth_context() (the
//               verified mTLS client cert) is resolved to a role via the
//               HARPIA_RBAC_MAP file and checked against the RPC's operation
//               (push -> create, pullByID -> read, streamSrc -> stream). No /
//               unverifiable identity -> UNAUTHENTICATED; valid identity,
//               wrong role -> PERMISSION_DENIED. Every denial emits exactly
//               one AuditSink "rbac_denied" record (names only, never a
//               credential value). See generated grpc/harpia_rbac.h.
//   otherwise -> the flat generated access credential: the call must carry
//               x-user: top_users and x-pswd: 3ac5d8b36fc7dcfb70888145147ddfb7 metadata, or it is rejected
//               with UNAUTHENTICATED.
// heartBeat stays open as a liveness probe in both variants.
//
// Session tokens (transport-authn epic, task 5; hardened variant only). Under
// the RBAC gate, a call may present a bearer token as `authorization: Bearer
// <token>` metadata instead of re-deriving its identity from the client cert;
// a token that does not verify (signature / expiry / revocation) is
// UNAUTHENTICATED, never a fall-through to the cert. A token is obtained by
// calling heartBeat() with `harpia-issue-session` metadata -- the response
// carries a fresh `harpia-session-token` in its trailing metadata. See
// generated grpc/harpia_session.h.
namespace harpia {
namespace grpc_svc {

class top_users_service final
    : public ::frameworkProtos::top_users_Service::Service {
public:
    explicit top_users_service(::soci::session& db) : db_(db) {}

    // x509 subject CommonName of the verified mTLS client certificate, or "".
    static ::std::string peer_cn(::grpc::ServerContext* ctx) {
        if (!ctx) return {};
        const auto ac = ctx->auth_context();
        if (!ac) return {};
        const auto vals = ac->FindPropertyValues(GRPC_X509_CN_PROPERTY_NAME);
        if (vals.empty()) return {};
        return ::std::string(vals[0].data(), vals[0].size());
    }

    // Raw `authorization` call-metadata value ("Bearer <token>"), or "".
    static ::std::string bearer_metadata(::grpc::ServerContext* ctx) {
        if (!ctx) return {};
        const auto& md = ctx->client_metadata();
        const auto it = md.find("authorization");
        if (it == md.end()) return {};
        return ::std::string(it->second.data(), it->second.length());
    }

    // Role gate for top_users (transport-authn epic, tasks 4 + 5): identity is a
    // valid `authorization: Bearer` session token (task 5) or, absent one,
    // peer_cn() (the verified mTLS client cert); a presented-but-invalid token
    // is UNAUTHENTICATED with no fall-through to the cert. The resolved CN is
    // mapped to a role via the HARPIA_RBAC_MAP file and checked against `op`.
    // OK -> proceed; UNAUTHENTICATED (no / unverifiable identity) or
    // PERMISSION_DENIED (valid identity, wrong role) otherwise.
    // ::harpia::rbac::decide has already emitted the single AuditSink
    // "rbac_denied" record on a denial (a bad token emits one "session_denied"
    // record instead).
    static ::grpc::Status rbac_check(::grpc::ServerContext* ctx,
                                     ::harpia::rbac::Operation op) {
        ::std::string cn = peer_cn(ctx);
        const auto bearer =
            ::harpia::session::from_authorization(bearer_metadata(ctx));
        if (bearer.present) {
            if (bearer.verdict != ::harpia::session::Verdict::ok) {
                return ::grpc::Status(::grpc::StatusCode::UNAUTHENTICATED,
                                      "invalid session token");
            }
            cn = bearer.cn;
        }
        switch (::harpia::rbac::decide(cn, op, "top_users")) {
            case ::harpia::rbac::Decision::allow:
                return ::grpc::Status::OK;
            case ::harpia::rbac::Decision::unauthenticated:
                return ::grpc::Status(::grpc::StatusCode::UNAUTHENTICATED,
                                      "unauthenticated");
            default:
                return ::grpc::Status(::grpc::StatusCode::PERMISSION_DENIED,
                                      "forbidden");
        }
    }

    ::grpc::Status push(::grpc::ServerContext* context,
                        const ::frameworkProtos::top_users_Message* request,
                        ::frameworkProtos::errorCode* response) override {
        if (const auto rbac_s = rbac_check(context, ::harpia::rbac::Operation::create);
            !rbac_s.ok()) {
            return rbac_s;
        }
        ::harpia::db::top_users_dao dao(db_);
        const bool ok = dao.create(request->msg());
        response->set_code(ok ? 0 : 1);
        response->set_message(ok ? "ok" : "create failed");
        return ::grpc::Status::OK;
    }

    ::grpc::Status pullByID(::grpc::ServerContext* context,
                            const ::frameworkProtos::top_users_ID* request,
                            ::frameworkProtos::top_users_Message* response) override {
        if (const auto rbac_s = rbac_check(context, ::harpia::rbac::Operation::read);
            !rbac_s.ok()) {
            return rbac_s;
        }
        ::harpia::db::top_users_dao dao(db_);
        if (!dao.read(request->id(), response->mutable_msg())) {
            return ::grpc::Status(::grpc::StatusCode::NOT_FOUND, "not found");
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status streamSrc(
            ::grpc::ServerContext* context,
            const ::frameworkProtos::top_users_Stream* request,
            ::grpc::ServerWriter< ::frameworkProtos::top_users_Message>* writer) override {
        if (const auto rbac_s = rbac_check(context, ::harpia::rbac::Operation::stream);
            !rbac_s.ok()) {
            return rbac_s;
        }
        ::harpia::db::top_users_dao dao(db_);
        std::vector< ::top_users> rows;
        // limit <= 0 (proto3 default / not set) means unbounded, matching
        // pre-pagination behavior.
        const bool paginated = request->limit() > 0;
        const bool ok = paginated
            ? dao.list(&rows, request->offset(), request->limit())
            : dao.list(&rows);
        if (!ok) {
            return ::grpc::Status(::grpc::StatusCode::INTERNAL, "list failed");
        }
        for (const auto& r : rows) {
            ::frameworkProtos::top_users_Message m;
            *m.mutable_msg() = r;
            writer->Write(m);
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status heartBeat(::grpc::ServerContext* context,
                             const ::frameworkProtos::top_users_HeartBeat* request,
                             ::frameworkProtos::top_users_HeartBeat* response) override {
        // transport-authn task 5: heartBeat also issues session tokens. A
        // caller that has authenticated the mTLS transport sends
        // `harpia-issue-session` metadata and gets a signed bearer token
        // carrying its RBAC CN + role back as `harpia-session-token` trailing
        // metadata. Never gated -- heartBeat is the open liveness probe.
        if (context) {
            const auto& md = context->client_metadata();
            if (md.find("harpia-issue-session") != md.end()) {
                const ::std::string cn = peer_cn(context);
                if (!cn.empty()) {
                    const auto issue_role =
                        ::harpia::rbac::role_map().role_for(cn);
                    const ::std::string tok = ::harpia::session::issue(
                        cn, ::harpia::rbac::role_name(issue_role));
                    if (!tok.empty()) {
                        context->AddTrailingMetadata("harpia-session-token", tok);
                    }
                }
            }
        }
        *response = *request;
        return ::grpc::Status::OK;
    }

private:
    ::soci::session& db_;
};

}  // namespace grpc_svc
}  // namespace harpia

#endif  // HARPIA_GRPC_TOP_USERS_3ac5d8b36fc7dcfb70888145147ddfb7
