#!/usr/bin/env python3
"""
Minimal GUI generator prototype.
Reads a simple YAML GUI file and emits two C files: gui_defs.h and gui_resources.c
This is stage-1: it demonstrates the pipeline and emits lightweight structs.
"""
import sys
import os
import yaml

if len(sys.argv) < 3:
    print("Usage: generator.py <input.yml> <out_dir>")
    sys.exit(1)

infile = sys.argv[1]
outdir = sys.argv[2]

with open(infile, 'r') as f:
    data = yaml.safe_load(f)

os.makedirs(outdir, exist_ok=True)

screens = []
if 'screen' in data:
    screens = [data['screen']]

# simple id hash
def id_hash(s):
    h = 2166136261
    for c in s:
        h = (h ^ ord(c)) * 16777619 & 0xffffffff
    return h

# emit header
hdr_path = os.path.join(outdir, 'gui_defs.h')
with open(hdr_path, 'w') as h:
    h.write('/* Generated by GuiAdapter generator.py - Stage 1 prototype */\n')
    h.write('#pragma once\n\n')
    h.write('#include <stdint.h>\n\n')
    h.write('typedef struct {\n')
    h.write('  const char* id;\n')
    h.write('  uint16_t width;\n')
    h.write('  uint16_t height;\n')
    h.write('  const void* widgets; /* pointer to widget array */\n')
    h.write('  uint16_t widget_count;\n')
    h.write('} GuiScreen;\n\n')
    h.write('typedef struct {\n')
    h.write('  uint32_t id_hash;\n')
    h.write('  uint8_t type;\n')
    h.write('  int16_t x,y,w,h;\n')
    h.write('  int32_t resource_index;\n')
    h.write('} GuiWidget;\n\n')

    # forward declare arrays
    for s in screens:
        name = s.get('id','screen')
        h.write('extern const GuiWidget gui_widgets_%s[];\n' % name)
        h.write('extern const GuiScreen gui_screen_%s;\n' % name)

# emit resources C
res_path = os.path.join(outdir, 'gui_resources.c')
with open(res_path, 'w') as c:
    c.write('/* Generated resources - Stage 1 prototype */\n')
    c.write('#include "gui_defs.h"\n\n')

    for s in screens:
        name = s.get('id','screen')
        widgets = s.get('widgets', [])
        c.write('const GuiWidget gui_widgets_%s[] = {\n' % name)
        for w in widgets:
            wid = w.get('id','w')
            typ = w.get('type','label')
            ty = 0
            if typ == 'label': ty = 1
            elif typ == 'button': ty = 2
            elif typ == 'image': ty = 3
            elif typ == 'progress': ty = 4
            x,y = 0,0
            w_w,w_h = 0,0
            if 'pos' in w:
                x,y = w['pos'][0], w['pos'][1]
            if 'size' in w:
                w_w,w_h = w['size'][0], w['size'][1]
            ridx = -1
            if 'src' in w:
                ridx = 0
            hval = id_hash(wid)
            c.write('  { %u, %u, %d, %d, %d, %d, %d },\n' % (hval, ty, x, y, w_w, w_h, ridx))
        c.write('};\n\n')
        c.write('const GuiScreen gui_screen_%s = { "%s", %d, %d, gui_widgets_%s, %d };\n\n' % (
            name, name, s.get('size',[240,320])[0], s.get('size',[240,320])[1], name, len(s.get('widgets',[]))
        ))

print('Generated:', hdr_path, res_path)
