// edge -- the reference system's Linux program (multi-system-reference /
// reference-system task 4). It has NO database: everything it stores goes to
// `station` over hardened gRPC, and its live stream goes out over CURVE ZMQ.
//
//   edge --station station.lan:50051 --certs <pki dir> --identity edge \
//        --pub tcp://*:5556 --zmq-keys <zmq dir> --interval 500 --notes-every 10
//
// Every --interval ms it creates one `reading` on station (mTLS + a bearer
// session) and publishes one `live_sample` on its PUB socket (CURVE; the ZAP
// handler admits only the keys in HARPIA_ZMQ_ALLOWLIST). Every --notes-every
// readings it lists the `field_note`s on station and logs how many it saw --
// the station -> edge direction.
//
// Load mode (load-harness task 1): `--load --rate <ops/s> --duration <s>
// --mix <create>:<list>:<read> --report <file.jsonl>`. The process is ONE
// identity (its own client cert, its own session), so N processes are N real
// clients to station. Operations are paced at --rate, picked by the --mix
// weights (create a reading / list field notes / read back one of its own
// readings -- the generated gRPC surface is push, streamSrc, pullByID; there
// is no update RPC), and each one appends a JSON line:
//   {"t":<unix s>,"client_kind":"edge","identity":..,"op":..,"ok":..,
//    "grpc_code":"OK"|"UNAVAILABLE"|..,"latency_us":..}
// --pub is optional in load mode (a spawned load client usually doesn't
// publish; the reference stream comes from one ordinary edge).
//
// Environment: HARPIA_ZMQ_ALLOWLIST (the subscribers' public keys; without it
// every subscriber is refused -- fail-safe). See README.md.
#include "harpia_ms_client.h"   // generated by CMake: the hash-named headers

#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <functional>
#include <iostream>
#include <memory>
#include <random>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include <grpcpp/grpcpp.h>
#include <zmq.hpp>

#ifdef _WIN32
#include <windows.h>
#else
#include <csignal>
#endif

namespace {

std::atomic<bool> g_stop{false};
#ifdef _WIN32
BOOL WINAPI on_console_event(DWORD) { g_stop = true; return TRUE; }
void install_shutdown_hook() { SetConsoleCtrlHandler(on_console_event, TRUE); }
#else
extern "C" void on_signal(int) { g_stop = true; }
void install_shutdown_hook() {
    std::signal(SIGINT, on_signal);
    std::signal(SIGTERM, on_signal);
}
#endif

struct Args {
    std::string station = "127.0.0.1:50051";
    std::string authority;        // TLS name to verify (default: the station host)
    std::string certs = ".";
    std::string identity = "edge";
    std::string pub;              // default tcp://*:5556 outside load mode
    std::string zmq_keys = ".";
    std::string device;           // default: the identity
    int interval_ms = 500;
    int notes_every = 10;
    long long id_base = 1;
    long long count = 0;          // 0 = until stopped
    int duration_s = 0;           // 0 = until stopped
    // load mode
    bool load = false;
    double rate = 20.0;
    int mix[3] = {8, 1, 1};       // create : list : read
    std::string report;
};

int usage(const std::string& why) {
    std::cerr << "edge: " << why << "\n"
              << "usage: edge --station host:port --certs <dir> [--identity name] "
                 "[--authority tls-name] [--pub tcp://*:port] [--zmq-keys <dir>] "
                 "[--device id] [--interval ms] [--notes-every N] [--id-base N] "
                 "[--count N] [--duration s]\n"
                 "       edge --load --identity name --rate ops/s --duration s "
                 "[--mix create:list:read] --report file.jsonl --station ... --certs ...\n";
    return 2;
}

bool parse_mix(const std::string& v, int out[3]) {
    std::istringstream in(v);
    std::string part;
    int i = 0;
    while (std::getline(in, part, ':')) {
        if (i >= 3) return false;
        out[i++] = std::atoi(part.c_str());
        if (out[i - 1] < 0) return false;
    }
    return i == 3 && (out[0] + out[1] + out[2]) > 0;
}

bool parse(int argc, char** argv, Args* a, std::string* err) {
    for (int i = 1; i < argc; ++i) {
        const std::string k = argv[i];
        if (k == "--load") { a->load = true; continue; }
        if (i + 1 >= argc) { *err = k + " needs a value"; return false; }
        const std::string v = argv[++i];
        if (k == "--station") a->station = v;
        else if (k == "--authority") a->authority = v;
        else if (k == "--certs") a->certs = v;
        else if (k == "--identity") a->identity = v;
        else if (k == "--pub") a->pub = v;
        else if (k == "--zmq-keys") a->zmq_keys = v;
        else if (k == "--device") a->device = v;
        else if (k == "--interval") a->interval_ms = std::atoi(v.c_str());
        else if (k == "--notes-every") a->notes_every = std::atoi(v.c_str());
        else if (k == "--id-base") a->id_base = std::atoll(v.c_str());
        else if (k == "--count") a->count = std::atoll(v.c_str());
        else if (k == "--duration") a->duration_s = std::atoi(v.c_str());
        else if (k == "--rate") a->rate = std::atof(v.c_str());
        else if (k == "--mix") { if (!parse_mix(v, a->mix)) { *err = "--mix wants create:list:read weights, e.g. 8:1:1"; return false; } }
        else if (k == "--report") a->report = v;
        else { *err = "unknown argument " + k; return false; }
    }
    if (a->interval_ms < 1) a->interval_ms = 1;
    if (a->device.empty()) a->device = a->identity;
    if (!a->load && a->pub.empty()) a->pub = "tcp://*:5556";
    if (a->load) {
        if (a->rate <= 0) { *err = "--rate must be > 0"; return false; }
        if (a->duration_s <= 0) { *err = "load mode needs --duration"; return false; }
        if (a->report.empty()) { *err = "load mode needs --report"; return false; }
    }
    return true;
}

std::string read_key(const std::string& path) {
    std::ifstream in(path);
    std::string k;
    in >> k;
    return k;
}

long long now_ms() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::system_clock::now().time_since_epoch()).count();
}

const char* code_name(::grpc::StatusCode c) {
    switch (c) {
        case ::grpc::StatusCode::OK: return "OK";
        case ::grpc::StatusCode::CANCELLED: return "CANCELLED";
        case ::grpc::StatusCode::UNKNOWN: return "UNKNOWN";
        case ::grpc::StatusCode::INVALID_ARGUMENT: return "INVALID_ARGUMENT";
        case ::grpc::StatusCode::DEADLINE_EXCEEDED: return "DEADLINE_EXCEEDED";
        case ::grpc::StatusCode::NOT_FOUND: return "NOT_FOUND";
        case ::grpc::StatusCode::ALREADY_EXISTS: return "ALREADY_EXISTS";
        case ::grpc::StatusCode::PERMISSION_DENIED: return "PERMISSION_DENIED";
        case ::grpc::StatusCode::RESOURCE_EXHAUSTED: return "RESOURCE_EXHAUSTED";
        case ::grpc::StatusCode::FAILED_PRECONDITION: return "FAILED_PRECONDITION";
        case ::grpc::StatusCode::ABORTED: return "ABORTED";
        case ::grpc::StatusCode::OUT_OF_RANGE: return "OUT_OF_RANGE";
        case ::grpc::StatusCode::UNIMPLEMENTED: return "UNIMPLEMENTED";
        case ::grpc::StatusCode::INTERNAL: return "INTERNAL";
        case ::grpc::StatusCode::UNAVAILABLE: return "UNAVAILABLE";
        case ::grpc::StatusCode::DATA_LOSS: return "DATA_LOSS";
        case ::grpc::StatusCode::UNAUTHENTICATED: return "UNAUTHENTICATED";
        default: return "UNKNOWN";
    }
}

// One JSON line per operation. Identities are [A-Za-z0-9._-] (the PKI
// script's rule), so no escaping is needed.
class Report {
public:
    explicit Report(const std::string& path) : out_(path, std::ios::app) {}
    bool ok() const { return static_cast<bool>(out_); }
    void op(const std::string& identity, const char* op, const ::grpc::Status& st,
            long long latency_us) {
        const double t = static_cast<double>(now_ms()) / 1000.0;
        char buf[512];
        std::snprintf(buf, sizeof buf,
                      "{\"t\":%.3f,\"client_kind\":\"edge\",\"identity\":\"%s\",\"op\":\"%s\","
                      "\"ok\":%s,\"grpc_code\":\"%s\",\"latency_us\":%lld}\n",
                      t, identity.c_str(), op, st.ok() ? "true" : "false",
                      code_name(st.error_code()), latency_us);
        out_ << buf;
        out_.flush();   // a crashed client still leaves every finished op behind
    }

private:
    std::ofstream out_;
};

// heartBeat with `harpia-issue-session` metadata -> the `harpia-session-token`
// trailing metadata the generated server mints for this client's CN + role.
std::string issue_session(frameworkProtos::reading_Service::Stub& stub, ::grpc::Status* out) {
    ::grpc::ClientContext c;
    c.AddMetadata("harpia-issue-session", "1");
    c.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(10));
    frameworkProtos::reading_HeartBeat req, resp;
    ::grpc::Status st = stub.heartBeat(&c, req, &resp);
    if (out) *out = st;
    if (!st.ok()) {
        std::cerr << "edge: session issue failed: " << st.error_message() << "\n";
        return {};
    }
    const auto& md = c.GetServerTrailingMetadata();
    auto it = md.find("harpia-session-token");
    return it == md.end() ? std::string() : std::string(it->second.data(), it->second.size());
}

struct Client {
    std::unique_ptr<frameworkProtos::reading_Service::Stub> readings;
    std::unique_ptr<frameworkProtos::field_note_Service::Stub> notes;
    std::string token;

    void auth(::grpc::ClientContext& c) const {
        c.AddMetadata("authorization", "Bearer " + token);
        c.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(10));
    }
    // Runs `call` once; on UNAUTHENTICATED (expired / revoked token) re-issues
    // the session once and runs it again. Returns the final status.
    ::grpc::Status with_session(const std::function<::grpc::Status()>& call, long long* reissued) {
        ::grpc::Status st = call();
        if (st.error_code() == ::grpc::StatusCode::UNAUTHENTICATED) {
            std::string t = issue_session(*readings, nullptr);
            if (!t.empty()) {
                token = t;
                if (reissued) ++*reissued;
                st = call();
            }
        }
        return st;
    }
    ::grpc::Status create(const Args& a, long long seq, float value) {
        frameworkProtos::reading_Message req;
        ::reading* r = req.mutable_msg();
        harpia_ms::set_id(*r, static_cast<int>(a.id_base + seq));
        r->set_device_id(a.device);
        r->set_taken_at_ms(now_ms());
        r->set_value(value);
        r->set_unit("C");
        ::grpc::ClientContext c;
        auth(c);
        frameworkProtos::errorCode ec;
        ::grpc::Status st = readings->push(&c, req, &ec);
        if (st.ok() && ec.code() != 0) return ::grpc::Status(::grpc::StatusCode::INTERNAL, ec.message());
        return st;
    }
    ::grpc::Status list_notes(int* n, int limit) {
        ::grpc::ClientContext c;
        auth(c);
        frameworkProtos::field_note_Stream q;
        q.set_limit(limit);
        auto reader = notes->streamSrc(&c, q);
        frameworkProtos::field_note_Message m;
        *n = 0;
        while (reader->Read(&m)) ++*n;
        return reader->Finish();
    }
    ::grpc::Status read(long long id) {
        ::grpc::ClientContext c;
        auth(c);
        frameworkProtos::reading_ID req;
        req.set_id(static_cast<int>(id));
        frameworkProtos::reading_Message resp;
        return readings->pullByID(&c, req, &resp);
    }
};

long long since_us(std::chrono::steady_clock::time_point t0) {
    return std::chrono::duration_cast<std::chrono::microseconds>(
               std::chrono::steady_clock::now() - t0).count();
}

int run_load(const Args& a, Client& cl, ::harpia::zmq_transport::live_sample_publisher* pub) {
    Report rep(a.report);
    if (!rep.ok()) {
        std::cerr << "edge: cannot write " << a.report << "\n";
        return 7;
    }
    // deterministic per identity, so a rerun issues the same op sequence
    std::mt19937_64 rng(std::hash<std::string>{}(a.identity));
    std::discrete_distribution<int> pick({double(a.mix[0]), double(a.mix[1]), double(a.mix[2])});
    std::vector<long long> mine;     // ids this client created (read targets)
    long long created = 0, ops = 0, failed = 0, reissued = 0;
    const auto t0 = std::chrono::steady_clock::now();
    const auto t_end = t0 + std::chrono::seconds(a.duration_s);
    const auto period = std::chrono::duration<double>(1.0 / a.rate);
    for (long long i = 0; !g_stop; ++i) {
        const auto due = t0 + std::chrono::duration_cast<std::chrono::steady_clock::duration>(period * i);
        if (due >= t_end) break;
        std::this_thread::sleep_until(due);
        if (g_stop) break;
        int kind = pick(rng);
        if (kind == 2 && mine.empty()) kind = 0;   // nothing of ours to read yet
        const auto s = std::chrono::steady_clock::now();
        ::grpc::Status st;
        const char* name = "create";
        if (kind == 0) {
            const float value = 20.0f + static_cast<float>(created % 100) / 10.0f;
            const long long seq = created;
            st = cl.with_session([&] { return cl.create(a, seq, value); }, &reissued);
            if (st.ok()) {
                mine.push_back(a.id_base + seq);
                if (pub) {
                    ::live_sample smp;
                    smp.set_device_id(a.device);
                    smp.set_seq(seq);
                    smp.set_value(value);
                    pub->publish(smp);
                }
            }
            ++created;   // the id is spent either way (a failed id is never reused)
        } else if (kind == 1) {
            name = "list";
            int n = 0;
            st = cl.with_session([&] { return cl.list_notes(&n, 50); }, &reissued);
        } else {
            name = "read";
            std::uniform_int_distribution<std::size_t> which(0, mine.size() - 1);
            const long long id = mine[which(rng)];
            st = cl.with_session([&] { return cl.read(id); }, &reissued);
        }
        rep.op(a.identity, name, st, since_us(s));
        ++ops;
        if (!st.ok()) ++failed;
    }
    std::cout << "edge: load done identity=" << a.identity << " ops=" << ops
              << " failed=" << failed << " sessions_reissued=" << reissued << std::endl;
    return 0;
}

}  // namespace

int main(int argc, char** argv) {
    Args a;
    std::string err;
    if (!parse(argc, argv, &a, &err)) return usage(err);

    // --- gRPC to station: mTLS with this identity's client cert ------------
    ::harpia::grpc_transport::MtlsFiles files{
        a.certs + "/ca.pem", a.certs + "/client_" + a.identity + ".pem",
        a.certs + "/client_" + a.identity + "_key.pem"};
    std::shared_ptr<::grpc::ChannelCredentials> creds;
    try {
        creds = ::harpia::grpc_transport::channel_credentials(true, files);
    } catch (const std::exception& e) {
        std::cerr << "edge: " << e.what() << "\n";
        return 3;
    }
    ::grpc::ChannelArguments chargs;
    if (!a.authority.empty()) chargs.SetSslTargetNameOverride(a.authority);
    auto channel = ::grpc::CreateCustomChannel(a.station, creds, chargs);
    Client cl;
    cl.readings = frameworkProtos::reading_Service::NewStub(channel);
    cl.notes = frameworkProtos::field_note_Service::NewStub(channel);

    ::grpc::Status ist;              // load mode: the session issue is an op too
    const auto s0 = std::chrono::steady_clock::now();
    cl.token = issue_session(*cl.readings, &ist);
    if (a.load) {
        Report r(a.report);
        r.op(a.identity, "session", cl.token.empty() && ist.ok()
                 ? ::grpc::Status(::grpc::StatusCode::INTERNAL, "no token") : ist, since_us(s0));
    }
    if (cl.token.empty()) return 4;

    // --- ZMQ PUB for the live stream: CURVE server + ZAP allowlist --------
    ::zmq::context_t ctx;
    std::unique_ptr<::harpia::zmq_transport::live_sample_publisher> pub;
    if (!a.pub.empty()) {
        const std::string secret = read_key(a.zmq_keys + "/zmq_server_secret.key");
        if (secret.size() != 40) {
            std::cerr << "edge: no CURVE server secret key in " << a.zmq_keys << "\n";
            return 5;
        }
        try {
            pub = std::make_unique<::harpia::zmq_transport::live_sample_publisher>(
                ctx, a.pub, ::harpia::zmq_transport::live_sample_publisher::origin_id(),
                ::harpia::zmq_transport::CurveServerKeys{secret});
            pub->socket().set(::zmq::sockopt::linger, 0);
        } catch (const std::exception& e) {
            std::cerr << "edge: cannot bind " << a.pub << ": " << e.what() << "\n";
            return 5;
        }
    }

    install_shutdown_hook();
    if (a.load) return run_load(a, cl, pub.get());

    std::cout << "edge: " << a.identity << " -> station " << a.station
              << ", publishing on " << a.pub << std::endl;
    const auto t_end = std::chrono::steady_clock::now() + std::chrono::seconds(a.duration_s);
    long long sent = 0, failed = 0, published = 0, reissued = 0;
    for (long long seq = 0; !g_stop; ++seq) {
        if (a.count > 0 && seq >= a.count) break;
        if (a.duration_s > 0 && std::chrono::steady_clock::now() >= t_end) break;
        const auto tick = std::chrono::steady_clock::now();
        const float value = 20.0f + static_cast<float>(seq % 100) / 10.0f;
        ::grpc::Status st = cl.with_session([&] { return cl.create(a, seq, value); }, &reissued);
        if (st.ok()) ++sent;
        else {
            ++failed;
            std::cerr << "edge: create reading failed: " << st.error_message() << "\n";
        }

        ::live_sample s;
        s.set_device_id(a.device);
        s.set_seq(seq);
        s.set_value(value);
        if (pub->publish(s)) ++published;

        if (a.notes_every > 0 && (seq + 1) % a.notes_every == 0) {
            int n = 0;
            st = cl.with_session([&] { return cl.list_notes(&n, 1000); }, &reissued);
            if (st.ok()) std::cout << "edge: field_notes on station: " << n << std::endl;
            else std::cerr << "edge: list field_notes failed: " << st.error_message() << "\n";
        }
        std::this_thread::sleep_until(tick + std::chrono::milliseconds(a.interval_ms));
    }
    std::cout << "edge: done readings_created=" << sent << " readings_failed=" << failed
              << " samples_published=" << published << " sessions_reissued=" << reissued
              << std::endl;
    return failed == 0 ? 0 : 6;
}
