// edge -- the reference system's Linux program (multi-system-reference /
// reference-system task 4). It has NO database: everything it stores goes to
// `station` over hardened gRPC, and its live stream goes out over CURVE ZMQ.
//
//   edge --station station.lan:50051 --certs <pki dir> --identity edge \
//        --pub tcp://*:5556 --zmq-keys <zmq dir> --interval 500 --notes-every 10
//
// Every --interval ms it creates one `reading` on station (mTLS + a bearer
// session) and publishes one `live_sample` on its PUB socket (CURVE; the ZAP
// handler admits only the keys in HARPIA_ZMQ_ALLOWLIST). Every --notes-every
// readings it lists the `field_note`s on station and logs how many it saw --
// the station -> edge direction.
//
// Environment: HARPIA_ZMQ_ALLOWLIST (the subscribers' public keys; without it
// every subscriber is refused -- fail-safe). See README.md.
#include "harpia_ms_client.h"   // generated by CMake: the hash-named headers

#include <atomic>
#include <chrono>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <thread>

#include <grpcpp/grpcpp.h>
#include <zmq.hpp>

#ifdef _WIN32
#include <windows.h>
#else
#include <csignal>
#endif

namespace {

std::atomic<bool> g_stop{false};
#ifdef _WIN32
BOOL WINAPI on_console_event(DWORD) { g_stop = true; return TRUE; }
void install_shutdown_hook() { SetConsoleCtrlHandler(on_console_event, TRUE); }
#else
extern "C" void on_signal(int) { g_stop = true; }
void install_shutdown_hook() {
    std::signal(SIGINT, on_signal);
    std::signal(SIGTERM, on_signal);
}
#endif

struct Args {
    std::string station = "127.0.0.1:50051";
    std::string authority;        // TLS name to verify (default: the station host)
    std::string certs = ".";
    std::string identity = "edge";
    std::string pub = "tcp://*:5556";
    std::string zmq_keys = ".";
    std::string device = "edge-1";
    int interval_ms = 500;
    int notes_every = 10;
    long long id_base = 1;
    long long count = 0;          // 0 = until stopped
    int duration_s = 0;           // 0 = until stopped
};

int usage(const std::string& why) {
    std::cerr << "edge: " << why << "\n"
              << "usage: edge --station host:port --certs <dir> [--identity name] "
                 "[--authority tls-name] [--pub tcp://*:port] [--zmq-keys <dir>] "
                 "[--device id] [--interval ms] [--notes-every N] [--id-base N] "
                 "[--count N] [--duration s]\n";
    return 2;
}

bool parse(int argc, char** argv, Args* a, std::string* err) {
    for (int i = 1; i < argc; ++i) {
        const std::string k = argv[i];
        if (i + 1 >= argc) { *err = k + " needs a value"; return false; }
        const std::string v = argv[++i];
        if (k == "--station") a->station = v;
        else if (k == "--authority") a->authority = v;
        else if (k == "--certs") a->certs = v;
        else if (k == "--identity") a->identity = v;
        else if (k == "--pub") a->pub = v;
        else if (k == "--zmq-keys") a->zmq_keys = v;
        else if (k == "--device") a->device = v;
        else if (k == "--interval") a->interval_ms = std::atoi(v.c_str());
        else if (k == "--notes-every") a->notes_every = std::atoi(v.c_str());
        else if (k == "--id-base") a->id_base = std::atoll(v.c_str());
        else if (k == "--count") a->count = std::atoll(v.c_str());
        else if (k == "--duration") a->duration_s = std::atoi(v.c_str());
        else { *err = "unknown argument " + k; return false; }
    }
    if (a->interval_ms < 1) a->interval_ms = 1;
    return true;
}

std::string read_key(const std::string& path) {
    std::ifstream in(path);
    std::string k;
    in >> k;
    return k;
}

long long now_ms() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::system_clock::now().time_since_epoch()).count();
}

// heartBeat with `harpia-issue-session` metadata -> the `harpia-session-token`
// trailing metadata the generated server mints for this client's CN + role.
std::string issue_session(frameworkProtos::reading_Service::Stub& stub) {
    ::grpc::ClientContext c;
    c.AddMetadata("harpia-issue-session", "1");
    c.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(10));
    frameworkProtos::reading_HeartBeat req, resp;
    ::grpc::Status st = stub.heartBeat(&c, req, &resp);
    if (!st.ok()) {
        std::cerr << "edge: session issue failed: " << st.error_message() << "\n";
        return {};
    }
    const auto& md = c.GetServerTrailingMetadata();
    auto it = md.find("harpia-session-token");
    return it == md.end() ? std::string() : std::string(it->second.data(), it->second.size());
}

}  // namespace

int main(int argc, char** argv) {
    Args a;
    std::string err;
    if (!parse(argc, argv, &a, &err)) return usage(err);

    // --- gRPC to station: mTLS with this identity's client cert ------------
    ::harpia::grpc_transport::MtlsFiles files{
        a.certs + "/ca.pem", a.certs + "/client_" + a.identity + ".pem",
        a.certs + "/client_" + a.identity + "_key.pem"};
    std::shared_ptr<::grpc::ChannelCredentials> creds;
    try {
        creds = ::harpia::grpc_transport::channel_credentials(true, files);
    } catch (const std::exception& e) {
        std::cerr << "edge: " << e.what() << "\n";
        return 3;
    }
    ::grpc::ChannelArguments chargs;
    if (!a.authority.empty()) chargs.SetSslTargetNameOverride(a.authority);
    auto channel = ::grpc::CreateCustomChannel(a.station, creds, chargs);
    auto readings = frameworkProtos::reading_Service::NewStub(channel);
    auto notes = frameworkProtos::field_note_Service::NewStub(channel);

    std::string token = issue_session(*readings);
    if (token.empty()) return 4;
    auto authed = [&](::grpc::ClientContext& c) {
        c.AddMetadata("authorization", "Bearer " + token);
        c.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(10));
    };

    // --- ZMQ PUB for the live stream: CURVE server + ZAP allowlist --------
    ::zmq::context_t ctx;
    const std::string secret = read_key(a.zmq_keys + "/zmq_server_secret.key");
    if (secret.size() != 40) {
        std::cerr << "edge: no CURVE server secret key in " << a.zmq_keys << "\n";
        return 5;
    }
    std::unique_ptr<::harpia::zmq_transport::live_sample_publisher> pub;
    try {
        pub = std::make_unique<::harpia::zmq_transport::live_sample_publisher>(
            ctx, a.pub, ::harpia::zmq_transport::live_sample_publisher::origin_id(),
            ::harpia::zmq_transport::CurveServerKeys{secret});
        pub->socket().set(::zmq::sockopt::linger, 0);
    } catch (const std::exception& e) {
        std::cerr << "edge: cannot bind " << a.pub << ": " << e.what() << "\n";
        return 5;
    }

    install_shutdown_hook();
    std::cout << "edge: " << a.identity << " -> station " << a.station
              << ", publishing on " << a.pub << std::endl;

    const auto t_end = std::chrono::steady_clock::now() + std::chrono::seconds(a.duration_s);
    long long sent = 0, failed = 0, published = 0, reissued = 0;
    for (long long seq = 0; !g_stop; ++seq) {
        if (a.count > 0 && seq >= a.count) break;
        if (a.duration_s > 0 && std::chrono::steady_clock::now() >= t_end) break;
        const auto tick = std::chrono::steady_clock::now();
        const float value = 20.0f + static_cast<float>(seq % 100) / 10.0f;

        frameworkProtos::reading_Message req;
        ::reading* r = req.mutable_msg();
        harpia_ms::set_id(*r, static_cast<int>(a.id_base + seq));
        r->set_device_id(a.device);
        r->set_taken_at_ms(now_ms());
        r->set_value(value);
        r->set_unit("C");
        for (int attempt = 0; attempt < 2; ++attempt) {
            ::grpc::ClientContext c;
            authed(c);
            frameworkProtos::errorCode ec;
            ::grpc::Status st = readings->push(&c, req, &ec);
            if (st.error_code() == ::grpc::StatusCode::UNAUTHENTICATED && attempt == 0) {
                token = issue_session(*readings);   // expired / revoked: re-issue once
                ++reissued;
                if (!token.empty()) continue;
            }
            if (st.ok() && ec.code() == 0) ++sent;
            else {
                ++failed;
                std::cerr << "edge: create reading failed: "
                          << (st.ok() ? ec.message() : st.error_message()) << "\n";
            }
            break;
        }

        ::live_sample s;
        s.set_device_id(a.device);
        s.set_seq(seq);
        s.set_value(value);
        if (pub->publish(s)) ++published;

        if (a.notes_every > 0 && (seq + 1) % a.notes_every == 0) {
            ::grpc::ClientContext c;
            authed(c);
            frameworkProtos::field_note_Stream q;
            q.set_limit(1000);
            auto reader = notes->streamSrc(&c, q);
            frameworkProtos::field_note_Message m;
            int n = 0;
            while (reader->Read(&m)) ++n;
            ::grpc::Status st = reader->Finish();
            if (st.ok()) std::cout << "edge: field_notes on station: " << n << std::endl;
            else std::cerr << "edge: list field_notes failed: " << st.error_message() << "\n";
        }
        std::this_thread::sleep_until(tick + std::chrono::milliseconds(a.interval_ms));
    }
    std::cout << "edge: done readings_created=" << sent << " readings_failed=" << failed
              << " samples_published=" << published << " sessions_reissued=" << reissued
              << std::endl;
    return failed == 0 ? 0 : 6;
}
