// Generated by harpia Stage 8 (CRUDL). Do not edit.
#ifndef HARPIA_CRUDL_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_CRUDL_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da

#include <cstdint>
#include <string>
#include <vector>

#include <soci/soci.h>
#include "protofiles/beacon_log_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

namespace harpia {
namespace db {

// Data-access object for beacon_log over the "beacon_log_table" table. Wraps a soci::session
// the caller owns; being SOCI-based it runs on any backend (SQLite, PostgreSQL,
// ...). Scalar/enum fields, singular FKs to table-bearing messages, the
// flattened sub-fields of a non-table composed field, and map<K,V> + repeated
// scalar fields (as child tables keyed by the primary key) are persisted.
//
// Every method returns false instead of throwing: SOCI signals errors with
// exceptions, so each body is wrapped in try/catch. use()/into() bind by
// reference, so bound values are copied into named locals first; nullable reads
// are guarded by an indicator.
class beacon_log_dao {
public:
    explicit beacon_log_dao(::soci::session& db) : db_(db) {}

    bool create_table() {
        try {
            db_ << "CREATE TABLE IF NOT EXISTS \"beacon_log_table\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\" INTEGER PRIMARY KEY, \"label\" TEXT, \"strength\" INTEGER, \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ORIGINATOR\" TEXT);";
            return true;
        } catch (const std::exception&) { return false; }
    }
    bool drop_table() {
        try {
            db_ << "DROP TABLE IF EXISTS \"beacon_log_table\";";
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool create(const ::beacon_log& msg) {
        try {
            int c0 = msg.id_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c1 = msg.label();
            int c2 = msg.strength();
            std::string c3 = msg.status_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c4 = msg.error_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c5 = msg.originator();
            db_ << "INSERT INTO \"beacon_log_table\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"label\", \"strength\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR\") VALUES (:c0, :c1, :c2, :c3, :c4, :c5)",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(c5);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool read(std::int64_t id, ::beacon_log* msg) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            int l2 = 0; ::soci::indicator n2;
            std::string l3; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            db_ << "SELECT \"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"label\", \"strength\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR\" FROM \"beacon_log_table\" WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :id", ::soci::use(id),
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5);
            if (!db_.got_data()) return false;
                msg->set_id_c96f8fd7f45108efee5a8ecb43eab1da(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_label(n1 == ::soci::i_ok ? l1 : std::string());
                msg->set_strength(n2 == ::soci::i_ok ? l2 : 0);
                msg->set_status_c96f8fd7f45108efee5a8ecb43eab1da(n3 == ::soci::i_ok ? l3 : std::string());
                msg->set_error_c96f8fd7f45108efee5a8ecb43eab1da(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_originator(n5 == ::soci::i_ok ? l5 : std::string());
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool update(const ::beacon_log& msg) {
        try {
            std::string c0 = msg.label();
            int c1 = msg.strength();
            std::string c2 = msg.status_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c3 = msg.error_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c4 = msg.originator();
            long long cid = msg.id_c96f8fd7f45108efee5a8ecb43eab1da();
            db_ << "UPDATE \"beacon_log_table\" SET \"label\" = :c0, \"strength\" = :c1, \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" = :c2, \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" = :c3, \"ORIGINATOR\" = :c4 WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :cid",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(cid);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool remove(std::int64_t id) {
        try {
            db_ << "DELETE FROM \"beacon_log_table\" WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :id", ::soci::use(id);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool list(std::vector<::beacon_log>* out) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            int l2 = 0; ::soci::indicator n2;
            std::string l3; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            ::soci::statement st = (db_.prepare << "SELECT \"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"label\", \"strength\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR\" FROM \"beacon_log_table\"",
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5));
            st.execute();
            while (st.fetch()) {
                ::beacon_log row;
                ::beacon_log* msg = &row;
                msg->set_id_c96f8fd7f45108efee5a8ecb43eab1da(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_label(n1 == ::soci::i_ok ? l1 : std::string());
                msg->set_strength(n2 == ::soci::i_ok ? l2 : 0);
                msg->set_status_c96f8fd7f45108efee5a8ecb43eab1da(n3 == ::soci::i_ok ? l3 : std::string());
                msg->set_error_c96f8fd7f45108efee5a8ecb43eab1da(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_originator(n5 == ::soci::i_ok ? l5 : std::string());
                out->push_back(row);
            }
            return true;
        } catch (const std::exception&) { return false; }
    }

    // Paginated list: LIMIT/OFFSET applied server-side. offset is 0-based.
    bool list(std::vector<::beacon_log>* out, long long offset, long long limit) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            int l2 = 0; ::soci::indicator n2;
            std::string l3; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            ::soci::statement st = (db_.prepare << "SELECT \"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"label\", \"strength\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR\" FROM \"beacon_log_table\" LIMIT :lim OFFSET :off", ::soci::use(limit), ::soci::use(offset),
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5));
            st.execute();
            while (st.fetch()) {
                ::beacon_log row;
                ::beacon_log* msg = &row;
                msg->set_id_c96f8fd7f45108efee5a8ecb43eab1da(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_label(n1 == ::soci::i_ok ? l1 : std::string());
                msg->set_strength(n2 == ::soci::i_ok ? l2 : 0);
                msg->set_status_c96f8fd7f45108efee5a8ecb43eab1da(n3 == ::soci::i_ok ? l3 : std::string());
                msg->set_error_c96f8fd7f45108efee5a8ecb43eab1da(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_originator(n5 == ::soci::i_ok ? l5 : std::string());
                out->push_back(row);
            }
            return true;
        } catch (const std::exception&) { return false; }
    }

private:
    ::soci::session& db_;
};

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_CRUDL_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da
