// Generated by harpia Stage 8 (CRUDL). Do not edit.
#ifndef HARPIA_CRUDL_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_CRUDL_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <cstdint>
#include <string>
#include <vector>

#include <soci/soci.h>
#include "protofiles/users_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

namespace harpia {
namespace db {

// Data-access object for users over the "user_table" table. Wraps a soci::session
// the caller owns; being SOCI-based it runs on any backend (SQLite, PostgreSQL,
// ...). Scalar/enum fields, singular FKs to table-bearing messages, the
// flattened sub-fields of a non-table composed field, and map<K,V> + repeated
// scalar fields (as child tables keyed by the primary key) are persisted.
//
// Every method returns false instead of throwing: SOCI signals errors with
// exceptions, so each body is wrapped in try/catch. use()/into() bind by
// reference, so bound values are copied into named locals first; nullable reads
// are guarded by an indicator.
class users_dao {
public:
    explicit users_dao(::soci::session& db) : db_(db) {}

    bool create_table() {
        try {
            db_ << "CREATE TABLE IF NOT EXISTS \"user_table\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\" INTEGER PRIMARY KEY, \"address\" TEXT, \"name\" TEXT, \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT);";
            return true;
        } catch (const std::exception&) { return false; }
    }
    bool drop_table() {
        try {
            db_ << "DROP TABLE IF EXISTS \"user_table\";";
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool create(const ::users& msg) {
        try {
            int c0 = msg.id_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c1 = msg.address();
            std::string c2 = msg.name();
            std::string c3 = msg.status_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c4 = msg.error_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c5 = msg.originator_c96f8fd7f45108efee5a8ecb43eab1da();
            db_ << "INSERT INTO \"user_table\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"address\", \"name\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\") VALUES (:c0, :c1, :c2, :c3, :c4, :c5)",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(c5);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool read(std::int64_t id, ::users* msg) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            std::string l2; ::soci::indicator n2;
            std::string l3; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            db_ << "SELECT \"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"address\", \"name\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" FROM \"user_table\" WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :id", ::soci::use(id),
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5);
            if (!db_.got_data()) return false;
                msg->set_id_c96f8fd7f45108efee5a8ecb43eab1da(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_address(n1 == ::soci::i_ok ? l1 : std::string());
                msg->set_name(n2 == ::soci::i_ok ? l2 : std::string());
                msg->set_status_c96f8fd7f45108efee5a8ecb43eab1da(n3 == ::soci::i_ok ? l3 : std::string());
                msg->set_error_c96f8fd7f45108efee5a8ecb43eab1da(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_originator_c96f8fd7f45108efee5a8ecb43eab1da(n5 == ::soci::i_ok ? l5 : std::string());
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool update(const ::users& msg) {
        try {
            std::string c0 = msg.address();
            std::string c1 = msg.name();
            std::string c2 = msg.status_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c3 = msg.error_c96f8fd7f45108efee5a8ecb43eab1da();
            std::string c4 = msg.originator_c96f8fd7f45108efee5a8ecb43eab1da();
            long long cid = msg.id_c96f8fd7f45108efee5a8ecb43eab1da();
            db_ << "UPDATE \"user_table\" SET \"address\" = :c0, \"name\" = :c1, \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" = :c2, \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" = :c3, \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" = :c4 WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :cid",
                ::soci::use(c0), ::soci::use(c1), ::soci::use(c2), ::soci::use(c3), ::soci::use(c4), ::soci::use(cid);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool remove(std::int64_t id) {
        try {
            db_ << "DELETE FROM \"user_table\" WHERE \"ID_c96f8fd7f45108efee5a8ecb43eab1da\" = :id", ::soci::use(id);
            return true;
        } catch (const std::exception&) { return false; }
    }

    bool list(std::vector<::users>* out) {
        try {
            int l0 = 0; ::soci::indicator n0;
            std::string l1; ::soci::indicator n1;
            std::string l2; ::soci::indicator n2;
            std::string l3; ::soci::indicator n3;
            std::string l4; ::soci::indicator n4;
            std::string l5; ::soci::indicator n5;
            ::soci::statement st = (db_.prepare << "SELECT \"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"address\", \"name\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" FROM \"user_table\"",
                ::soci::into(l0, n0), ::soci::into(l1, n1), ::soci::into(l2, n2), ::soci::into(l3, n3), ::soci::into(l4, n4), ::soci::into(l5, n5));
            st.execute();
            while (st.fetch()) {
                ::users row;
                ::users* msg = &row;
                msg->set_id_c96f8fd7f45108efee5a8ecb43eab1da(n0 == ::soci::i_ok ? l0 : 0);
                msg->set_address(n1 == ::soci::i_ok ? l1 : std::string());
                msg->set_name(n2 == ::soci::i_ok ? l2 : std::string());
                msg->set_status_c96f8fd7f45108efee5a8ecb43eab1da(n3 == ::soci::i_ok ? l3 : std::string());
                msg->set_error_c96f8fd7f45108efee5a8ecb43eab1da(n4 == ::soci::i_ok ? l4 : std::string());
                msg->set_originator_c96f8fd7f45108efee5a8ecb43eab1da(n5 == ::soci::i_ok ? l5 : std::string());
                out->push_back(row);
            }
            return true;
        } catch (const std::exception&) { return false; }
    }

private:
    ::soci::session& db_;
};

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_CRUDL_USERS_c96f8fd7f45108efee5a8ecb43eab1da
