// Generated by harpia Stage 13 (gRPC service impl). Do not edit.
#ifndef HARPIA_GRPC_TOP_USERS_6cea4c29647b10eb99b42c762ac09f75
#define HARPIA_GRPC_TOP_USERS_6cea4c29647b10eb99b42c762ac09f75

#include <vector>

#include <grpcpp/grpcpp.h>
#include "sqlite3.h"
#include "protofiles/top_users_6cea4c29647b10eb99b42c762ac09f75_service.grpc.pb.h"
#include "db/top_users_6cea4c29647b10eb99b42c762ac09f75_crudl.h"

// gRPC service implementation for top_users, backed by the CRUDL DAO -- the RPCs of
// the generated top_users_Service are wired to create/read/list over SQLite:
//   push(msg)      -> dao.create(msg)             -> errorCode
//   pullByID(id)   -> dao.read(id)                -> top_users_Message (NOT_FOUND)
//   streamSrc()    -> dao.list() streamed back    -> stream top_users_Message
//   heartBeat(hb)  -> echo                         (no CRUDL)
// Construct with a sqlite3* the caller owns; register with a grpc::ServerBuilder.
// (Access-credential enforcement over gRPC metadata is deferred.)
namespace harpia {
namespace grpc_svc {

class top_users_service final
    : public ::frameworkProtos::top_users_Service::Service {
public:
    explicit top_users_service(::sqlite3* db) : db_(db) {}

    ::grpc::Status push(::grpc::ServerContext*,
                        const ::frameworkProtos::top_users_Message* request,
                        ::frameworkProtos::errorCode* response) override {
        ::harpia::db::top_users_dao dao(db_);
        const bool ok = dao.create(request->msg());
        response->set_code(ok ? 0 : 1);
        response->set_message(ok ? "ok" : "create failed");
        return ::grpc::Status::OK;
    }

    ::grpc::Status pullByID(::grpc::ServerContext*,
                            const ::frameworkProtos::top_users_ID* request,
                            ::frameworkProtos::top_users_Message* response) override {
        ::harpia::db::top_users_dao dao(db_);
        if (!dao.read(request->id(), response->mutable_msg())) {
            return ::grpc::Status(::grpc::StatusCode::NOT_FOUND, "not found");
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status streamSrc(
            ::grpc::ServerContext*,
            const ::frameworkProtos::top_users_Stream*,
            ::grpc::ServerWriter< ::frameworkProtos::top_users_Message>* writer) override {
        ::harpia::db::top_users_dao dao(db_);
        std::vector< ::top_users> rows;
        if (!dao.list(&rows)) {
            return ::grpc::Status(::grpc::StatusCode::INTERNAL, "list failed");
        }
        for (const auto& r : rows) {
            ::frameworkProtos::top_users_Message m;
            *m.mutable_msg() = r;
            writer->Write(m);
        }
        return ::grpc::Status::OK;
    }

    ::grpc::Status heartBeat(::grpc::ServerContext*,
                             const ::frameworkProtos::top_users_HeartBeat* request,
                             ::frameworkProtos::top_users_HeartBeat* response) override {
        *response = *request;
        return ::grpc::Status::OK;
    }

private:
    ::sqlite3* db_;
};

}  // namespace grpc_svc
}  // namespace harpia

#endif  // HARPIA_GRPC_TOP_USERS_6cea4c29647b10eb99b42c762ac09f75
