// Generated by harpia Stage 10 (phi-field registry -- Track F / F.3). Do not edit.
//
// The schema's `phi`-tagged (message, field) pairs (from variable.is_phi, F2).
// harpia_redaction.h consults this so the unified serialization path renders
// every `phi` value as a fixed placeholder by default -- one hook, all three
// formats.
#ifndef HARPIA_PHI_REGISTRY_H
#define HARPIA_PHI_REGISTRY_H

#include <array>
#include <cstddef>
#include <string_view>

namespace harpia {
namespace serialize {
namespace phi {

struct PhiField {
    std::string_view message;
    std::string_view field;
};

inline constexpr std::size_t kPhiFieldCount = 8;
inline constexpr std::array<PhiField, kPhiFieldCount> kPhiFields = {{
    harpia::serialize::phi::PhiField{"patient_vitals", "patient_id"},
    harpia::serialize::phi::PhiField{"patient_vitals", "heart_rate"},
    harpia::serialize::phi::PhiField{"alarm_event", "patient_id"},
    harpia::serialize::phi::PhiField{"lab_result", "subject_ref"},
    harpia::serialize::phi::PhiField{"lab_result", "analyte_code"},
    harpia::serialize::phi::PhiField{"lab_result", "value_scaled"},
    harpia::serialize::phi::PhiField{"lab_result", "reference_high"},
    harpia::serialize::phi::PhiField{"vitals_publication", "patient_ref"}
}};

// is (message, field) a `phi` field?
inline constexpr bool is_phi(std::string_view message, std::string_view field) {
    for (const auto& e : kPhiFields) {
        if (e.message == message && e.field == field) {
            return true;
        }
    }
    return false;
}

// does `message` declare at least one `phi` field directly? (a nested-message
// tree walk is the caller's job -- it needs the runtime descriptor.)
inline constexpr bool message_has_phi(std::string_view message) {
    for (const auto& e : kPhiFields) {
        if (e.message == message) {
            return true;
        }
    }
    return false;
}

}  // namespace phi
}  // namespace serialize
}  // namespace harpia

#endif  // HARPIA_PHI_REGISTRY_H
