"""HTTP capability advertisement: ``GET <base>/capabilities``.

Generated by harpia (python target), the Python side of the C++
``capability/capabilities_3ac5d8b36fc7dcfb70888145147ddfb7_http.h``. Do not edit. One route on the
router REST and SOAP share (``HttpServer`` registers it under its REST
base); the body is ``capabilities_Response`` as protobuf JSON
(``{"messageTypes":[...]}``, byte-identical to C++). Ungated, like
``heartBeat``. Clients ask with :func:`harpia_runtime.capability.http.negotiate`.
"""
from harpia_generated.protofiles.capabilities_service_pb2 import capabilities_Response
from harpia_runtime.http.router import Request, Response, Router
from harpia_runtime.json import to_json

#: the advertised message-type names
MESSAGE_TYPES: tuple[str, ...] = (
    'alarm_event',
    'another_sage',
    'beacon_log',
    'bed_state',
    'courier',
    'crew',
    'crew_quarters',
    'data',
    'journey',
    'lab_result',
    'outpost',
    'parcel',
    'patient_vitals',
    'prince',
    'pump_tick',
    'queen',
    'reception_desk',
    'route',
    'sensor_feed',
    'shipment',
    'telemetry',
    'top_users',
    'trace_row',
    'users',
    'vault',
    'vip_users',
    'vitals_publication',
    'waypoint',
)


def register_capabilities(router: Router, base: str = "") -> None:
    """Register ``GET <base>/capabilities`` on ``router``."""
    body = to_json(capabilities_Response(message_types=MESSAGE_TYPES)).encode()

    def handler(req: Request) -> Response:
        return Response(200, body, "application/json")
    router.add("GET", base + "/capabilities", handler)
