"""gRPC servicer for ``alarm_event`` (``frameworkProtos.alarm_event_Service``).

Generated by harpia (python target), the Python side of the C++
``grpc/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_grpc.h``. Do not edit. RPCs and status codes are
documented in :mod:`harpia_runtime.grpc_service`.

Access gate: the flat generated credential -- ``x-user: alarm_event`` and ``x-pswd: <hash>`` call metadata, else ``UNAUTHENTICATED``.
"""
from typing import Any

from harpia_generated.db.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    alarm_event_dao,
)
from harpia_generated.protofiles import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2 as service_pb2,
)
from harpia_generated.protofiles import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2_grpc as service_grpc,
)
from harpia_generated.protofiles.errorCode_pb2 import errorCode
from harpia_runtime.grpc_service import CrudServicer, flat_gate


class alarm_event_Service(CrudServicer):
    """``push`` / ``pullByID`` / ``streamSrc`` / ``heartBeat`` for ``alarm_event``."""

    DAO = alarm_event_dao
    WRAPPER = service_pb2.alarm_event_Message
    ERROR_CODE = errorCode
    GATE = flat_gate('alarm_event', '3ac5d8b36fc7dcfb70888145147ddfb7')


def add_to_server(servicer: alarm_event_Service, server: Any) -> None:
    """Register ``servicer`` on a ``grpc.Server``."""
    # protoc's grpc plugin emits untyped code
    service_grpc.add_alarm_event_ServiceServicer_to_server(  # type: ignore[no-untyped-call]
        servicer, server)
