"""gRPC servicer for ``crew`` (``frameworkProtos.crew_Service``).

Generated by harpia (python target), the Python side of the C++
``grpc/crew_3ac5d8b36fc7dcfb70888145147ddfb7_grpc.h``. Do not edit. RPCs and status codes are
documented in :mod:`harpia_runtime.grpc_service`.

Access gate: the flat generated credential -- ``x-user: crew`` and ``x-pswd: <hash>`` call metadata, else ``UNAUTHENTICATED``.
"""
from typing import Any

from harpia_generated.db.crew_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    crew_dao,
)
from harpia_generated.protofiles import (
    crew_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2 as service_pb2,
)
from harpia_generated.protofiles import (
    crew_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2_grpc as service_grpc,
)
from harpia_generated.protofiles.errorCode_pb2 import errorCode
from harpia_runtime.grpc_service import CrudServicer, flat_gate


class crew_Service(CrudServicer):
    """``push`` / ``pullByID`` / ``streamSrc`` / ``heartBeat`` for ``crew``."""

    DAO = crew_dao
    WRAPPER = service_pb2.crew_Message
    ERROR_CODE = errorCode
    GATE = flat_gate('crew', '3ac5d8b36fc7dcfb70888145147ddfb7')


def add_to_server(servicer: crew_Service, server: Any) -> None:
    """Register ``servicer`` on a ``grpc.Server``."""
    # protoc's grpc plugin emits untyped code
    service_grpc.add_crew_ServiceServicer_to_server(  # type: ignore[no-untyped-call]
        servicer, server)
