"""gRPC servicer for ``top_users`` (``frameworkProtos.top_users_Service``).

Generated by harpia (python target), the Python side of the C++
``grpc/top_users_3ac5d8b36fc7dcfb70888145147ddfb7_grpc.h``. Do not edit. RPCs and status codes are
documented in :mod:`harpia_runtime.grpc_service`.

Access gate: RBAC (``protected``, or hardened and not ``open``) -- the verified client-certificate CN mapped to a role by ``HARPIA_RBAC_MAP`` (:mod:`harpia_runtime.rbac`); ``UNAUTHENTICATED`` without an identity, ``PERMISSION_DENIED`` when its role may not perform the RPC. Needs a server that requires client certificates (see :mod:`harpia_runtime.rbac_gates`).
"""
from typing import Any

from harpia_generated.db.top_users_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    top_users_dao,
)
from harpia_generated.protofiles import (
    top_users_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2 as service_pb2,
)
from harpia_generated.protofiles import (
    top_users_3ac5d8b36fc7dcfb70888145147ddfb7_service_pb2_grpc as service_grpc,
)
from harpia_generated.protofiles.errorCode_pb2 import errorCode
from harpia_runtime.grpc_service import CrudServicer
from harpia_runtime.rbac_gates import grpc_rbac_gate


class top_users_Service(CrudServicer):
    """``push`` / ``pullByID`` / ``streamSrc`` / ``heartBeat`` for ``top_users``."""

    DAO = top_users_dao
    WRAPPER = service_pb2.top_users_Message
    ERROR_CODE = errorCode
    GATE = grpc_rbac_gate('top_users')


def add_to_server(servicer: top_users_Service, server: Any) -> None:
    """Register ``servicer`` on a ``grpc.Server``."""
    # protoc's grpc plugin emits untyped code
    service_grpc.add_top_users_ServiceServicer_to_server(  # type: ignore[no-untyped-call]
        servicer, server)
