"""In-process event channel for ``alarm_event``.

Generated by harpia (python target), the port of the C++
``events/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_events.h``. Do not edit. The ``event`` modifier
gives it cached last-value semantics (see :mod:`harpia_runtime.events`)::

    sub = alarm_event_channel().subscribe(lambda msg: ...)
    alarm_event_channel().publish(msg)
    alarm_event_channel().unsubscribe(sub)

Each publish records a value-free ``phi_event_dispatch`` audit for its
``phi`` fields (patient_id).
"""
from harpia_generated.protofiles.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    alarm_event,
)
from harpia_runtime.events import CacheMode, EventChannel

_CHANNEL = EventChannel[alarm_event](
    CacheMode.CACHED, 'alarm_event_table', 'patient_id')


def alarm_event_channel() -> EventChannel[alarm_event]:
    """The one :class:`~harpia_runtime.events.EventChannel` for ``alarm_event``."""
    return _CHANNEL
