"""In-process event channel for ``bed_state``.

Generated by harpia (python target), the port of the C++
``events/bed_state_3ac5d8b36fc7dcfb70888145147ddfb7_events.h``. Do not edit. The ``event`` modifier
gives it cached last-value semantics (see :mod:`harpia_runtime.events`)::

    sub = bed_state_channel().subscribe(lambda msg: ...)
    bed_state_channel().publish(msg)
    bed_state_channel().unsubscribe(sub)

This type carries no ``phi``: the channel never audits a publish.
"""
from harpia_generated.protofiles.bed_state_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    bed_state,
)
from harpia_runtime.events import CacheMode, EventChannel

_CHANNEL = EventChannel[bed_state](
    CacheMode.CACHED, '', '')


def bed_state_channel() -> EventChannel[bed_state]:
    """The one :class:`~harpia_runtime.events.EventChannel` for ``bed_state``."""
    return _CHANNEL
