"""In-process event channel for ``users``.

Generated by harpia (python target), the port of the C++
``events/users_3ac5d8b36fc7dcfb70888145147ddfb7_events.h``. Do not edit. The ``event`` modifier
gives it cached last-value semantics (see :mod:`harpia_runtime.events`)::

    sub = users_channel().subscribe(lambda msg: ...)
    users_channel().publish(msg)
    users_channel().unsubscribe(sub)

This type carries no ``phi``: the channel never audits a publish.
"""
from harpia_generated.protofiles.users_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    users,
)
from harpia_runtime.events import CacheMode, EventChannel

_CHANNEL = EventChannel[users](
    CacheMode.CACHED, '', '')


def users_channel() -> EventChannel[users]:
    """The one :class:`~harpia_runtime.events.EventChannel` for ``users``."""
    return _CHANNEL
