"""Stage 8 (database) -- environment-level public/private DB registry (Track K).

Every other Database adapter emits one artifact *per message*. This one emits a
single project-wide header, ``generated/cpp/db/harpia_db_registry.h``, listing
every table this project owns together with its visibility (PUBLIC / PRIVATE,
from the message's trailing ``;`` -> ``visibility``) and the owning project
name (``project.harpia.yaml`` -> ``project:``, via ``ComplianceContext``).

It also emits the access check the registry exists for:

    harpia::db::db_access_check(requesting_project, target_table)
        -> ALLOWED
         | DENIED_PRIVATE_CROSS_PROJECT   (PRIVATE table, different project)
         | DENIED_UNKNOWN_TABLE           (no such table in this registry)

A PUBLIC table is reachable from any project; a PRIVATE one only from code
built for the same project name. The header is self-contained (constexpr
table, no .cpp, no linkage) so a second generated project can ``#include`` it
directly to ask "am I allowed at project X's table?".

Purely additive: no existing per-message SQL/DAO/proto output changes, so a
single-project build is byte-for-byte unaffected.
"""
import os

from Logger.logger import logger
from Util.util import write_if_different
from Compliance.context import DEFAULT_PROJECT

REGISTRY_FILE = "harpia_db_registry.h"
_GUARD = "HARPIA_DB_REGISTRY_H"


class DbRegistryAdapter:
    def __init__(self, messages, dest, compliance=None) -> None:
        self.compliance = compliance
        self.messages = messages
        self.dest = dest
        self.outDir = os.path.join(dest, "generated", "cpp", "db")
        self.project = getattr(compliance, "project", None) or DEFAULT_PROJECT
        self.log = logger(outFile=None, moduleName="DbRegistryAdapter")

    def _entries(self):
        """``[(table_name, visibility), ...]`` for every table-bearing message,
        deduped by table name (first declaration wins) and sorted for a
        deterministic header, plus a list of any table name a later message
        re-declared with a *different* visibility -- a pre-existing same-name
        collision (see ``users``/``top_users`` in the test fixture) this
        adapter surfaces rather than silently resolves."""
        seen = {}
        conflicts = []
        for msg in self.messages:
            if getattr(msg, "isEnum", False) or not msg.tableName:
                continue
            vis = (msg.visibility or "PUBLIC").upper()
            if msg.tableName in seen:
                if seen[msg.tableName] != vis:
                    conflicts.append((msg.tableName, msg.name, vis))
                continue
            seen[msg.tableName] = vis
        return sorted(seen.items()), conflicts

    def _render(self, entries, conflicts):
        proj = _cpp_str(self.project)
        rows = ",\n".join(
            '    harpia::db::RegistryEntry{{{table}, harpia::db::Visibility::{vis}, {owner}}}'.format(
                table=_cpp_str(table), vis=vis, owner=proj)
            for table, vis in entries)
        # literal C++ double-braces for std::array aggregate init (-Wmissing-braces)
        body = "{{\n" + rows + "\n}}" if entries else "{}"
        notes = "".join(
            '// note: table {} is also declared {} by message "{}" -- kept the '
            "first declaration above\n".format(_cpp_str(t), v, n)
            for t, n, v in conflicts)
        return _TEMPLATE.format(guard=_GUARD, project=proj, count=len(entries),
                                rows=body, notes=notes)

    def Process(self):
        os.makedirs(self.outDir, exist_ok=True)
        entries, conflicts = self._entries()
        write_if_different(os.path.join(self.outDir, REGISTRY_FILE),
                           self._render(entries, conflicts))
        self.log.print(
            "generated public/private DB registry ({} table(s), project {!r}) "
            "into {}".format(len(entries), self.project, self.outDir))
        return None


def _cpp_str(s):
    """A C++ string-literal for `s` (only `\\` and `"` need escaping for the
    identifiers/names that reach here)."""
    return '"{}"'.format(str(s).replace("\\", "\\\\").replace('"', '\\"'))


_TEMPLATE = '''\
// Generated by harpia Stage 8 (public/private DB registry -- Track K). Do not edit.
//
// The environment-level registry of every table this project owns, each tagged
// PUBLIC or PRIVATE, plus the cross-project access check it exists for. A
// PUBLIC table is reachable from any project; a PRIVATE one only from code
// built for this same project name. Self-contained (constexpr, header-only) so
// another generated project can #include this to check access to our tables.
#ifndef {guard}
#define {guard}

#include <array>
#include <cstddef>
#include <string_view>

namespace harpia {{
namespace db {{

enum class Visibility {{ PUBLIC, PRIVATE }};

enum class AccessDecision {{
    ALLOWED,
    DENIED_PRIVATE_CROSS_PROJECT,
    DENIED_UNKNOWN_TABLE,
}};

struct RegistryEntry {{
    std::string_view table;
    Visibility visibility;
    std::string_view owner_project;
}};

// This build's project name (project.harpia.yaml -> `project:`).
inline constexpr std::string_view kProjectName = {project};

// One row per table-bearing message, deduped by table name, sorted.
{notes}inline constexpr std::size_t kRegistrySize = {count};
inline constexpr std::array<RegistryEntry, kRegistrySize> kRegistry = {rows};

inline constexpr const RegistryEntry* find_entry(std::string_view table) {{
    for (const auto& entry : kRegistry) {{
        if (entry.table == table) {{
            return &entry;
        }}
    }}
    return nullptr;
}}

// Is `requesting_project` allowed to touch `target_table`?
inline constexpr AccessDecision db_access_check(std::string_view requesting_project,
                                                std::string_view target_table) {{
    const RegistryEntry* entry = find_entry(target_table);
    if (entry == nullptr) {{
        return AccessDecision::DENIED_UNKNOWN_TABLE;
    }}
    if (entry->visibility == Visibility::PUBLIC) {{
        return AccessDecision::ALLOWED;
    }}
    if (requesting_project == entry->owner_project) {{
        return AccessDecision::ALLOWED;
    }}
    return AccessDecision::DENIED_PRIVATE_CROSS_PROJECT;
}}

// Convenience: is *this* build (kProjectName) allowed at `target_table`?
inline constexpr AccessDecision db_access_check(std::string_view target_table) {{
    return db_access_check(kProjectName, target_table);
}}

}}  // namespace db
}}  // namespace harpia

#endif  // {guard}
'''
