// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_JOURNEY_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_XML_JOURNEY_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/journey_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// XML for journey is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // journey -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> journey
namespace harpia {
namespace xml {

// XSD schema for journey
inline std::string journey_xsd() {
    return ::harpia::xml::xsd(::journey::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_JOURNEY_3ac5d8b36fc7dcfb70888145147ddfb7
