// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_KING_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_XML_KING_c96f8fd7f45108efee5a8ecb43eab1da

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/king_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

// XML for king is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // king -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> king
namespace harpia {
namespace xml {

// XSD schema for king
inline std::string king_xsd() {
    return ::harpia::xml::xsd(::king::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_KING_c96f8fd7f45108efee5a8ecb43eab1da
