// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_XML_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/patient_vitals_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// XML for patient_vitals is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // patient_vitals -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> patient_vitals
namespace harpia {
namespace xml {

// XSD schema for patient_vitals
inline std::string patient_vitals_xsd() {
    return ::harpia::xml::xsd(::patient_vitals::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_PATIENT_VITALS_3ac5d8b36fc7dcfb70888145147ddfb7
