// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_POPE_738be851643f8e1a41c121caf519d41f
#define HARPIA_XML_POPE_738be851643f8e1a41c121caf519d41f

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/pope_738be851643f8e1a41c121caf519d41f.pb.h"

// XML for pope is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // pope -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> pope
namespace harpia {
namespace xml {

// XSD schema for pope
inline std::string pope_xsd() {
    return ::harpia::xml::xsd(::pope::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_POPE_738be851643f8e1a41c121caf519d41f
