// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_PRINCE_6cea4c29647b10eb99b42c762ac09f75
#define HARPIA_XML_PRINCE_6cea4c29647b10eb99b42c762ac09f75

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/prince_6cea4c29647b10eb99b42c762ac09f75.pb.h"

// XML for prince is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // prince -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> prince
namespace harpia {
namespace xml {

// XSD schema for prince
inline std::string prince_xsd() {
    return ::harpia::xml::xsd(::prince::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_PRINCE_6cea4c29647b10eb99b42c762ac09f75
