// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_PRINCE_734126ee6efdfbd64a1678bf49ee9683
#define HARPIA_XML_PRINCE_734126ee6efdfbd64a1678bf49ee9683

#include "xml/harpia_xml.h"
#include "protofiles/prince_734126ee6efdfbd64a1678bf49ee9683.pb.h"

// XML for prince is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // prince -> XML

#endif  // HARPIA_XML_PRINCE_734126ee6efdfbd64a1678bf49ee9683
