// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_ROUTE_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_XML_ROUTE_c96f8fd7f45108efee5a8ecb43eab1da

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/route_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

// XML for route is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // route -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> route
namespace harpia {
namespace xml {

// XSD schema for route
inline std::string route_xsd() {
    return ::harpia::xml::xsd(::route::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_ROUTE_c96f8fd7f45108efee5a8ecb43eab1da
