// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_VIP_USERS_738be851643f8e1a41c121caf519d41f
#define HARPIA_XML_VIP_USERS_738be851643f8e1a41c121caf519d41f

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/vip_users_738be851643f8e1a41c121caf519d41f.pb.h"

// XML for vip_users is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // vip_users -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> vip_users
namespace harpia {
namespace xml {

// XSD schema for vip_users
inline std::string vip_users_xsd() {
    return ::harpia::xml::xsd(::vip_users::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_VIP_USERS_738be851643f8e1a41c121caf519d41f
