"""DDS transport for ``alarm_event`` (topic ``alarm_event``, type ``harpia_dds::Frame``).

QoS: ``critical`` -- reliable, keep-all, at most 128 samples (design-rules §4a).

Generated by harpia (python target), the Python side of the C++
``dds/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_dds.h``. Do not edit. Publish/receive semantics are
documented in :mod:`harpia_runtime.dds.transport`::

    pub = alarm_event_publisher()
    pub.publish(msg)
    sub = alarm_event_subscriber()
    got = sub.receive(timeout=1.0)
"""
from harpia_generated.protofiles.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    alarm_event,
)
from harpia_runtime.dds.transport import Publisher, Subscriber


class alarm_event_publisher(Publisher[alarm_event]):
    """Publishes ``alarm_event`` on topic ``alarm_event``."""

    MESSAGE = alarm_event
    NAME = 'alarm_event'
    CRITICAL = True
    QUEUE_DEPTH = 128


class alarm_event_subscriber(Subscriber[alarm_event]):
    """Receives ``alarm_event`` from topic ``alarm_event``."""

    MESSAGE = alarm_event
    NAME = 'alarm_event'
    CRITICAL = True
    QUEUE_DEPTH = 128
