// Generated by harpia Stage 13 (DDS transport). Do not edit.
#ifndef HARPIA_DDS_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_DDS_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7

#include <cstdint>
#include <string>
#include <vector>

#include "dds/dds.hpp"
#include "harpia_dds_frame.hpp"
#include "protofiles/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

namespace harpia {
namespace dds_transport {

// QoS profile for `alarm_event` -- §4a ordered/complete: RELIABLE + KEEP_ALL, bounded by RESOURCE_LIMITS (`critical` message type)
// (harpia_sensitive_data_design_rules.md §4; the delivery-guarantee split is
// a schema-level choice, never inferred at runtime). DURABILITY is left at
// VOLATILE: TRANSIENT_LOCAL late-joiner catch-up is a per-use-case open
// question (dds-transport task 2b), not defaulted on here.
inline ::dds::pub::qos::DataWriterQos alarm_event_writer_qos(
    ::dds::pub::qos::DataWriterQos qos) {
    qos << ::dds::core::policy::Reliability::Reliable(
               ::dds::core::Duration::from_secs(10));
    qos << ::dds::core::policy::History::KeepAll();
    qos << ::dds::core::policy::ResourceLimits(
               128, ::dds::core::LENGTH_UNLIMITED,
               ::dds::core::LENGTH_UNLIMITED);
    return qos;
}

inline ::dds::sub::qos::DataReaderQos alarm_event_reader_qos(
    ::dds::sub::qos::DataReaderQos qos) {
    qos << ::dds::core::policy::Reliability::Reliable(
               ::dds::core::Duration::from_secs(10));
    qos << ::dds::core::policy::History::KeepAll();
    qos << ::dds::core::policy::ResourceLimits(
               128, ::dds::core::LENGTH_UNLIMITED,
               ::dds::core::LENGTH_UNLIMITED);
    return qos;
}

// `dds` + `critical`: alarm_event_publisher writes onto topic "alarm_event", alarm_event_subscriber reads from it.
class alarm_event_publisher {
public:
    explicit alarm_event_publisher(
        ::dds::domain::DomainParticipant participant,
        const ::std::string& topic_name = "alarm_event")
        : participant_(participant),
          topic_(participant_, topic_name),
          publisher_(participant_),
          writer_(publisher_, topic_,
                  alarm_event_writer_qos(publisher_.default_datawriter_qos())) {}

    // Serialize `msg` to protobuf and publish it as a harpia_dds::Frame --
    // the same wire payload the ZMQ / gRPC transports move.
    bool publish(const ::alarm_event& msg) {
        ::std::string bytes;
        if (!msg.SerializeToString(&bytes)) return false;
        ::harpia_dds::Frame frame;
        frame.message_type("alarm_event");
        frame.payload(::std::vector<uint8_t>(bytes.begin(), bytes.end()));
        writer_.write(frame);
        return true;
    }

    int32_t matched_subscribers() {
        return writer_.publication_matched_status().current_count();
    }
    ::dds::pub::DataWriter<::harpia_dds::Frame>& writer() { return writer_; }

private:
    ::dds::domain::DomainParticipant participant_;
    ::dds::topic::Topic<::harpia_dds::Frame> topic_;
    ::dds::pub::Publisher publisher_;
    ::dds::pub::DataWriter<::harpia_dds::Frame> writer_;
};

class alarm_event_subscriber {
public:
    explicit alarm_event_subscriber(
        ::dds::domain::DomainParticipant participant,
        const ::std::string& topic_name = "alarm_event")
        : participant_(participant),
          topic_(participant_, topic_name),
          subscriber_(participant_),
          reader_(subscriber_, topic_,
                  alarm_event_reader_qos(subscriber_.default_datareader_qos())) {}

    // Take the oldest available message; false when none is available or the
    // frame did not parse. Bounded to one sample per call so repeated calls
    // drain the reader's history in order (KEEP_ALL for a `critical` type,
    // KEEP_LAST(1) otherwise) without dropping the rest of a batch.
    bool receive(::alarm_event* msg) {
        auto samples = reader_.select().max_samples(1).take();
        for (const auto& s : samples) {
            if (!s.info().valid()) continue;
            const auto& p = s.data().payload();
            return msg->ParseFromArray(p.data(), static_cast<int>(p.size()));
        }
        return false;
    }

    int32_t matched_publishers() {
        return reader_.subscription_matched_status().current_count();
    }
    ::dds::sub::DataReader<::harpia_dds::Frame>& reader() { return reader_; }

private:
    ::dds::domain::DomainParticipant participant_;
    ::dds::topic::Topic<::harpia_dds::Frame> topic_;
    ::dds::sub::Subscriber subscriber_;
    ::dds::sub::DataReader<::harpia_dds::Frame> reader_;
};
}  // namespace dds_transport
}  // namespace harpia

#endif  // HARPIA_DDS_ALARM_EVENT_3ac5d8b36fc7dcfb70888145147ddfb7
