"""Bulk JSON / XML import and export of table ``crew_table`` (``crew``).

Generated by harpia (python target), the port of the C++
``dbio/crew_3ac5d8b36fc7dcfb70888145147ddfb7_dbio.h``. Do not edit. Formats and error handling are
documented in ``harpia_runtime.db.dbio``.
"""
from harpia_generated.db.crew_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    crew_dao,
)
from harpia_runtime.db import dbio

#: the XML export's root element
XML_WRAPPER = 'crew_list'


def export_json(dao: crew_dao) -> str:
    """Every ``crew`` row as newline-delimited JSON."""
    return dbio.export_json(dao)


def import_json(dao: crew_dao, text: str) -> int:
    """Create one ``crew`` row per JSON line; returns the row count."""
    return dbio.import_json(dao, text)


def export_xml(dao: crew_dao) -> str:
    """Every ``crew`` row inside ``<crew_list>``."""
    return dbio.export_xml(dao, XML_WRAPPER)


def import_xml(dao: crew_dao, text: str) -> int:
    """Create one ``crew`` row per element of a ``<crew_list>``
    document; returns the row count."""
    return dbio.import_xml(dao, text)
