// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_PRINCE_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_XML_PRINCE_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/prince_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// XML for prince is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // prince -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> prince
namespace harpia {
namespace xml {

// XSD schema for prince
inline std::string prince_xsd() {
    return ::harpia::xml::xsd(::prince::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_PRINCE_3ac5d8b36fc7dcfb70888145147ddfb7
