// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_XML_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/telemetry_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// XML for telemetry is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // telemetry -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> telemetry
namespace harpia {
namespace xml {

// XSD schema for telemetry
inline std::string telemetry_xsd() {
    return ::harpia::xml::xsd(::telemetry::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_TELEMETRY_3ac5d8b36fc7dcfb70888145147ddfb7
