// Generated by harpia Stage 10 (XML adapter). Do not edit.
#ifndef HARPIA_XML_VAULT_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_XML_VAULT_3ac5d8b36fc7dcfb70888145147ddfb7

#include <string>

#include "xml/harpia_xml.h"
#include "protofiles/vault_3ac5d8b36fc7dcfb70888145147ddfb7.pb.h"

// XML for vault is provided by the generic reflection-based runtime:
//   std::string xml = harpia::xml::to_xml(msg);   // vault -> XML
//   harpia::xml::from_xml(xml, &msg);             // XML -> vault
namespace harpia {
namespace xml {

// XSD schema for vault
inline std::string vault_xsd() {
    return ::harpia::xml::xsd(::vault::descriptor());
}

}  // namespace xml
}  // namespace harpia

#endif  // HARPIA_XML_VAULT_3ac5d8b36fc7dcfb70888145147ddfb7
