// Generated by harpia -- end-to-end demo SERVER (ZMQ PULL).
//
// Binds a %DEMO_MESSAGE% receiver, waits for one message, and prints it as JSON.
// The message type, JSON adapter and ZMQ transport are all harpia-generated; this
// file is message-agnostic apart from the substituted type name.
#include <iostream>
#include <string>

#include <zmq.hpp>

#include "json/%DEMO_MESSAGE%_%DEMO_HASH%_json.h"
#include "zmq/%DEMO_MESSAGE%_%DEMO_HASH%_zmq.h"

int main(int argc, char* argv[]) {
    const std::string endpoint = (argc > 1) ? argv[1] : "tcp://*:5599";

    ::zmq::context_t ctx{1};
    harpia::zmq_transport::%DEMO_MESSAGE%_receiver receiver(ctx, endpoint);
    std::cout << "[server] %DEMO_MESSAGE% receiver bound to " << endpoint
              << ", waiting..." << std::endl;

    ::%DEMO_MESSAGE% msg;
    if (!receiver.recv(&msg)) {
        std::cerr << "[server] receive failed" << std::endl;
        return 1;
    }

    std::string json;
    harpia::json::to_json(msg, &json);
    std::cout << "[server] received: " << json << std::endl;
    return 0;
}
