// Generated by harpia Stage 9 (JSON adapter). Do not edit.
#ifndef HARPIA_JSON_ANOTHER_SAGE_6cea4c29647b10eb99b42c762ac09f75
#define HARPIA_JSON_ANOTHER_SAGE_6cea4c29647b10eb99b42c762ac09f75

#include <string>
#include <google/protobuf/util/json_util.h>
#include "protofiles/another_sage_6cea4c29647b10eb99b42c762ac09f75.pb.h"

namespace harpia {
namespace json {

// message -> JSON
inline bool to_json(const ::another_sage& msg, std::string* out) {
    return ::google::protobuf::util::MessageToJsonString(msg, out).ok();
}

// JSON -> message
inline bool from_json(const std::string& in, ::another_sage* msg) {
    return ::google::protobuf::util::JsonStringToMessage(in, msg).ok();
}

// is the JSON a valid another_sage message?
inline bool is_valid_json(const std::string& in) {
    ::another_sage probe;
    return ::google::protobuf::util::JsonStringToMessage(in, &probe).ok();
}

}  // namespace json
}  // namespace harpia

#endif  // HARPIA_JSON_ANOTHER_SAGE_6cea4c29647b10eb99b42c762ac09f75
