// Generated by harpia Stage 9 (JSON adapter). Do not edit.
#ifndef HARPIA_JSON_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_JSON_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da

#include <string>
#include <google/protobuf/util/json_util.h>
#include "protofiles/beacon_log_c96f8fd7f45108efee5a8ecb43eab1da.pb.h"

namespace harpia {
namespace json {

// message -> JSON
inline bool to_json(const ::beacon_log& msg, std::string* out) {
    return ::google::protobuf::util::MessageToJsonString(msg, out).ok();
}

// JSON -> message
inline bool from_json(const std::string& in, ::beacon_log* msg) {
    return ::google::protobuf::util::JsonStringToMessage(in, msg).ok();
}

// is the JSON a valid beacon_log message?
inline bool is_valid_json(const std::string& in) {
    ::beacon_log probe;
    return ::google::protobuf::util::JsonStringToMessage(in, &probe).ok();
}

}  // namespace json
}  // namespace harpia

#endif  // HARPIA_JSON_BEACON_LOG_c96f8fd7f45108efee5a8ecb43eab1da
