// Generated by harpia Stage 9 (JSON adapter). Do not edit.
#ifndef HARPIA_JSON_POPE_738be851643f8e1a41c121caf519d41f
#define HARPIA_JSON_POPE_738be851643f8e1a41c121caf519d41f

#include <string>
#include <google/protobuf/util/json_util.h>
#include "protofiles/pope_738be851643f8e1a41c121caf519d41f.pb.h"

namespace harpia {
namespace json {

// message -> JSON
inline bool to_json(const ::pope& msg, std::string* out) {
    return ::google::protobuf::util::MessageToJsonString(msg, out).ok();
}

// JSON -> message
inline bool from_json(const std::string& in, ::pope* msg) {
    return ::google::protobuf::util::JsonStringToMessage(in, msg).ok();
}

// is the JSON a valid pope message?
inline bool is_valid_json(const std::string& in) {
    ::pope probe;
    return ::google::protobuf::util::JsonStringToMessage(in, &probe).ok();
}

}  // namespace json
}  // namespace harpia

#endif  // HARPIA_JSON_POPE_738be851643f8e1a41c121caf519d41f
