-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message crew -> table "crew_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "crew_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "name" TEXT,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR" TEXT
);
