-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message patient_vitals -> table "patient_vitals_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "patient_vitals_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "patient_id" TEXT,
    "heart_rate" REAL NOT NULL,
    "device_note" TEXT,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR" TEXT
);
