-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message telemetry -> table "telemetry_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "telemetry_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "label" TEXT,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR" TEXT
);
-- samples: repeated -> child table (see repeated_fields)
-- notes: repeated -> child table (see repeated_fields)
-- gauges: map -> child table (see map_fields)
-- flags: map -> child table (see map_fields)

-- map gauges -> child table "telemetry_table__gauges" (owner -> "telemetry_table")
CREATE TABLE IF NOT EXISTS "telemetry_table__gauges" (
    "owner" INTEGER,
    "key" TEXT,
    "value" INTEGER,
    PRIMARY KEY ("owner", "key")
);
-- map flags -> child table "telemetry_table__flags" (owner -> "telemetry_table")
CREATE TABLE IF NOT EXISTS "telemetry_table__flags" (
    "owner" INTEGER,
    "key" INTEGER,
    "value" TEXT,
    PRIMARY KEY ("owner", "key")
);
-- repeated samples -> child table "telemetry_table__samples" (owner -> "telemetry_table")
CREATE TABLE IF NOT EXISTS "telemetry_table__samples" (
    "owner" INTEGER,
    "ordinal" INTEGER,
    "value" INTEGER,
    PRIMARY KEY ("owner", "ordinal")
);
-- repeated notes -> child table "telemetry_table__notes" (owner -> "telemetry_table")
CREATE TABLE IF NOT EXISTS "telemetry_table__notes" (
    "owner" INTEGER,
    "ordinal" INTEGER,
    "value" TEXT,
    PRIMARY KEY ("owner", "ordinal")
);
