-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message top_users -> table "user_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "user_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "sponsor" TEXT,
    "name" TEXT NOT NULL,
    "myUsers" INTEGER,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT
);
-- members: repeated FK -> vip_users link table (see repeated_fields)

-- repeated members -> child table "user_table__members" (owner -> "user_table")
CREATE TABLE IF NOT EXISTS "user_table__members" (
    "owner" INTEGER,
    "ordinal" INTEGER,
    "value" INTEGER,
    PRIMARY KEY ("owner", "ordinal")
);
