-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message vault -> table "vault_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "vault_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "secret_code" TEXT,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR" TEXT
);
