"""WS-Discovery participant descriptor for ``alarm_event``.

Generated by harpia (python target), the Python side of the C++
``sdc/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_sdc.h``. Do not edit. Advertises ``alarm_event``'s SOAP
endpoint (``POST <soap_url>/alarm_event``) for zero-config discovery by an
SDC/DPWS-aware client -- additive, the endpoint itself is unchanged::

    responder = Responder()
    register_alarm_event_wsdiscovery(responder, "http://host:8080/soap")
    responder.start()
"""
from harpia_runtime.wsdiscovery import Endpoint, Responder

#: stable RFC-4122 v5 endpoint reference (project + message + schema hash)
ENDPOINT_REFERENCE = 'urn:uuid:23bde95c-4a66-539a-a1d8-8e7915aaeead'
#: the fixed generic DPWS device type
DEVICE_TYPE = 'dpws:Device'
#: the Harpia-namespaced per-project scope
SCOPE = 'https://harpia.dev/sdc/scope/default/alarm_event'


def alarm_event_wsdiscovery_endpoint(soap_url: str) -> Endpoint:
    """The advertised endpoint; ``soap_url`` is the deployment's SOAP base
    URL (e.g. ``"http://host:8080/soap"``)."""
    return Endpoint(ENDPOINT_REFERENCE, [DEVICE_TYPE], [SCOPE], soap_url + "/alarm_event")


def register_alarm_event_wsdiscovery(responder: Responder, soap_url: str) -> None:
    """Register ``alarm_event``'s endpoint (before ``responder.start()``)."""
    responder.add(alarm_event_wsdiscovery_endpoint(soap_url))
