"""WS-Discovery participant descriptor for ``beacon_log``.

Generated by harpia (python target), the Python side of the C++
``sdc/beacon_log_3ac5d8b36fc7dcfb70888145147ddfb7_sdc.h``. Do not edit. Advertises ``beacon_log``'s SOAP
endpoint (``POST <soap_url>/beacon_log``) for zero-config discovery by an
SDC/DPWS-aware client -- additive, the endpoint itself is unchanged::

    responder = Responder()
    register_beacon_log_wsdiscovery(responder, "http://host:8080/soap")
    responder.start()
"""
from harpia_runtime.wsdiscovery import Endpoint, Responder

#: stable RFC-4122 v5 endpoint reference (project + message + schema hash)
ENDPOINT_REFERENCE = 'urn:uuid:7897e0ed-b7f1-5166-afc8-d5ed22d73556'
#: the fixed generic DPWS device type
DEVICE_TYPE = 'dpws:Device'
#: the Harpia-namespaced per-project scope
SCOPE = 'https://harpia.dev/sdc/scope/default/beacon_log'


def beacon_log_wsdiscovery_endpoint(soap_url: str) -> Endpoint:
    """The advertised endpoint; ``soap_url`` is the deployment's SOAP base
    URL (e.g. ``"http://host:8080/soap"``)."""
    return Endpoint(ENDPOINT_REFERENCE, [DEVICE_TYPE], [SCOPE], soap_url + "/beacon_log")


def register_beacon_log_wsdiscovery(responder: Responder, soap_url: str) -> None:
    """Register ``beacon_log``'s endpoint (before ``responder.start()``)."""
    responder.add(beacon_log_wsdiscovery_endpoint(soap_url))
