"""WS-Discovery participant descriptor for ``journey``.

Generated by harpia (python target), the Python side of the C++
``sdc/journey_3ac5d8b36fc7dcfb70888145147ddfb7_sdc.h``. Do not edit. Advertises ``journey``'s SOAP
endpoint (``POST <soap_url>/journey``) for zero-config discovery by an
SDC/DPWS-aware client -- additive, the endpoint itself is unchanged::

    responder = Responder()
    register_journey_wsdiscovery(responder, "http://host:8080/soap")
    responder.start()
"""
from harpia_runtime.wsdiscovery import Endpoint, Responder

#: stable RFC-4122 v5 endpoint reference (project + message + schema hash)
ENDPOINT_REFERENCE = 'urn:uuid:097e6c1f-b117-5c76-a157-fa065458b9d2'
#: the fixed generic DPWS device type
DEVICE_TYPE = 'dpws:Device'
#: the Harpia-namespaced per-project scope
SCOPE = 'https://harpia.dev/sdc/scope/default/journey'


def journey_wsdiscovery_endpoint(soap_url: str) -> Endpoint:
    """The advertised endpoint; ``soap_url`` is the deployment's SOAP base
    URL (e.g. ``"http://host:8080/soap"``)."""
    return Endpoint(ENDPOINT_REFERENCE, [DEVICE_TYPE], [SCOPE], soap_url + "/journey")


def register_journey_wsdiscovery(responder: Responder, soap_url: str) -> None:
    """Register ``journey``'s endpoint (before ``responder.start()``)."""
    responder.add(journey_wsdiscovery_endpoint(soap_url))
