"""WS-Discovery participant descriptor for ``shipment``.

Generated by harpia (python target), the Python side of the C++
``sdc/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_sdc.h``. Do not edit. Advertises ``shipment``'s SOAP
endpoint (``POST <soap_url>/shipment``) for zero-config discovery by an
SDC/DPWS-aware client -- additive, the endpoint itself is unchanged::

    responder = Responder()
    register_shipment_wsdiscovery(responder, "http://host:8080/soap")
    responder.start()
"""
from harpia_runtime.wsdiscovery import Endpoint, Responder

#: stable RFC-4122 v5 endpoint reference (project + message + schema hash)
ENDPOINT_REFERENCE = 'urn:uuid:7c77fbf8-457c-52fd-94ae-54d14ab8cd40'
#: the fixed generic DPWS device type
DEVICE_TYPE = 'dpws:Device'
#: the Harpia-namespaced per-project scope
SCOPE = 'https://harpia.dev/sdc/scope/default/shipment'


def shipment_wsdiscovery_endpoint(soap_url: str) -> Endpoint:
    """The advertised endpoint; ``soap_url`` is the deployment's SOAP base
    URL (e.g. ``"http://host:8080/soap"``)."""
    return Endpoint(ENDPOINT_REFERENCE, [DEVICE_TYPE], [SCOPE], soap_url + "/shipment")


def register_shipment_wsdiscovery(responder: Responder, soap_url: str) -> None:
    """Register ``shipment``'s endpoint (before ``responder.start()``)."""
    responder.add(shipment_wsdiscovery_endpoint(soap_url))
