"""Generated unit tests for ``alarm_event`` (table ``alarm_event_table``).

Generated by harpia (python target), the Python side of the C++
``tests/alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_test.cpp``. Do not edit. Run with ``pytest`` from the
``python/`` directory (``pip install .[test]``). Values come from
:func:`harpia_runtime.testing.sample` (the C++ ``TestAdapter`` rules).

Access gate under test: RBAC -- the matrix, and an anonymous caller is fail-closed (401) on every route.
"""
import sqlite3
from pathlib import Path

import pytest

from harpia_generated.db.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    alarm_event_dao,
)
from harpia_generated.protofiles.alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    alarm_event,
)
from harpia_generated.rest import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_rest as rest,
)
from harpia_generated.soap import (
    alarm_event_3ac5d8b36fc7dcfb70888145147ddfb7_soap as soap,
)
from harpia_runtime import testing
from harpia_runtime.db.pool import ConnectionPool, sqlite_pool
from harpia_runtime.json import from_json, to_json
from harpia_runtime.rbac import Decision, Operation, Role, decide, permitted
from harpia_runtime.redaction import PLACEHOLDER
from harpia_runtime.serialize import Format, from_string, to_string, tree_has_phi
from harpia_runtime.xml import from_xml, to_xml
from harpia_runtime.yaml import from_yaml, to_yaml


def _pool(tmp_path: Path) -> ConnectionPool:
    pool = sqlite_pool(str(tmp_path / "http.db"))
    with pool.borrow() as conn:
        testing.create_tables(conn, alarm_event_dao)
    return pool


def _view(msg: alarm_event) -> dict[str, object]:
    return testing.persisted_view(alarm_event_dao, msg)


def test_field_access() -> None:
    testing.check_field_access(alarm_event)


def test_json_round_trip() -> None:
    sent, got = testing.sample(alarm_event), alarm_event()
    assert from_json(to_json(sent), got) and got == sent


def test_xml_round_trip() -> None:
    sent, got = testing.sample(alarm_event), alarm_event()
    assert from_xml(to_xml(sent), got) and got == sent


def test_yaml_round_trip() -> None:
    sent, got = testing.sample(alarm_event), alarm_event()
    assert from_yaml(to_yaml(sent), got) and got == sent


def test_to_string() -> None:
    sent = testing.sample(alarm_event)
    for fmt in Format:
        text = to_string(sent, fmt)
        if tree_has_phi(alarm_event.DESCRIPTOR):  # redacted by design: not a round trip
            assert PLACEHOLDER in text, fmt
            continue
        got = alarm_event()
        assert from_string(text, got, fmt) and got == sent, fmt

def test_crudl_round_trip(tmp_path: Path) -> None:
    # a file, not :memory: (the pool refuses it; same database either way)
    conn = sqlite3.connect(str(tmp_path / "db.sqlite"))
    try:
        testing.create_tables(conn, alarm_event_dao)
        dao = alarm_event_dao(conn)
        first = testing.sample(alarm_event, "a", pk=1, id_base=1000)
        second = testing.sample(alarm_event, "a", pk=2, id_base=2000)
        assert dao.create(first) and dao.create(second)
        got = alarm_event()
        assert dao.read(1, got)
        assert (testing.persisted_view(alarm_event_dao, got)
                == testing.persisted_view(alarm_event_dao, first))
        assert not dao.read(99, alarm_event())
        assert ([testing.persisted_view(alarm_event_dao, m) for m in dao.list()]
                == [testing.persisted_view(alarm_event_dao, m) for m in (first, second)])
        assert len(dao.list(1, 1)) == 1
        changed = testing.sample(alarm_event, "b", pk=1, id_base=1000)
        assert dao.update(changed)
        got = alarm_event()
        assert dao.read(1, got)
        assert (testing.persisted_view(alarm_event_dao, got)
                == testing.persisted_view(alarm_event_dao, changed))
        assert dao.remove(1)
        assert not dao.read(1, alarm_event())
        assert len(dao.list()) == 1
    finally:
        conn.close()


def test_access_modifiers(tmp_path: Path) -> None:
    conn = sqlite3.connect(str(tmp_path / "pk.sqlite"))
    try:
        testing.create_tables(conn, alarm_event_dao)
        dao = alarm_event_dao(conn)
        assert dao.create(testing.sample(alarm_event, "a", pk=1))
        # the primary key is unique: a second row with the same key is refused
        with pytest.raises(sqlite3.IntegrityError):
            dao.create(testing.sample(alarm_event, "b", pk=1, id_base=5000))
    finally:
        conn.close()


XML = {"Content-Type": "text/xml"}


def test_access_rights() -> None:
    # RBAC gate (transport-authn): the fixed role x operation matrix, and no
    # client-certificate identity is fail-closed
    assert permitted(Role.admin, Operation.remove)
    assert not permitted(Role.guest, Operation.create)
    assert permitted(Role.guest, Operation.read)
    assert not permitted(Role.main, Operation.remove)
    assert permitted(Role.none, Operation.heartbeat)
    assert decide("", Operation.create, 'alarm_event') is Decision.unauthenticated


def test_rest_api(tmp_path: Path) -> None:
    # an anonymous (no client certificate) caller is refused on every gated
    # route; the role matrix over mTLS is harpia's own UnitTests/test_py_rbac.py
    pool = _pool(tmp_path)
    path = "/api/v1/alarm_event"
    with testing.serve(pool, rest=[rest.register]) as port:
        assert testing.request(port, "GET", path)[0] == 401
        assert testing.request(port, "GET", path + "/1")[0] == 401
        assert testing.request(port, "POST", path, "{}",
                               {"Content-Type": "application/json"})[0] == 401
        assert testing.request(port, "DELETE", path + "/1")[0] == 401


def test_soap_api(tmp_path: Path) -> None:
    pool = _pool(tmp_path)
    path = "/soap/alarm_event"
    with testing.serve(pool, soap=[soap.register]) as port:
        for op in ("<get><id>1</id></get>",
                   "<set>" + to_xml(testing.sample(alarm_event)) + "</set>"):
            status, body = testing.request(port, "POST", path, testing.soap_envelope(op), XML)
            assert status == 401 and "Client.Authentication" in body
