"""Generated unit tests for ``vip_users`` (table ``table_vip_users``).

Generated by harpia (python target), the Python side of the C++
``tests/vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_test.cpp``. Do not edit. Run with ``pytest`` from the
``python/`` directory (``pip install .[test]``). Values come from
:func:`harpia_runtime.testing.sample` (the C++ ``TestAdapter`` rules).
"""
import sqlite3
from pathlib import Path

from harpia_generated.db.vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_dao import (
    vip_users_dao,
)
from harpia_generated.protofiles.vip_users_3ac5d8b36fc7dcfb70888145147ddfb7_pb2 import (
    vip_users,
)
from harpia_runtime import testing
from harpia_runtime.json import from_json, to_json
from harpia_runtime.redaction import PLACEHOLDER
from harpia_runtime.serialize import Format, from_string, to_string, tree_has_phi
from harpia_runtime.xml import from_xml, to_xml
from harpia_runtime.yaml import from_yaml, to_yaml


def test_field_access() -> None:
    testing.check_field_access(vip_users)


def test_json_round_trip() -> None:
    sent, got = testing.sample(vip_users), vip_users()
    assert from_json(to_json(sent), got) and got == sent


def test_xml_round_trip() -> None:
    sent, got = testing.sample(vip_users), vip_users()
    assert from_xml(to_xml(sent), got) and got == sent


def test_yaml_round_trip() -> None:
    sent, got = testing.sample(vip_users), vip_users()
    assert from_yaml(to_yaml(sent), got) and got == sent


def test_to_string() -> None:
    sent = testing.sample(vip_users)
    for fmt in Format:
        text = to_string(sent, fmt)
        if tree_has_phi(vip_users.DESCRIPTOR):  # redacted by design: not a round trip
            assert PLACEHOLDER in text, fmt
            continue
        got = vip_users()
        assert from_string(text, got, fmt) and got == sent, fmt

def test_crudl_round_trip(tmp_path: Path) -> None:
    # a file, not :memory: (the pool refuses it; same database either way)
    conn = sqlite3.connect(str(tmp_path / "db.sqlite"))
    try:
        testing.create_tables(conn, vip_users_dao)
        dao = vip_users_dao(conn)
        first = testing.sample(vip_users, "a", pk=1, id_base=1000)
        second = testing.sample(vip_users, "a", pk=2, id_base=2000)
        assert dao.create(first) and dao.create(second)
        got = vip_users()
        assert dao.read(1, got)
        assert (testing.persisted_view(vip_users_dao, got)
                == testing.persisted_view(vip_users_dao, first))
        assert not dao.read(99, vip_users())
        assert ([testing.persisted_view(vip_users_dao, m) for m in dao.list()]
                == [testing.persisted_view(vip_users_dao, m) for m in (first, second)])
        assert len(dao.list(1, 1)) == 1
        changed = testing.sample(vip_users, "b", pk=1, id_base=1000)
        assert dao.update(changed)
        got = vip_users()
        assert dao.read(1, got)
        assert (testing.persisted_view(vip_users_dao, got)
                == testing.persisted_view(vip_users_dao, changed))
        assert dao.remove(1)
        assert not dao.read(1, vip_users())
        assert len(dao.list()) == 1
    finally:
        conn.close()
