// Generated by harpia Stage 12 (REST). Do not edit.
#ifndef HARPIA_REST_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_REST_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <string>
#include <vector>

#include "httplib.h"
#include "db/top_users_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"
#include "json/top_users_c96f8fd7f45108efee5a8ecb43eab1da_json.h"
#include "xml/top_users_c96f8fd7f45108efee5a8ecb43eab1da_xml.h"

// RESTful CRUD for top_users, backed by the CRUDL DAO. Register on an
// httplib::Server with a base path (e.g. "/project/v1"); routes are then:
//   GET    <base>/top_users        list
//   GET    <base>/top_users/:id    read
//   POST   <base>/top_users        create   (JSON or XML body)
//   PUT    <base>/top_users/:id    update   (JSON or XML body)
//   DELETE <base>/top_users/:id    delete
//
// Content negotiation: a request body is parsed as XML when its Content-Type
// contains "xml" (else JSON); a response is serialized as XML when the Accept
// header asks for "xml" (else JSON).
//
// Every route enforces the generated access credential (Stage 5 access rights):
// the request must carry X-User: top_users and X-Pswd: c96f8fd7f45108efee5a8ecb43eab1da, or it is rejected
// with HTTP 401 before the operation runs.
namespace harpia {
namespace rest {

// True iff the request carries the correct credential for top_users. Exposed so it
// can be unit-tested directly.
inline bool authorized_top_users(const ::httplib::Request& req) {
    return req.get_header_value("X-User") == "top_users" &&
           req.get_header_value("X-Pswd") == "c96f8fd7f45108efee5a8ecb43eab1da";
}

// content negotiation: XML when asked for, JSON otherwise
inline bool wants_xml_top_users(const ::httplib::Request& req) {
    return req.get_header_value("Accept").find("xml") != std::string::npos;
}
inline bool body_xml_top_users(const ::httplib::Request& req) {
    return req.get_header_value("Content-Type").find("xml") != std::string::npos;
}
inline bool parse_top_users(const ::httplib::Request& req, ::top_users* msg) {
    return body_xml_top_users(req) ? ::harpia::xml::from_xml(req.body, msg)
                                : ::harpia::json::from_json(req.body, msg);
}
inline void serialize_top_users(const ::httplib::Request& req,
                             const ::top_users& msg, ::httplib::Response& res) {
    if (wants_xml_top_users(req)) {
        res.set_content(::harpia::xml::to_xml(msg), "application/xml");
    } else {
        std::string j; ::harpia::json::to_json(msg, &j);
        res.set_content(j, "application/json");
    }
}

inline void register_top_users(::httplib::Server& svr, ::sqlite3* db,
                            const std::string& base) {
    const std::string col = base + "/top_users";
    const std::string item = col + R"(/(\d+))";

    svr.Get(col, [db](const ::httplib::Request& req, ::httplib::Response& res) {
        if (!authorized_top_users(req)) { res.status = 401; return; }
        ::harpia::db::top_users_dao dao(db);
        std::vector<::top_users> rows;
        if (!dao.list(&rows)) { res.status = 500; return; }
        if (wants_xml_top_users(req)) {
            std::string body = "<list>";
            for (const auto& r : rows) body += ::harpia::xml::to_xml(r);
            body += "</list>";
            res.set_content(body, "application/xml");
        } else {
            std::string body = "[";
            for (size_t i = 0; i < rows.size(); ++i) {
                std::string j;
                ::harpia::json::to_json(rows[i], &j);
                if (i) body += ",";
                body += j;
            }
            body += "]";
            res.set_content(body, "application/json");
        }
    });

    svr.Get(item, [db](const ::httplib::Request& req, ::httplib::Response& res) {
        if (!authorized_top_users(req)) { res.status = 401; return; }
        ::harpia::db::top_users_dao dao(db);
        ::top_users msg;
        if (!dao.read(std::stoll(req.matches[1]), &msg)) { res.status = 404; return; }
        serialize_top_users(req, msg, res);
    });

    svr.Post(col, [db](const ::httplib::Request& req, ::httplib::Response& res) {
        if (!authorized_top_users(req)) { res.status = 401; return; }
        ::harpia::db::top_users_dao dao(db);
        ::top_users msg;
        if (!parse_top_users(req, &msg)) { res.status = 400; return; }
        if (!dao.create(msg)) { res.status = 500; return; }
        res.status = 201;
    });

    svr.Put(item, [db](const ::httplib::Request& req, ::httplib::Response& res) {
        if (!authorized_top_users(req)) { res.status = 401; return; }
        ::harpia::db::top_users_dao dao(db);
        ::top_users msg;
        if (!parse_top_users(req, &msg)) { res.status = 400; return; }
        if (!dao.update(msg)) { res.status = 500; return; }
        res.status = 204;
    });

    svr.Delete(item, [db](const ::httplib::Request& req, ::httplib::Response& res) {
        if (!authorized_top_users(req)) { res.status = 401; return; }
        ::harpia::db::top_users_dao dao(db);
        if (!dao.remove(std::stoll(req.matches[1]))) { res.status = 500; return; }
        res.status = 204;
    });
}

}  // namespace rest
}  // namespace harpia

#endif  // HARPIA_REST_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
