// Generated by harpia Stage 12 (REST). Do not edit.
#ifndef HARPIA_REST_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_REST_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>

// Crow's own HTTPMethod enum guards its ALL-CAPS members (DELETE/GET/HEAD/
// POST/PUT/...) with a single `#ifndef DELETE` around the WHOLE block -- if
// DELETE is a macro by the time crow.h's own enum is reached, Crow silently
// falls back to TitleCase members only (Delete/Get/Post/Put), and every
// crow::HTTPMethod::<VERB> reference below stops existing. The trouble is
// crow.h itself (line ~915) does `#include <asio.hpp>` long before its own
// enum (~line 2112), and asio.hpp pulls in <windows.h> (which #defines
// DELETE, winnt.h's generic-access-rights macro) internally -- undefining
// DELETE before `#include "crow.h"` doesn't survive that internal
// re-inclusion. Force <windows.h> in ourselves first and undef DELETE right
// after: windows.h's own include guard then makes crow.h/asio's later
// `#include <windows.h>` a no-op, so our undef sticks.
#ifdef _WIN32
#include <windows.h>
#undef DELETE
#endif

#include "crow.h"
#include "db/users_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"
#include "json/users_c96f8fd7f45108efee5a8ecb43eab1da_json.h"
#include "xml/users_c96f8fd7f45108efee5a8ecb43eab1da_xml.h"

// RESTful CRUD for users, backed by the CRUDL DAO. Register on a
// crow::SimpleApp with a base path (e.g. "/project/v1"); routes are then:
//   GET    <base>/users        list   (?limit=&offset= to paginate)
//   GET    <base>/users/:id    read
//   POST   <base>/users        create   (JSON or XML body)
//   PUT    <base>/users/:id    update   (JSON or XML body)
//   DELETE <base>/users/:id    delete
//
// GET list is paginated when the request supplies ?limit= (>0), or when
// users declares a "pagination[size]" field (its size becomes the default
// limit); ?offset= defaults to 0. With no limit in play, list() returns
// everything, matching pre-pagination behavior.
//
// Routes are registered with route_dynamic (not CROW_ROUTE): the path is built
// from the runtime `base` argument, so it cannot be a compile-time literal. Item
// routes use the "<int>" tag, delivered to the handler as a trailing int64_t.
//
// Content negotiation: a request body is parsed as XML when its Content-Type
// contains "xml" (else JSON); a response is serialized as XML when the Accept
// header asks for "xml" (else JSON).
//
// Every route enforces the generated access credential (Stage 5 access rights):
// the request must carry X-User: users and X-Pswd: c96f8fd7f45108efee5a8ecb43eab1da, or it is rejected
// with HTTP 401 before the operation runs.
namespace harpia {
namespace rest {

// True iff the request carries the correct credential for users. Exposed so it
// can be unit-tested directly.
inline bool authorized_users(const crow::request& req) {
    return req.get_header_value("X-User") == "users" &&
           req.get_header_value("X-Pswd") == "c96f8fd7f45108efee5a8ecb43eab1da";
}

// content negotiation: XML when asked for, JSON otherwise
inline bool wants_xml_users(const crow::request& req) {
    return req.get_header_value("Accept").find("xml") != std::string::npos;
}
inline bool body_xml_users(const crow::request& req) {
    return req.get_header_value("Content-Type").find("xml") != std::string::npos;
}
inline bool parse_users(const crow::request& req, ::users* msg) {
    return body_xml_users(req) ? ::harpia::xml::from_xml(req.body, msg)
                                : ::harpia::json::from_json(req.body, msg);
}
inline void serialize_users(const crow::request& req,
                             const ::users& msg, crow::response& res) {
    if (wants_xml_users(req)) {
        res.set_header("Content-Type", "application/xml");
        res.body = ::harpia::xml::to_xml(msg);
    } else {
        std::string j; ::harpia::json::to_json(msg, &j);
        res.set_header("Content-Type", "application/json");
        res.body = j;
    }
}

inline void register_users(crow::SimpleApp& app, ::soci::session& db,
                            const std::string& base) {
    const std::string col = base + "/users";
    const std::string item = col + "/<int>";
    // capture a session pointer (soci::session is non-copyable); the caller must
    // keep the session alive for the lifetime of the registered routes.
    ::soci::session* dbp = &db;

    app.route_dynamic(col).methods(crow::HTTPMethod::GET)(
        [dbp](const crow::request& req, crow::response& res) {
            if (!authorized_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::users_dao dao(*dbp);
            std::vector<::users> rows;
            // ?limit=&offset= (or the table's declared pagination[size]
            // default) paginate the list; omitting both keeps the
            // unpaginated behavior.
            const char* lim_s = req.url_params.get("limit");
            long long limit = lim_s ? std::atoll(lim_s) : 0LL;
            bool listed;
            if (limit > 0) {
                const char* off_s = req.url_params.get("offset");
                long long offset = off_s ? std::atoll(off_s) : 0;
                listed = dao.list(&rows, offset, limit);
            } else {
                listed = dao.list(&rows);
            }
            if (!listed) { res.code = 500; res.end(); return; }
            if (wants_xml_users(req)) {
                std::string body = "<list>";
                for (const auto& r : rows) body += ::harpia::xml::to_xml(r);
                body += "</list>";
                res.set_header("Content-Type", "application/xml");
                res.body = body;
            } else {
                std::string body = "[";
                for (size_t i = 0; i < rows.size(); ++i) {
                    std::string j;
                    ::harpia::json::to_json(rows[i], &j);
                    if (i) body += ",";
                    body += j;
                }
                body += "]";
                res.set_header("Content-Type", "application/json");
                res.body = body;
            }
            res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::GET)(
        [dbp](const crow::request& req, crow::response& res, int64_t id) {
            if (!authorized_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::users_dao dao(*dbp);
            ::users msg;
            if (!dao.read(id, &msg)) { res.code = 404; res.end(); return; }
            serialize_users(req, msg, res);
            res.end();
        });

    app.route_dynamic(col).methods(crow::HTTPMethod::POST)(
        [dbp](const crow::request& req, crow::response& res) {
            if (!authorized_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::users_dao dao(*dbp);
            ::users msg;
            if (!parse_users(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.create(msg)) { res.code = 500; res.end(); return; }
            res.code = 201; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::PUT)(
        [dbp](const crow::request& req, crow::response& res, int64_t) {
            if (!authorized_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::users_dao dao(*dbp);
            ::users msg;
            if (!parse_users(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.update(msg)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::DELETE)(
        [dbp](const crow::request& req, crow::response& res, int64_t id) {
            if (!authorized_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::users_dao dao(*dbp);
            if (!dao.remove(id)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });
}

}  // namespace rest
}  // namespace harpia

#endif  // HARPIA_REST_USERS_c96f8fd7f45108efee5a8ecb43eab1da
