// Generated by harpia Stage 12 (REST). Do not edit.
#ifndef HARPIA_REST_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_REST_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <cstdint>
#include <string>
#include <vector>

#include "crow.h"
#include "db/vip_users_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"
#include "json/vip_users_c96f8fd7f45108efee5a8ecb43eab1da_json.h"
#include "xml/vip_users_c96f8fd7f45108efee5a8ecb43eab1da_xml.h"

// RESTful CRUD for vip_users, backed by the CRUDL DAO. Register on a
// crow::SimpleApp with a base path (e.g. "/project/v1"); routes are then:
//   GET    <base>/vip_users        list
//   GET    <base>/vip_users/:id    read
//   POST   <base>/vip_users        create   (JSON or XML body)
//   PUT    <base>/vip_users/:id    update   (JSON or XML body)
//   DELETE <base>/vip_users/:id    delete
//
// Routes are registered with route_dynamic (not CROW_ROUTE): the path is built
// from the runtime `base` argument, so it cannot be a compile-time literal. Item
// routes use the "<int>" tag, delivered to the handler as a trailing int64_t.
//
// Content negotiation: a request body is parsed as XML when its Content-Type
// contains "xml" (else JSON); a response is serialized as XML when the Accept
// header asks for "xml" (else JSON).
//
// Every route enforces the generated access credential (Stage 5 access rights):
// the request must carry X-User: vip_users and X-Pswd: c96f8fd7f45108efee5a8ecb43eab1da, or it is rejected
// with HTTP 401 before the operation runs.
namespace harpia {
namespace rest {

// True iff the request carries the correct credential for vip_users. Exposed so it
// can be unit-tested directly.
inline bool authorized_vip_users(const crow::request& req) {
    return req.get_header_value("X-User") == "vip_users" &&
           req.get_header_value("X-Pswd") == "c96f8fd7f45108efee5a8ecb43eab1da";
}

// content negotiation: XML when asked for, JSON otherwise
inline bool wants_xml_vip_users(const crow::request& req) {
    return req.get_header_value("Accept").find("xml") != std::string::npos;
}
inline bool body_xml_vip_users(const crow::request& req) {
    return req.get_header_value("Content-Type").find("xml") != std::string::npos;
}
inline bool parse_vip_users(const crow::request& req, ::vip_users* msg) {
    return body_xml_vip_users(req) ? ::harpia::xml::from_xml(req.body, msg)
                                : ::harpia::json::from_json(req.body, msg);
}
inline void serialize_vip_users(const crow::request& req,
                             const ::vip_users& msg, crow::response& res) {
    if (wants_xml_vip_users(req)) {
        res.set_header("Content-Type", "application/xml");
        res.body = ::harpia::xml::to_xml(msg);
    } else {
        std::string j; ::harpia::json::to_json(msg, &j);
        res.set_header("Content-Type", "application/json");
        res.body = j;
    }
}

inline void register_vip_users(crow::SimpleApp& app, ::sqlite3* db,
                            const std::string& base) {
    const std::string col = base + "/vip_users";
    const std::string item = col + "/<int>";

    app.route_dynamic(col).methods(crow::HTTPMethod::GET)(
        [db](const crow::request& req, crow::response& res) {
            if (!authorized_vip_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::vip_users_dao dao(db);
            std::vector<::vip_users> rows;
            if (!dao.list(&rows)) { res.code = 500; res.end(); return; }
            if (wants_xml_vip_users(req)) {
                std::string body = "<list>";
                for (const auto& r : rows) body += ::harpia::xml::to_xml(r);
                body += "</list>";
                res.set_header("Content-Type", "application/xml");
                res.body = body;
            } else {
                std::string body = "[";
                for (size_t i = 0; i < rows.size(); ++i) {
                    std::string j;
                    ::harpia::json::to_json(rows[i], &j);
                    if (i) body += ",";
                    body += j;
                }
                body += "]";
                res.set_header("Content-Type", "application/json");
                res.body = body;
            }
            res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::GET)(
        [db](const crow::request& req, crow::response& res, int64_t id) {
            if (!authorized_vip_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::vip_users_dao dao(db);
            ::vip_users msg;
            if (!dao.read(id, &msg)) { res.code = 404; res.end(); return; }
            serialize_vip_users(req, msg, res);
            res.end();
        });

    app.route_dynamic(col).methods(crow::HTTPMethod::POST)(
        [db](const crow::request& req, crow::response& res) {
            if (!authorized_vip_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::vip_users_dao dao(db);
            ::vip_users msg;
            if (!parse_vip_users(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.create(msg)) { res.code = 500; res.end(); return; }
            res.code = 201; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::PUT)(
        [db](const crow::request& req, crow::response& res, int64_t) {
            if (!authorized_vip_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::vip_users_dao dao(db);
            ::vip_users msg;
            if (!parse_vip_users(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.update(msg)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::DELETE)(
        [db](const crow::request& req, crow::response& res, int64_t id) {
            if (!authorized_vip_users(req)) { res.code = 401; res.end(); return; }
            ::harpia::db::vip_users_dao dao(db);
            if (!dao.remove(id)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });
}

}  // namespace rest
}  // namespace harpia

#endif  // HARPIA_REST_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
