// Generated by harpia Stage 14 (unit tests). Do not edit.
//
// Unit tests for the generated shipment message, CRUDL DAO and SOAP access:
//   14.1 simple access     -- setter/getter round-trips for every scalar field
//   14.2 database          -- create/read/update/list/remove over in-memory SQLite
//   14.3 access rights      -- the SOAP credential gate accepts the right password
//                             and rejects a wrong/absent one
//   14.4 access modifiers   -- schema constraints from the modifiers are enforced
//                             (PRIMARY KEY uniqueness rejects a duplicate row)
//   14.5 json parser        -- to_json/from_json round-trips the message and
//                             is_valid_json accepts good JSON, rejects garbage
//   14.6 xml parser         -- to_xml/from_xml round-trips the message and
//                             from_xml rejects garbage
//   14.7/14.10 REST API      -- the REST bindings serve real HTTP JSON CRUD
//                             (POST/GET/list/PUT/DELETE/404) over a live server
//   14.8/14.9 SOAP API       -- the SOAP endpoint serves real SOAP-over-HTTP
//                             (set/get with the credential; wrong one -> 401)
//
// Each check returns a distinct non-zero code so a CTest failure points at the
// exact assertion; main() returns 0 only when every check passes.
#include "db/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"
#include "soap/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_soap.h"
#include "json/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_json.h"
#include "xml/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_xml.h"
#include "rest/shipment_3ac5d8b36fc7dcfb70888145147ddfb7_rest.h"
#include "harpia_test_client.h"

#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>

#include <cstdint>
#include <string>
#include <thread>
#include <vector>

namespace {

int simple_access() {
    ::shipment m;
    m.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    m.set_tag("tag_a");
    m.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    m.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    m.set_originator("originator_a");
    if (m.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 10;
    if (m.tag() != "tag_a") return 11;
    if (m.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 12;
    if (m.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 13;
    if (m.originator() != "originator_a") return 14;
    return 0;
}

int database_roundtrip() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::shipment_dao dao(db);
    if (!dao.create_table()) return 21;

    // create + read back row 1
    ::shipment a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_tag("tag_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator("originator_a");
    if (!dao.create(a)) return 22;
    ::shipment got;
    if (!dao.read(1, &got)) return 23;
    if (got.tag() != "tag_a") return 24;
    if (got.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 24;
    if (got.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 24;
    if (got.originator() != "originator_a") return 24;

    // update an existing row
    ::shipment upd = a;
    upd.set_tag("tag_u");
    if (!dao.update(upd)) return 25;
    ::shipment got2;
    if (!dao.read(1, &got2)) return 26;
    if (got2.tag() != "tag_u") return 27;

    // a second row, then list + delete
    ::shipment b;
    b.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(2);
    b.set_tag("tag_b");
    b.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    b.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    b.set_originator("originator_b");
    if (!dao.create(b)) return 28;
    std::vector<::shipment> all;
    if (!dao.list(&all) || all.size() != 2) return 29;
    if (!dao.remove(1)) return 30;
    ::shipment gone;
    if (dao.read(1, &gone)) return 31;

    return 0;
}

int access_rights() {
    const std::string good = "<soap:Envelope><soap:Header><credentials><user>shipment</user><pswd>3ac5d8b36fc7dcfb70888145147ddfb7</pswd></credentials></soap:Header><soap:Body/></soap:Envelope>";
    const std::string wrong = "<soap:Envelope><soap:Header><credentials><user>shipment</user><pswd>wrong-password</pswd></credentials></soap:Header><soap:Body/></soap:Envelope>";
    const std::string none = "<soap:Envelope><soap:Body/></soap:Envelope>";
    if (!harpia::soap::authorized_shipment(good)) return 50;
    if (harpia::soap::authorized_shipment(wrong)) return 51;
    if (harpia::soap::authorized_shipment(none)) return 52;
    return 0;
}

int access_modifiers() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::shipment_dao dao(db);
    if (!dao.create_table()) return 41;
    ::shipment a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_tag("tag_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator("originator_a");
    if (!dao.create(a)) return 42;
    // PRIMARY KEY is unique: a duplicate key must be rejected
    ::shipment dup;
    dup.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    dup.set_tag("tag_b");
    dup.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    dup.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    dup.set_originator("originator_b");
    if (dao.create(dup)) return 43;
    return 0;
}

int json_parser() {
    ::shipment a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_tag("tag_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator("originator_a");
    std::string js;
    if (!harpia::json::to_json(a, &js)) return 60;
    ::shipment b;
    if (!harpia::json::from_json(js, &b)) return 61;
    if (b.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 62;
    if (b.tag() != "tag_a") return 62;
    if (b.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 62;
    if (b.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 62;
    if (b.originator() != "originator_a") return 62;
    if (!harpia::json::is_valid_json(js)) return 63;
    if (harpia::json::is_valid_json("this is not json")) return 64;
    return 0;
}

int xml_parser() {
    ::shipment a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_tag("tag_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator("originator_a");
    const std::string xs = ::harpia::xml::to_xml(a);
    if (xs.empty()) return 70;
    ::shipment b;
    if (!::harpia::xml::from_xml(xs, &b)) return 71;
    if (b.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 72;
    if (b.tag() != "tag_a") return 72;
    if (b.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 72;
    if (b.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 72;
    if (b.originator() != "originator_a") return 72;
    ::shipment c;
    if (::harpia::xml::from_xml("not xml at all", &c)) return 73;
    return 0;
}

int rest_api() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::shipment_dao dao(db);
    if (!dao.create_table()) return 81;
    crow::SimpleApp app;
    app.loglevel(crow::LogLevel::Warning);
    harpia::rest::register_shipment(app, db, "/api/v1");
    auto fut = app.bindaddr("127.0.0.1").port(0).multithreaded().run_async();
    app.wait_for_server_start();
    const int port = app.port();
    if (port <= 0) { app.stop(); fut.get(); return 82; }
    harpia_test::Client cli("127.0.0.1", port);
    const harpia_test::Headers cred = {{"X-User", "shipment"}, {"X-Pswd", "3ac5d8b36fc7dcfb70888145147ddfb7"}};
    const harpia_test::Headers credx = {{"X-User", "shipment"}, {"X-Pswd", "3ac5d8b36fc7dcfb70888145147ddfb7"}, {"Accept", "application/xml"}};
    int code = 0;
    do {
        // every route requires the generated credential (X-User/X-Pswd)
        auto noc = cli.Get("/api/v1/shipment");
        if (!noc || noc.status != 401) { code = 93; break; }
        auto bad = cli.Get("/api/v1/shipment", harpia_test::Headers{{"X-User", "shipment"}, {"X-Pswd", "nope"}});
        if (!bad || bad.status != 401) { code = 94; break; }
        ::shipment a;
        a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
        a.set_tag("tag_a");
        a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
        a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
        a.set_originator("originator_a");
        std::string body;
        if (!::harpia::json::to_json(a, &body)) { code = 83; break; }
        auto post = cli.Post("/api/v1/shipment", body, "application/json", cred);
        if (!post || post.status != 201) { code = 84; break; }
        auto got = cli.Get("/api/v1/shipment/1", cred);
        if (!got || got.status != 200) { code = 85; break; }
        if (got.body.find("tag_a") == std::string::npos) { code = 86; break; }
        auto lst = cli.Get("/api/v1/shipment", cred);
        if (!lst || lst.status != 200) { code = 87; break; }
        // content negotiation: XML response, and an XML request body
        auto gx = cli.Get("/api/v1/shipment/1", credx);
        if (!gx || gx.status != 200 || gx.body.find("<") == std::string::npos) { code = 95; break; }
        if (gx.body.find("tag_a") == std::string::npos) { code = 96; break; }
        ::shipment ax = a;
        ax.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(2);
        const std::string axml = ::harpia::xml::to_xml(ax);
        auto xpost = cli.Post("/api/v1/shipment", axml, "application/xml", cred);
        if (!xpost || xpost.status != 201) { code = 97; break; }
        auto gx2 = cli.Get("/api/v1/shipment/2", credx);
        if (!gx2 || gx2.status != 200) { code = 98; break; }
        if (gx2.body.find("tag_a") == std::string::npos) { code = 99; break; }
        ::shipment b = a;
        b.set_tag("tag_u");
        std::string bb;
        if (!::harpia::json::to_json(b, &bb)) { code = 88; break; }
        auto put = cli.Put("/api/v1/shipment/1", bb, "application/json", cred);
        if (!put || put.status != 204) { code = 89; break; }
        auto g2 = cli.Get("/api/v1/shipment/1", cred);
        if (!g2 || g2.body.find("tag_u") == std::string::npos) { code = 90; break; }
        auto del = cli.Delete("/api/v1/shipment/1", cred);
        if (!del || del.status != 204) { code = 91; break; }
        auto gone = cli.Get("/api/v1/shipment/1", cred);
        if (!gone || gone.status != 404) { code = 92; break; }
    } while (false);
    app.stop(); fut.get();
    return code;
}

int soap_api() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::shipment_dao dao(db);
    if (!dao.create_table()) return 101;
    crow::SimpleApp app;
    app.loglevel(crow::LogLevel::Warning);
    harpia::soap::register_shipment_soap(app, db, "/soap");
    auto fut = app.bindaddr("127.0.0.1").port(0).multithreaded().run_async();
    app.wait_for_server_start();
    const int port = app.port();
    if (port <= 0) { app.stop(); fut.get(); return 102; }
    harpia_test::Client cli("127.0.0.1", port);
    const std::string hdr = "<soap:Header><credentials><user>shipment</user><pswd>3ac5d8b36fc7dcfb70888145147ddfb7</pswd></credentials></soap:Header>";
    const std::string badhdr = "<soap:Header><credentials><user>shipment</user><pswd>nope</pswd></credentials></soap:Header>";
    int code = 0;
    do {
        ::shipment a;
        a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
        a.set_tag("tag_a");
        a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
        a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
        a.set_originator("originator_a");
        const std::string mx = ::harpia::xml::to_xml(a);
        const std::string setEnv = "<soap:Envelope>" + hdr + "<soap:Body><set>" + mx + "</set></soap:Body></soap:Envelope>";
        auto s = cli.Post("/soap/shipment", setEnv, "text/xml");
        if (!s || s.status != 200 || s.body.find("<ok>true</ok>") == std::string::npos) { code = 103; break; }
        const std::string badEnv = "<soap:Envelope>" + badhdr + "<soap:Body><get><id>1</id></get></soap:Body></soap:Envelope>";
        auto na = cli.Post("/soap/shipment", badEnv, "text/xml");
        if (!na || na.status != 401) { code = 104; break; }
        const std::string getEnv = "<soap:Envelope>" + hdr + "<soap:Body><get><id>1</id></get></soap:Body></soap:Envelope>";
        auto g = cli.Post("/soap/shipment", getEnv, "text/xml");
        if (!g || g.status != 200 || g.body.find("getResponse") == std::string::npos) { code = 105; break; }
        if (g.body.find("tag_a") == std::string::npos) { code = 106; break; }
        ::shipment b = a;
        b.set_tag("tag_u");
        const std::string ux = ::harpia::xml::to_xml(b);
        const std::string updEnv = "<soap:Envelope>" + hdr + "<soap:Body><update>" + ux + "</update></soap:Body></soap:Envelope>";
        auto u = cli.Post("/soap/shipment", updEnv, "text/xml");
        if (!u || u.status != 200 || u.body.find("<ok>true</ok>") == std::string::npos) { code = 107; break; }
        auto g2 = cli.Post("/soap/shipment", getEnv, "text/xml");
        if (!g2 || g2.body.find("tag_u") == std::string::npos) { code = 108; break; }
        const std::string delEnv = "<soap:Envelope>" + hdr + "<soap:Body><delete><id>1</id></delete></soap:Body></soap:Envelope>";
        auto d = cli.Post("/soap/shipment", delEnv, "text/xml");
        if (!d || d.status != 200 || d.body.find("<ok>true</ok>") == std::string::npos) { code = 109; break; }
        auto g3 = cli.Post("/soap/shipment", getEnv, "text/xml");
        if (!g3 || g3.body.find("not found") == std::string::npos) { code = 111; break; }
    } while (false);
    app.stop(); fut.get();
    return code;
}

}  // namespace

int main() {
    if (int rc = simple_access()) return rc;
    if (int rc = database_roundtrip()) return rc;
    if (int rc = access_rights()) return rc;
    if (int rc = access_modifiers()) return rc;
    if (int rc = json_parser()) return rc;
    if (int rc = xml_parser()) return rc;
    if (int rc = rest_api()) return rc;
    if (int rc = soap_api()) return rc;
    return 0;
}
