// Generated by harpia Stage 14 (unit tests). Do not edit.
//
// Unit tests for the generated users message, CRUDL DAO and SOAP access:
//   14.1 simple access     -- setter/getter round-trips for every scalar field
//   14.2 database          -- create/read/update/list/remove over in-memory SQLite
//   14.3 access rights      -- the SOAP credential gate accepts the right password
//                             and rejects a wrong/absent one
//   14.4 access modifiers   -- schema constraints from the modifiers are enforced
//                             (PRIMARY KEY uniqueness rejects a duplicate row)
//   14.5 json parser        -- to_json/from_json round-trips the message and
//                             is_valid_json accepts good JSON, rejects garbage
//   14.6 xml parser         -- to_xml/from_xml round-trips the message and
//                             from_xml rejects garbage
//   14.7/14.10 REST API      -- the REST bindings serve real HTTP JSON CRUD
//                             (POST/GET/list/PUT/DELETE/404) over a live server
//   14.8/14.9 SOAP API       -- the SOAP endpoint serves real SOAP-over-HTTP
//                             (set/get with the credential; wrong one -> 401)
//
// Each check returns a distinct non-zero code so a CTest failure points at the
// exact assertion; main() returns 0 only when every check passes.
#include "db/users_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"
#include "soap/users_3ac5d8b36fc7dcfb70888145147ddfb7_soap.h"
#include "json/users_3ac5d8b36fc7dcfb70888145147ddfb7_json.h"
#include "xml/users_3ac5d8b36fc7dcfb70888145147ddfb7_xml.h"
#include "rest/users_3ac5d8b36fc7dcfb70888145147ddfb7_rest.h"
#include "harpia_test_client.h"

#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>

#include <cstdint>
#include <string>
#include <thread>
#include <vector>

namespace {

int simple_access() {
    ::users m;
    m.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    m.set_address("address_a");
    m.set_name("name_a");
    m.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    m.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    m.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    if (m.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 10;
    if (m.address() != "address_a") return 11;
    if (m.name() != "name_a") return 12;
    if (m.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 13;
    if (m.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 14;
    if (m.originator_3ac5d8b36fc7dcfb70888145147ddfb7() != "originator_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 15;
    return 0;
}

int database_roundtrip() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::users_dao dao(db);
    if (!dao.create_table()) return 21;

    // create + read back row 1
    ::users a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_address("address_a");
    a.set_name("name_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    if (!dao.create(a)) return 22;
    ::users got;
    if (!dao.read(1, &got)) return 23;
    if (got.address() != "address_a") return 24;
    if (got.name() != "name_a") return 24;
    if (got.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 24;
    if (got.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 24;
    if (got.originator_3ac5d8b36fc7dcfb70888145147ddfb7() != "originator_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 24;

    // update an existing row
    ::users upd = a;
    upd.set_address("address_u");
    if (!dao.update(upd)) return 25;
    ::users got2;
    if (!dao.read(1, &got2)) return 26;
    if (got2.address() != "address_u") return 27;

    // a second row, then list + delete
    ::users b;
    b.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(2);
    b.set_address("address_b");
    b.set_name("name_b");
    b.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    b.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    b.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    if (!dao.create(b)) return 28;
    std::vector<::users> all;
    if (!dao.list(&all) || all.size() != 2) return 29;
    if (!dao.remove(1)) return 30;
    ::users gone;
    if (dao.read(1, &gone)) return 31;

    return 0;
}

int access_rights() {
    using ::harpia::rbac::Role;
    using ::harpia::rbac::Operation;
    using ::harpia::rbac::Decision;
    if (!::harpia::rbac::permitted(Role::admin, Operation::remove)) return 50;
    if (::harpia::rbac::permitted(Role::guest, Operation::create)) return 51;
    if (!::harpia::rbac::permitted(Role::guest, Operation::read)) return 52;
    if (::harpia::rbac::permitted(Role::main, Operation::remove)) return 53;
    if (!::harpia::rbac::permitted(Role::none, Operation::heartbeat)) return 54;
    // no client-cert identity -> unauthenticated (fail-closed)
    if (::harpia::rbac::decide("", Operation::create, "users")
            != Decision::unauthenticated) return 55;
    return 0;
}

int access_modifiers() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::users_dao dao(db);
    if (!dao.create_table()) return 41;
    ::users a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_address("address_a");
    a.set_name("name_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    if (!dao.create(a)) return 42;
    // PRIMARY KEY is unique: a duplicate key must be rejected
    ::users dup;
    dup.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    dup.set_address("address_b");
    dup.set_name("name_b");
    dup.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    dup.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    dup.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_b");
    if (dao.create(dup)) return 43;
    return 0;
}

int json_parser() {
    ::users a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_address("address_a");
    a.set_name("name_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    std::string js;
    if (!harpia::json::to_json(a, &js)) return 60;
    ::users b;
    if (!harpia::json::from_json(js, &b)) return 61;
    if (b.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 62;
    if (b.address() != "address_a") return 62;
    if (b.name() != "name_a") return 62;
    if (b.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 62;
    if (b.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 62;
    if (b.originator_3ac5d8b36fc7dcfb70888145147ddfb7() != "originator_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 62;
    if (!harpia::json::is_valid_json(js)) return 63;
    if (harpia::json::is_valid_json("this is not json")) return 64;
    return 0;
}

int xml_parser() {
    ::users a;
    a.set_id_3ac5d8b36fc7dcfb70888145147ddfb7(1);
    a.set_address("address_a");
    a.set_name("name_a");
    a.set_status_3ac5d8b36fc7dcfb70888145147ddfb7("status_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_error_3ac5d8b36fc7dcfb70888145147ddfb7("error_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    a.set_originator_3ac5d8b36fc7dcfb70888145147ddfb7("originator_3ac5d8b36fc7dcfb70888145147ddfb7_a");
    const std::string xs = ::harpia::xml::to_xml(a);
    if (xs.empty()) return 70;
    ::users b;
    if (!::harpia::xml::from_xml(xs, &b)) return 71;
    if (b.id_3ac5d8b36fc7dcfb70888145147ddfb7() != 1) return 72;
    if (b.address() != "address_a") return 72;
    if (b.name() != "name_a") return 72;
    if (b.status_3ac5d8b36fc7dcfb70888145147ddfb7() != "status_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 72;
    if (b.error_3ac5d8b36fc7dcfb70888145147ddfb7() != "error_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 72;
    if (b.originator_3ac5d8b36fc7dcfb70888145147ddfb7() != "originator_3ac5d8b36fc7dcfb70888145147ddfb7_a") return 72;
    ::users c;
    if (::harpia::xml::from_xml("not xml at all", &c)) return 73;
    return 0;
}

int rest_api() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::users_dao dao(db);
    if (!dao.create_table()) return 81;
    crow::SimpleApp app;
    app.loglevel(crow::LogLevel::Warning);
    harpia::rest::register_users(app, db, "/api/v1");
    auto fut = app.bindaddr("127.0.0.1").port(0).multithreaded().run_async();
    app.wait_for_server_start();
    const int port = app.port();
    if (port <= 0) { app.stop(); fut.get(); return 82; }
    harpia_test::Client cli("127.0.0.1", port);
    int code = 0;
    do {
        auto gl = cli.Get("/api/v1/users");
        if (!gl || gl.status != 401) { code = 93; break; }
        auto gi = cli.Get("/api/v1/users/1");
        if (!gi || gi.status != 401) { code = 94; break; }
        auto po = cli.Post("/api/v1/users", "{}", "application/json");
        if (!po || po.status != 401) { code = 95; break; }
        auto de = cli.Delete("/api/v1/users/1");
        if (!de || de.status != 401) { code = 96; break; }
    } while (false);
    app.stop(); fut.get();
    return code;
}

int soap_api() {
    ::soci::session db(::soci::sqlite3, ":memory:");
    harpia::db::users_dao dao(db);
    if (!dao.create_table()) return 101;
    crow::SimpleApp app;
    app.loglevel(crow::LogLevel::Warning);
    harpia::soap::register_users_soap(app, db, "/soap");
    auto fut = app.bindaddr("127.0.0.1").port(0).multithreaded().run_async();
    app.wait_for_server_start();
    const int port = app.port();
    if (port <= 0) { app.stop(); fut.get(); return 102; }
    harpia_test::Client cli("127.0.0.1", port);
    const std::string getEnv = "<soap:Envelope><soap:Body><get><id>1</id></get></soap:Body></soap:Envelope>";
    const std::string setEnv = "<soap:Envelope><soap:Body><set><users></users></set></soap:Body></soap:Envelope>";
    int code = 0;
    do {
        auto g = cli.Post("/soap/users", getEnv, "text/xml");
        if (!g || g.status != 401) { code = 103; break; }
        auto s = cli.Post("/soap/users", setEnv, "text/xml");
        if (!s || s.status != 401) { code = 104; break; }
    } while (false);
    app.stop(); fut.get();
    return code;
}

}  // namespace

int main() {
    if (int rc = simple_access()) return rc;
    if (int rc = database_roundtrip()) return rc;
    if (int rc = access_rights()) return rc;
    if (int rc = access_modifiers()) return rc;
    if (int rc = json_parser()) return rc;
    if (int rc = xml_parser()) return rc;
    if (int rc = rest_api()) return rc;
    if (int rc = soap_api()) return rc;
    return 0;
}
