// Generated by harpia Stage 8 (schema migration / version transforms). Do not edit.
#ifndef HARPIA_MIGRATE_DATA_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_MIGRATE_DATA_c96f8fd7f45108efee5a8ecb43eab1da

#include <functional>
#include <map>
#include <set>
#include <string>

#include <soci/soci.h>
#include "db/data_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"

// Schema migration for data (spec 8 / 7.2 "validation/transformative functions
// for versions"). Brings an existing database up to the current schema version
// (c96f8fd7f45108efee5a8ecb43eab1da) and records it in "_harpia_schema_version":
//   - ensures the table (and its map/repeated child tables) exist,
//   - RENAMEs a column carrying the DSL's renamed_from[<old>] modifier (both
//     names are known at generation time), before anything else runs,
//   - adds any column present in the current schema but missing from a live table
//     an older generated version created (additive evolution via ALTER TABLE),
//   - runs the caller-supplied data_transform hook, if any (see below),
//   - DROPs any column a live table has that the current schema no longer
//     declares. This is an IMPLICIT, UNCONDITIONAL diff, not a marker-driven
//     one: there is no schema history, so any unrecognized live column is
//     dropped, including one added out-of-band.
//   - RETYPEs any column whose live SQL type no longer matches the current
//     schema's declared type for that same name. Unlike a rename, this needs
//     no DSL marker -- the name is unchanged, so a mismatch is unambiguous.
//     Runs last among the structural steps, against the table already
//     stabilized by the rename/add/drop steps above.
//   - stamps the current version hash.
// Cross-version DATA transforms (deriving one column's value from another,
// not just moving/CASTing structure) are handled via an optional
// data_transform hook -- harpia has no schema history, so it cannot know
// what a transform should compute, only guarantee a stable extension point
// and when it runs. It runs AFTER add (so any new destination column already
// exists) and BEFORE drop (so an old source column being retired is still
// there to read) -- e.g. splitting a retiring "full_name" into new
// "first_name"/"last_name" columns needs exactly this ordering. Pass
// nothing for today's plaintext behavior; the caller's lambda should be
// idempotent (e.g. guard with a WHERE clause) since migrate_data may run
// on every startup.
//
// SOCI-based (works on any backend); the SQL dialect (version table, column
// introspection, ALTER/RENAME/DROP/RETYPE, version-stamp upsert) comes from
// the harpia DbBackend.
namespace harpia {
namespace db {

inline bool migrate_data(::soci::session& db,
                           std::function<void(::soci::session&)> data_transform = nullptr) {
    try {
        db << "CREATE TABLE IF NOT EXISTS \"_harpia_schema_version\" (\"name\" TEXT PRIMARY KEY, \"version\" TEXT);";

        // ensure the table + its map/repeated child tables exist at the current schema
        ::harpia::db::data_dao dao(db);
        if (!dao.create_table()) return false;

        // columns the live table currently has (dialect-uniform: the query's one
        // selected column is each existing column's name)
        std::set<std::string> have;
        {
            std::string _cn; ::soci::indicator _ci;
            ::soci::statement _cs = (db.prepare << "SELECT \"name\" FROM pragma_table_info('table_data');",
                                     ::soci::into(_cn, _ci));
            _cs.execute();
            while (_cs.fetch()) { if (_ci == ::soci::i_ok) have.insert(_cn); }
        }

        // renames: old column name -> new, ahead of add/drop so they see the
        // corrected column set. Idempotent: a no-op once the old name is gone
        // (a second migrate_data call, or a table that never had it).

        // additive migration: add any column missing from an older table version
        if (!have.count("i")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"i\" INTEGER;";
        }
        if (!have.count("j")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"j\" INTEGER;";
        }
        if (!have.count("val_vari")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"val_vari\" INTEGER;";
        }
        if (!have.count("val_var")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"val_var\" INTEGER;";
        }
        if (!have.count("val_val")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"val_val\" INTEGER;";
        }
        if (!have.count("car")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"car\" INTEGER;";
        }
        if (!have.count("STATUS_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        if (!have.count("ERROR_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        if (!have.count("ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"table_data\" ADD COLUMN \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        // caller-supplied cross-version data transform (see the header
        // comment above for why this runs here: after add, before drop).
        // No-op when not supplied.
        if (data_transform) data_transform(db);
        // non-additive: drop any live column the current schema no longer
        // declares (see the header comment above for the implicit-diff caveat)
        {
            static const std::set<std::string> _current = { "ID_c96f8fd7f45108efee5a8ecb43eab1da", "i", "j", "val_vari", "val_var", "val_val", "car", "STATUS_c96f8fd7f45108efee5a8ecb43eab1da", "ERROR_c96f8fd7f45108efee5a8ecb43eab1da", "ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da" };
            for (auto _hit = have.begin(); _hit != have.end(); ) {
                if (!_current.count(*_hit)) {
                    const std::string& _dc = *_hit;
                    db << "ALTER TABLE \"table_data\" DROP COLUMN \"" + _dc + "\";";
                    _hit = have.erase(_hit);
                } else {
                    ++_hit;
                }
            }
        }
        // live column TYPES (dialect-uniform: two selected columns, name then
        // type), queried AFTER the rename/add/drop steps above so it reflects
        // the table's now-stabilized current column set -- a mismatch here
        // can only be a stale type on a pre-existing column.
        std::map<std::string, std::string> have_types;
        {
            std::string _tn, _tt; ::soci::indicator _tni, _tti;
            ::soci::statement _ts = (db.prepare << "SELECT \"name\", \"type\" FROM pragma_table_info('table_data');",
                                     ::soci::into(_tn, _tni), ::soci::into(_tt, _tti));
            _ts.execute();
            while (_ts.fetch()) {
                if (_tni == ::soci::i_ok && _tti == ::soci::i_ok) have_types[_tn] = _tt;
            }
        }
        // non-additive: bring any column whose live type differs from the
        // current schema to the current type (see the header comment above)
        {
        bool _needs_retype = false;
            if (have_types.count("ID_c96f8fd7f45108efee5a8ecb43eab1da") && have_types["ID_c96f8fd7f45108efee5a8ecb43eab1da"] != "INTEGER") _needs_retype = true;
            if (have_types.count("i") && have_types["i"] != "INTEGER") _needs_retype = true;
            if (have_types.count("j") && have_types["j"] != "INTEGER") _needs_retype = true;
            if (have_types.count("val_vari") && have_types["val_vari"] != "INTEGER") _needs_retype = true;
            if (have_types.count("val_var") && have_types["val_var"] != "INTEGER") _needs_retype = true;
            if (have_types.count("val_val") && have_types["val_val"] != "INTEGER") _needs_retype = true;
            if (have_types.count("car") && have_types["car"] != "INTEGER") _needs_retype = true;
            if (have_types.count("STATUS_c96f8fd7f45108efee5a8ecb43eab1da") && have_types["STATUS_c96f8fd7f45108efee5a8ecb43eab1da"] != "TEXT") _needs_retype = true;
            if (have_types.count("ERROR_c96f8fd7f45108efee5a8ecb43eab1da") && have_types["ERROR_c96f8fd7f45108efee5a8ecb43eab1da"] != "TEXT") _needs_retype = true;
            if (have_types.count("ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da") && have_types["ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da"] != "TEXT") _needs_retype = true;
        if (_needs_retype) {
            db << "CREATE TABLE \"table_data__retype_tmp\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\" INTEGER PRIMARY KEY, \"i\" INTEGER, \"j\" INTEGER, \"val_vari\" INTEGER, \"val_var\" INTEGER, \"val_val\" INTEGER, \"car\" INTEGER, \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT, \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT);";
            db << "INSERT INTO \"table_data__retype_tmp\" (\"ID_c96f8fd7f45108efee5a8ecb43eab1da\", \"i\", \"j\", \"val_vari\", \"val_var\", \"val_val\", \"car\", \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\", \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\", \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\") SELECT CAST(\"ID_c96f8fd7f45108efee5a8ecb43eab1da\" AS INTEGER), CAST(\"i\" AS INTEGER), CAST(\"j\" AS INTEGER), CAST(\"val_vari\" AS INTEGER), CAST(\"val_var\" AS INTEGER), CAST(\"val_val\" AS INTEGER), CAST(\"car\" AS INTEGER), CAST(\"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" AS TEXT), CAST(\"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" AS TEXT), CAST(\"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" AS TEXT) FROM \"table_data\";";
            db << "DROP TABLE \"table_data\";";
            db << "ALTER TABLE \"table_data__retype_tmp\" RENAME TO \"table_data\";";
        }
        }
        // stamp the current version
        db << "INSERT OR REPLACE INTO \"_harpia_schema_version\" (\"name\", \"version\") VALUES ('table_data', 'c96f8fd7f45108efee5a8ecb43eab1da');";
        return true;
    } catch (const std::exception&) { return false; }
}

// The version hash this migration targets.
inline const char* version_data() { return "c96f8fd7f45108efee5a8ecb43eab1da"; }

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_MIGRATE_DATA_c96f8fd7f45108efee5a8ecb43eab1da
