// Generated by harpia Stage 8 (schema migration / version transforms). Do not edit.
#ifndef HARPIA_MIGRATE_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_MIGRATE_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <set>
#include <string>

#include <soci/soci.h>
#include "db/top_users_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"

// Schema migration for top_users (spec 8 / 7.2 "validation/transformative functions
// for versions"). Brings an existing database up to the current schema version
// (c96f8fd7f45108efee5a8ecb43eab1da) and records it in "_harpia_schema_version":
//   - ensures the table (and its map/repeated child tables) exist,
//   - RENAMEs a column carrying the DSL's renamed_from[<old>] modifier (both
//     names are known at generation time), before anything else runs,
//   - adds any column present in the current schema but missing from a live table
//     an older generated version created (additive evolution via ALTER TABLE),
//   - DROPs any column a live table has that the current schema no longer
//     declares. This is an IMPLICIT, UNCONDITIONAL diff, not a marker-driven
//     one: there is no schema history, so any unrecognized live column is
//     dropped, including one added out-of-band.
//   - stamps the current version hash.
// Column type changes and cross-version data transforms are still not handled.
//
// SOCI-based (works on any backend); the SQL dialect (version table, column
// introspection, ALTER/RENAME/DROP, version-stamp upsert) comes from the
// harpia DbBackend.
namespace harpia {
namespace db {

inline bool migrate_top_users(::soci::session& db) {
    try {
        db << "CREATE TABLE IF NOT EXISTS \"_harpia_schema_version\" (\"name\" TEXT PRIMARY KEY, \"version\" TEXT);";

        // ensure the table + its map/repeated child tables exist at the current schema
        ::harpia::db::top_users_dao dao(db);
        if (!dao.create_table()) return false;

        // columns the live table currently has (dialect-uniform: the query's one
        // selected column is each existing column's name)
        std::set<std::string> have;
        {
            std::string _cn; ::soci::indicator _ci;
            ::soci::statement _cs = (db.prepare << "SELECT \"name\" FROM pragma_table_info('user_table');",
                                     ::soci::into(_cn, _ci));
            _cs.execute();
            while (_cs.fetch()) { if (_ci == ::soci::i_ok) have.insert(_cn); }
        }

        // renames: old column name -> new, ahead of add/drop so they see the
        // corrected column set. Idempotent: a no-op once the old name is gone
        // (a second migrate_top_users call, or a table that never had it).

        // additive migration: add any column missing from an older table version
        if (!have.count("sponsor")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"sponsor\" TEXT;";
        }
        if (!have.count("name")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"name\" TEXT;";
        }
        if (!have.count("myUsers")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"myUsers\" INTEGER;";
        }
        if (!have.count("STATUS_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        if (!have.count("ERROR_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        if (!have.count("ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da")) {
            db << "ALTER TABLE \"user_table\" ADD COLUMN \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;";
        }
        // non-additive: drop any live column the current schema no longer
        // declares (see the header comment above for the implicit-diff caveat)
        {
            static const std::set<std::string> _current = { "ID_c96f8fd7f45108efee5a8ecb43eab1da", "sponsor", "name", "myUsers", "STATUS_c96f8fd7f45108efee5a8ecb43eab1da", "ERROR_c96f8fd7f45108efee5a8ecb43eab1da", "ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da" };
            for (auto _hit = have.begin(); _hit != have.end(); ) {
                if (!_current.count(*_hit)) {
                    const std::string& _dc = *_hit;
                    db << "ALTER TABLE \"user_table\" DROP COLUMN \"" + _dc + "\";";
                    _hit = have.erase(_hit);
                } else {
                    ++_hit;
                }
            }
        }
        // stamp the current version
        db << "INSERT OR REPLACE INTO \"_harpia_schema_version\" (\"name\", \"version\") VALUES ('user_table', 'c96f8fd7f45108efee5a8ecb43eab1da');";
        return true;
    } catch (const std::exception&) { return false; }
}

// The version hash this migration targets.
inline const char* version_top_users() { return "c96f8fd7f45108efee5a8ecb43eab1da"; }

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_MIGRATE_TOP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
