// Generated by harpia Stage 8 (schema migration / version transforms). Do not edit.
#ifndef HARPIA_MIGRATE_USERS_6cea4c29647b10eb99b42c762ac09f75
#define HARPIA_MIGRATE_USERS_6cea4c29647b10eb99b42c762ac09f75

#include <set>
#include <string>

#include "sqlite3.h"
#include "db/users_6cea4c29647b10eb99b42c762ac09f75_crudl.h"

// Schema migration for users (spec 8 / 7.2 "validation/transformative functions
// for versions"). Brings an existing database up to the current schema version
// (6cea4c29647b10eb99b42c762ac09f75) and records it in "_harpia_schema_version":
//   - ensures the table (and its map/repeated child tables) exist,
//   - adds any column present in the current schema but missing from a live table
//     an older generated version created (additive evolution via ALTER TABLE),
//   - stamps the current version hash.
// Column renames/drops, type changes and cross-version data transforms are not
// handled (additive migrations only).
namespace harpia {
namespace db {

inline bool migrate_users(::sqlite3* db) {
    auto exec = [db](const char* sql) {
        return ::sqlite3_exec(db, sql, nullptr, nullptr, nullptr) == SQLITE_OK;
    };
    if (!exec("CREATE TABLE IF NOT EXISTS \"_harpia_schema_version\" "
              "(\"name\" TEXT PRIMARY KEY, \"version\" TEXT);")) return false;

    // ensure the table + its map/repeated child tables exist at the current schema
    ::harpia::db::users_dao dao(db);
    if (!dao.create_table()) return false;

    // columns the live table currently has
    std::set<std::string> have;
    {
        ::sqlite3_stmt* st = nullptr;
        if (::sqlite3_prepare_v2(db, "PRAGMA table_info(\"user_table\");",
                                 -1, &st, nullptr) == SQLITE_OK) {
            while (::sqlite3_step(st) == SQLITE_ROW) {
                const unsigned char* n = ::sqlite3_column_text(st, 1);
                if (n) have.insert(reinterpret_cast<const char*>(n));
            }
            ::sqlite3_finalize(st);
        }
    }

    // additive migration: add any column missing from an older table version
    if (!have.count("address")) {
        if (!exec("ALTER TABLE \"user_table\" ADD COLUMN \"address\" TEXT;")) return false;
    }
    if (!have.count("name")) {
        if (!exec("ALTER TABLE \"user_table\" ADD COLUMN \"name\" TEXT;")) return false;
    }
    if (!have.count("STATUS_6cea4c29647b10eb99b42c762ac09f75")) {
        if (!exec("ALTER TABLE \"user_table\" ADD COLUMN \"STATUS_6cea4c29647b10eb99b42c762ac09f75\" TEXT;")) return false;
    }
    if (!have.count("ERROR_6cea4c29647b10eb99b42c762ac09f75")) {
        if (!exec("ALTER TABLE \"user_table\" ADD COLUMN \"ERROR_6cea4c29647b10eb99b42c762ac09f75\" TEXT;")) return false;
    }
    if (!have.count("ORIGINATOR_6cea4c29647b10eb99b42c762ac09f75")) {
        if (!exec("ALTER TABLE \"user_table\" ADD COLUMN \"ORIGINATOR_6cea4c29647b10eb99b42c762ac09f75\" TEXT;")) return false;
    }
    // stamp the current version
    if (!exec("INSERT OR REPLACE INTO \"_harpia_schema_version\" "
              "(\"name\", \"version\") VALUES ('user_table', '6cea4c29647b10eb99b42c762ac09f75');")) return false;
    return true;
}

// The version hash this migration targets.
inline const char* version_users() { return "6cea4c29647b10eb99b42c762ac09f75"; }

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_MIGRATE_USERS_6cea4c29647b10eb99b42c762ac09f75
