// Generated by harpia Stage 8 (schema migration / version transforms). Do not edit.
#ifndef HARPIA_MIGRATE_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
#define HARPIA_MIGRATE_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da

#include <set>
#include <string>

#include "sqlite3.h"
#include "db/vip_users_c96f8fd7f45108efee5a8ecb43eab1da_crudl.h"

// Schema migration for vip_users (spec 8 / 7.2 "validation/transformative functions
// for versions"). Brings an existing database up to the current schema version
// (c96f8fd7f45108efee5a8ecb43eab1da) and records it in "_harpia_schema_version":
//   - ensures the table (and its map/repeated child tables) exist,
//   - adds any column present in the current schema but missing from a live table
//     an older generated version created (additive evolution via ALTER TABLE),
//   - stamps the current version hash.
// Column renames/drops, type changes and cross-version data transforms are not
// handled (additive migrations only).
namespace harpia {
namespace db {

inline bool migrate_vip_users(::sqlite3* db) {
    auto exec = [db](const char* sql) {
        return ::sqlite3_exec(db, sql, nullptr, nullptr, nullptr) == SQLITE_OK;
    };
    if (!exec("CREATE TABLE IF NOT EXISTS \"_harpia_schema_version\" "
              "(\"name\" TEXT PRIMARY KEY, \"version\" TEXT);")) return false;

    // ensure the table + its map/repeated child tables exist at the current schema
    ::harpia::db::vip_users_dao dao(db);
    if (!dao.create_table()) return false;

    // columns the live table currently has
    std::set<std::string> have;
    {
        ::sqlite3_stmt* st = nullptr;
        if (::sqlite3_prepare_v2(db, "PRAGMA table_info(\"table_vip_users\");",
                                 -1, &st, nullptr) == SQLITE_OK) {
            while (::sqlite3_step(st) == SQLITE_ROW) {
                const unsigned char* n = ::sqlite3_column_text(st, 1);
                if (n) have.insert(reinterpret_cast<const char*>(n));
            }
            ::sqlite3_finalize(st);
        }
    }

    // additive migration: add any column missing from an older table version
    if (!have.count("name")) {
        if (!exec("ALTER TABLE \"table_vip_users\" ADD COLUMN \"name\" TEXT;")) return false;
    }
    if (!have.count("family")) {
        if (!exec("ALTER TABLE \"table_vip_users\" ADD COLUMN \"family\" TEXT;")) return false;
    }
    if (!have.count("STATUS_c96f8fd7f45108efee5a8ecb43eab1da")) {
        if (!exec("ALTER TABLE \"table_vip_users\" ADD COLUMN \"STATUS_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;")) return false;
    }
    if (!have.count("ERROR_c96f8fd7f45108efee5a8ecb43eab1da")) {
        if (!exec("ALTER TABLE \"table_vip_users\" ADD COLUMN \"ERROR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;")) return false;
    }
    if (!have.count("ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da")) {
        if (!exec("ALTER TABLE \"table_vip_users\" ADD COLUMN \"ORIGINATOR_c96f8fd7f45108efee5a8ecb43eab1da\" TEXT;")) return false;
    }
    // stamp the current version
    if (!exec("INSERT OR REPLACE INTO \"_harpia_schema_version\" "
              "(\"name\", \"version\") VALUES ('table_vip_users', 'c96f8fd7f45108efee5a8ecb43eab1da');")) return false;
    return true;
}

// The version hash this migration targets.
inline const char* version_vip_users() { return "c96f8fd7f45108efee5a8ecb43eab1da"; }

}  // namespace db
}  // namespace harpia

#endif  // HARPIA_MIGRATE_VIP_USERS_c96f8fd7f45108efee5a8ecb43eab1da
