-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message beacon_log -> table "beacon_log_table" (PRIVATE)
CREATE TABLE IF NOT EXISTS "beacon_log_table" (
    "ID_3ac5d8b36fc7dcfb70888145147ddfb7" INTEGER PRIMARY KEY,
    "label" TEXT,
    "strength" INTEGER,
    "STATUS_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ERROR_3ac5d8b36fc7dcfb70888145147ddfb7" TEXT,
    "ORIGINATOR" TEXT
);
