-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message data -> table "table_data" (PRIVATE)
CREATE TABLE IF NOT EXISTS "table_data" (
    "ID_738be851643f8e1a41c121caf519d41f" INTEGER PRIMARY KEY,
    "i" INTEGER,
    "j" INTEGER,
    "val_vari" INTEGER,
    "val_var" INTEGER,
    "val_val" INTEGER,
    "car" INTEGER,
    "STATUS_738be851643f8e1a41c121caf519d41f" TEXT,
    "ERROR_738be851643f8e1a41c121caf519d41f" TEXT,
    "ORIGINATOR_738be851643f8e1a41c121caf519d41f" TEXT
);
-- val.a: map in embedded prince -> child table
-- val.b: map in embedded prince -> child table
-- val.c: map in embedded prince -> child table
-- tags: repeated -> child table (see repeated_fields)

-- map a -> child table "table_data__val_a" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_a" (
    "owner" INTEGER,
    "key" TEXT,
    "value" TEXT,
    PRIMARY KEY ("owner", "key")
);
-- map b -> child table "table_data__val_b" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_b" (
    "owner" INTEGER,
    "key" TEXT,
    "value" INTEGER,
    PRIMARY KEY ("owner", "key")
);
-- map c -> child table "table_data__val_c" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_c" (
    "owner" INTEGER,
    "key" INTEGER,
    "value" TEXT,
    PRIMARY KEY ("owner", "key")
);
-- repeated tags -> child table "table_data__tags" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__tags" (
    "owner" INTEGER,
    "ordinal" INTEGER,
    "value" INTEGER,
    PRIMARY KEY ("owner", "ordinal")
);
