-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message data -> table "table_data" (PRIVATE)
CREATE TABLE IF NOT EXISTS "table_data" (
    "ID_6cea4c29647b10eb99b42c762ac09f75" INTEGER PRIMARY KEY,
    "i" INTEGER,
    "j" INTEGER,
    "val_vari" INTEGER,
    "val_var" INTEGER,
    "val_val" INTEGER,
    "car" INTEGER,
    "STATUS_6cea4c29647b10eb99b42c762ac09f75" TEXT,
    "ERROR_6cea4c29647b10eb99b42c762ac09f75" TEXT,
    "ORIGINATOR_6cea4c29647b10eb99b42c762ac09f75" TEXT
);
-- val.a: map in embedded prince -> child table
-- val.b: map in embedded prince -> child table
-- val.c: map in embedded prince -> child table
-- tags: repeated -> child table (see repeated_fields)

-- map a -> child table "table_data__val_a" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_a" (
    "owner" INTEGER,
    "key" TEXT,
    "value" TEXT,
    PRIMARY KEY ("owner", "key")
);
-- map b -> child table "table_data__val_b" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_b" (
    "owner" INTEGER,
    "key" TEXT,
    "value" INTEGER,
    PRIMARY KEY ("owner", "key")
);
-- map c -> child table "table_data__val_c" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__val_c" (
    "owner" INTEGER,
    "key" INTEGER,
    "value" TEXT,
    PRIMARY KEY ("owner", "key")
);
-- repeated tags -> child table "table_data__tags" (owner -> "table_data")
CREATE TABLE IF NOT EXISTS "table_data__tags" (
    "owner" INTEGER,
    "ordinal" INTEGER,
    "value" INTEGER,
    PRIMARY KEY ("owner", "ordinal")
);
