-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message users -> table "user_table" (PUBLIC)
CREATE TABLE IF NOT EXISTS "user_table" (
    "ID_738be851643f8e1a41c121caf519d41f" INTEGER PRIMARY KEY,
    "address" TEXT,
    "name" TEXT,
    "STATUS_738be851643f8e1a41c121caf519d41f" TEXT,
    "ERROR_738be851643f8e1a41c121caf519d41f" TEXT,
    "ORIGINATOR_738be851643f8e1a41c121caf519d41f" TEXT
);
