-- Generated by harpia Stage 8 (SQL schema). Do not edit.
-- message vip_users -> table "table_vip_users" (PRIVATE)
CREATE TABLE IF NOT EXISTS "table_vip_users" (
    "ID_734126ee6efdfbd64a1678bf49ee9683" INTEGER PRIMARY KEY,
    "name" TEXT,
    "family" TEXT,
    "STATUS_734126ee6efdfbd64a1678bf49ee9683" TEXT,
    "ERROR_734126ee6efdfbd64a1678bf49ee9683" TEXT,
    "ORIGINATOR_734126ee6efdfbd64a1678bf49ee9683" TEXT
);
