"""Stage 10 -- unified serialization façade (Track F / Sessions F.2, F.3).

F.2 closed out the JSON/XML/YAML `toString` triad through one shared entry
point (`SerializeAdapter/runtime/harpia_serialize.h`). F.3 wires `phi`
redaction into that single hook: `phi` fields render as a fixed placeholder
(`[REDACTED]`) by default in all three formats, never omitted from the
structure.

Emitted per generation:
  - one thin per-message wrapper `<name>_<hash>_serialize.h`,
  - `serialize/harpia_phi_registry.h` -- a generated `constexpr` table of the
    schema's `(message, field)` `phi` pairs (from `variable.is_phi`, F2),
  - copies of the static runtimes `harpia_serialize.h`, `harpia_redaction.h`
    and `harpia_redaction_audit.h` (serialization task 4 -- the audited
    opt-out from redaction), plus a co-copy of Foundation F3's
    `compliance/harpia_audit_sink.h` that the audit runtime #includes.
"""
import os

from Logger.logger import logger
from Errors.Error import Error, Types, Classes
from Util.util import loadTemplate, write_if_different, copy_if_different
from Compliance.audit_common import AUDIT_SINK_RUNTIME, AUDIT_SINK_RUNTIME_SRC

SERIALIZE_EXT = "_serialize.h"
RUNTIME = "harpia_serialize.h"
REDACTION_RUNTIME = "harpia_redaction.h"
REDACTION_AUDIT_RUNTIME = "harpia_redaction_audit.h"
PHI_REGISTRY = "harpia_phi_registry.h"
_PHI_GUARD = "HARPIA_PHI_REGISTRY_H"

_WRAPPER = loadTemplate(__file__, "wrapper.h.tmpl")
_RUNTIME_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "runtime")


class SerializeAdapter:
    def __init__(self, messages, dest, compliance=None) -> None:
        self.compliance = compliance
        self.messages = messages
        self.dest = dest
        self.outDir = os.path.join(dest, "generated", "cpp", "serialize")
        self.log = logger(outFile=None, moduleName="SerializeAdapter")

    def Process(self):
        os.makedirs(self.outDir, exist_ok=True)
        for name in (RUNTIME, REDACTION_RUNTIME, REDACTION_AUDIT_RUNTIME):
            copy_if_different(os.path.join(_RUNTIME_DIR, name),
                             os.path.join(self.outDir, name))
        # serialization task 4: harpia_redaction_audit.h #includes Foundation
        # F3's AuditSink as "compliance/harpia_audit_sink.h" -- co-copy it so
        # the include resolves from generated/cpp/ (same idea as Crypto's
        # KEY_PROVIDER_RUNTIME_DEPS co-copy).
        compliance_dir = os.path.join(self.dest, "generated", "cpp", "compliance")
        os.makedirs(compliance_dir, exist_ok=True)
        copy_if_different(AUDIT_SINK_RUNTIME_SRC,
                         os.path.join(compliance_dir, AUDIT_SINK_RUNTIME))
        write_if_different(os.path.join(self.outDir, PHI_REGISTRY),
                           self._render_phi_registry())

        written = 0
        for msg in self.messages:
            if getattr(msg, "isEnum", False):
                continue
            fileName = "{}_{}{}".format(msg.name, msg.md5Hash, SERIALIZE_EXT)
            write_if_different(os.path.join(self.outDir, fileName),
                               self._render(msg))
            written += 1

        if written == 0:
            self.log.print("no messages to generate serialization wrappers for")
            return Error(errCl=Classes.MESSAGES,
                         errTp=Types.NOTHING_TO_REPORT,
                         FileName=self.outDir)

        self.log.print(
            "generated {} unified serialization wrapper(s) + phi registry "
            "into {}".format(written, self.outDir))
        return None

    def _render(self, msg):
        pbHeader = "protofiles/{}_{}.pb.h".format(msg.name, msg.md5Hash)
        guard = "HARPIA_SERIALIZE_{}_{}".format(msg.name.upper(), msg.md5Hash)
        return _WRAPPER.format(guard=guard, pb_header=pbHeader, name=msg.name)

    def _phi_pairs(self):
        """(message name, field name) for every `phi`-tagged field in the
        schema -- keyed by the plain names the protobuf descriptor exposes at
        runtime (`Descriptor::name()` / `FieldDescriptor::name()`)."""
        pairs = []
        for msg in self.messages:
            if getattr(msg, "isEnum", False):
                continue
            for v in getattr(msg, "variables", None) or []:
                if getattr(v, "is_phi", False):
                    pairs.append((msg.name, v.name))
        return pairs

    def _render_phi_registry(self):
        pairs = self._phi_pairs()
        rows = ",\n".join(
            '    harpia::serialize::phi::PhiField{{{m}, {f}}}'.format(
                m=_cpp_str(m), f=_cpp_str(f)) for m, f in pairs)
        body = "{{\n" + rows + "\n}}" if pairs else "{}"
        return _PHI_TEMPLATE.format(guard=_PHI_GUARD, count=len(pairs), rows=body)


def _cpp_str(s):
    return '"{}"'.format(str(s).replace("\\", "\\\\").replace('"', '\\"'))


_PHI_TEMPLATE = '''\
// Generated by harpia Stage 10 (phi-field registry -- Track F / F.3). Do not edit.
//
// The schema's `phi`-tagged (message, field) pairs (from variable.is_phi, F2).
// harpia_redaction.h consults this so the unified serialization path renders
// every `phi` value as a fixed placeholder by default -- one hook, all three
// formats.
#ifndef {guard}
#define {guard}

#include <array>
#include <cstddef>
#include <string_view>

namespace harpia {{
namespace serialize {{
namespace phi {{

struct PhiField {{
    std::string_view message;
    std::string_view field;
}};

inline constexpr std::size_t kPhiFieldCount = {count};
inline constexpr std::array<PhiField, kPhiFieldCount> kPhiFields = {rows};

// is (message, field) a `phi` field?
inline constexpr bool is_phi(std::string_view message, std::string_view field) {{
    for (const auto& e : kPhiFields) {{
        if (e.message == message && e.field == field) {{
            return true;
        }}
    }}
    return false;
}}

// does `message` declare at least one `phi` field directly? (a nested-message
// tree walk is the caller's job -- it needs the runtime descriptor.)
inline constexpr bool message_has_phi(std::string_view message) {{
    for (const auto& e : kPhiFields) {{
        if (e.message == message) {{
            return true;
        }}
    }}
    return false;
}}

}}  // namespace phi
}}  // namespace serialize
}}  // namespace harpia

#endif  // {guard}
'''
