// Generated by harpia Stage 12 (REST). Do not edit.
#ifndef HARPIA_REST_DATA_3ac5d8b36fc7dcfb70888145147ddfb7
#define HARPIA_REST_DATA_3ac5d8b36fc7dcfb70888145147ddfb7

#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>

// Crow's own HTTPMethod enum guards its ALL-CAPS members (DELETE/GET/HEAD/
// POST/PUT/...) with a single `#ifndef DELETE` around the WHOLE block -- if
// DELETE is a macro by the time crow.h's own enum is reached, Crow silently
// falls back to TitleCase members only (Delete/Get/Post/Put), and every
// crow::HTTPMethod::<VERB> reference below stops existing. The trouble is
// crow.h itself (line ~915) does `#include <asio.hpp>` long before its own
// enum (~line 2112), and asio.hpp pulls in <windows.h> (which #defines
// DELETE, winnt.h's generic-access-rights macro) internally -- undefining
// DELETE before `#include "crow.h"` doesn't survive that internal
// re-inclusion. Force <windows.h> in ourselves first and undef DELETE right
// after: windows.h's own include guard then makes crow.h/asio's later
// `#include <windows.h>` a no-op, so our undef sticks.
#ifdef _WIN32
#include <windows.h>
#undef DELETE
#endif

#include "crow.h"
#include "db/data_3ac5d8b36fc7dcfb70888145147ddfb7_crudl.h"
#include "json/data_3ac5d8b36fc7dcfb70888145147ddfb7_json.h"
#include "xml/data_3ac5d8b36fc7dcfb70888145147ddfb7_xml.h"
#include "http/harpia_rbac.h"
// RESTful CRUD for data, backed by the CRUDL DAO. Register on a
// crow::SimpleApp with a base path (e.g. "/project/v1"); routes are then:
//   GET    <base>/data        list   (?limit=&offset= to paginate)
//   GET    <base>/data/:id    read
//   POST   <base>/data        create   (JSON or XML body)
//   PUT    <base>/data/:id    update   (JSON or XML body)
//   DELETE <base>/data/:id    delete
//
// GET list is paginated when the request supplies ?limit= (>0), or when
// data declares a "pagination[size]" field (its size becomes the default
// limit); ?offset= defaults to 0. With no limit in play, list() returns
// everything, matching pre-pagination behavior.
//
// Routes are registered with route_dynamic (not CROW_ROUTE): the path is built
// from the runtime `base` argument, so it cannot be a compile-time literal. Item
// routes use the "<int>" tag, delivered to the handler as a trailing int64_t.
//
// Content negotiation: a request body is parsed as XML when its Content-Type
// contains "xml" (else JSON); a response is serialized as XML when the Accept
// header asks for "xml" (else JSON).
//
// Access gate (compiled in at generation time; which variant depends on
// transport_hardening_required(compliance) -- transport-authn epic, tasks 3+4):
//   hardened  -> a three-role RBAC check (admin / main / guest). The verified
//               mTLS client-certificate subject CommonName
//               (crow::request::client_cert_cn) is resolved to a role via the
//               HARPIA_RBAC_MAP file and checked against the route's operation
//               (GET-list -> list, GET-item -> read, POST -> create, PUT ->
//               update, DELETE -> remove). No / unverifiable identity -> 401;
//               valid identity, wrong role -> 403. Every denial emits exactly
//               one AuditSink "rbac_denied" record (names only, never a
//               credential value). See generated http/harpia_rbac.h.
//   otherwise -> the flat generated access credential: the request must carry
//               X-User: data and X-Pswd: 3ac5d8b36fc7dcfb70888145147ddfb7, or it is rejected with 401
//               before the operation runs.
// The crow::SimpleApp itself is stood up by the generated
// http/http_server_bringup.h (transport-authn epic, task 3) -- its
// harpia::http_transport::HttpServer registers this binding and the matching
// SOAP endpoint on one app and, when transport_hardening_required(compliance)
// was true at generation time, configures it for mTLS (client cert required
// AND verified, harpia_http_mtls.h) with plaintext refused.
namespace harpia {
namespace rest {

// Role gate for data (transport-authn epic, task 4). Resolves the verified
// mTLS client-certificate CommonName (crow::request::client_cert_cn) to a role
// via the HARPIA_RBAC_MAP file and checks it against `op`. On deny it stamps
// the response -- 401 (no / unverifiable identity) or 403 (valid identity,
// wrong role) -- and returns false; ::harpia::rbac::decide has already emitted
// the single AuditSink "rbac_denied" record. Exposed for direct unit testing.
inline bool authz_data(const crow::request& req, crow::response& res,
                         ::harpia::rbac::Operation op) {
    switch (::harpia::rbac::decide(req.client_cert_cn, op, "data")) {
        case ::harpia::rbac::Decision::allow:
            return true;
        case ::harpia::rbac::Decision::unauthenticated:
            res.code = 401;
            return false;
        default:
            res.code = 403;
            return false;
    }
}

// content negotiation: XML when asked for, JSON otherwise
inline bool wants_xml_data(const crow::request& req) {
    return req.get_header_value("Accept").find("xml") != std::string::npos;
}
inline bool body_xml_data(const crow::request& req) {
    return req.get_header_value("Content-Type").find("xml") != std::string::npos;
}
inline bool parse_data(const crow::request& req, ::data* msg) {
    return body_xml_data(req) ? ::harpia::xml::from_xml(req.body, msg)
                                : ::harpia::json::from_json(req.body, msg);
}
inline void serialize_data(const crow::request& req,
                             const ::data& msg, crow::response& res) {
    if (wants_xml_data(req)) {
        res.set_header("Content-Type", "application/xml");
        res.body = ::harpia::xml::to_xml(msg);
    } else {
        std::string j; ::harpia::json::to_json(msg, &j);
        res.set_header("Content-Type", "application/json");
        res.body = j;
    }
}

inline void register_data(crow::SimpleApp& app, ::soci::session& db,
                            const std::string& base) {
    const std::string col = base + "/data";
    const std::string item = col + "/<int>";
    // capture a session pointer (soci::session is non-copyable); the caller must
    // keep the session alive for the lifetime of the registered routes.
    ::soci::session* dbp = &db;

    app.route_dynamic(col).methods(crow::HTTPMethod::GET)(
        [dbp](const crow::request& req, crow::response& res) {
            if (!authz_data(req, res, ::harpia::rbac::Operation::list)) { res.end(); return; }
            ::harpia::db::data_dao dao(*dbp);
            std::vector<::data> rows;
            // ?limit=&offset= (or the table's declared pagination[size]
            // default) paginate the list; omitting both keeps the
            // unpaginated behavior.
            const char* lim_s = req.url_params.get("limit");
            long long limit = lim_s ? std::atoll(lim_s) : 0LL;
            bool listed;
            if (limit > 0) {
                const char* off_s = req.url_params.get("offset");
                long long offset = off_s ? std::atoll(off_s) : 0;
                listed = dao.list(&rows, offset, limit);
            } else {
                listed = dao.list(&rows);
            }
            if (!listed) { res.code = 500; res.end(); return; }
            if (wants_xml_data(req)) {
                std::string body = "<list>";
                for (const auto& r : rows) body += ::harpia::xml::to_xml(r);
                body += "</list>";
                res.set_header("Content-Type", "application/xml");
                res.body = body;
            } else {
                std::string body = "[";
                for (size_t i = 0; i < rows.size(); ++i) {
                    std::string j;
                    ::harpia::json::to_json(rows[i], &j);
                    if (i) body += ",";
                    body += j;
                }
                body += "]";
                res.set_header("Content-Type", "application/json");
                res.body = body;
            }
            res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::GET)(
        [dbp](const crow::request& req, crow::response& res, int64_t id) {
            if (!authz_data(req, res, ::harpia::rbac::Operation::read)) { res.end(); return; }
            ::harpia::db::data_dao dao(*dbp);
            ::data msg;
            if (!dao.read(id, &msg)) { res.code = 404; res.end(); return; }
            serialize_data(req, msg, res);
            res.end();
        });

    app.route_dynamic(col).methods(crow::HTTPMethod::POST)(
        [dbp](const crow::request& req, crow::response& res) {
            if (!authz_data(req, res, ::harpia::rbac::Operation::create)) { res.end(); return; }
            ::harpia::db::data_dao dao(*dbp);
            ::data msg;
            if (!parse_data(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.create(msg)) { res.code = 500; res.end(); return; }
            res.code = 201; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::PUT)(
        [dbp](const crow::request& req, crow::response& res, int64_t) {
            if (!authz_data(req, res, ::harpia::rbac::Operation::update)) { res.end(); return; }
            ::harpia::db::data_dao dao(*dbp);
            ::data msg;
            if (!parse_data(req, &msg)) { res.code = 400; res.end(); return; }
            if (!dao.update(msg)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });

    app.route_dynamic(item).methods(crow::HTTPMethod::DELETE)(
        [dbp](const crow::request& req, crow::response& res, int64_t id) {
            if (!authz_data(req, res, ::harpia::rbac::Operation::remove)) { res.end(); return; }
            ::harpia::db::data_dao dao(*dbp);
            if (!dao.remove(id)) { res.code = 500; res.end(); return; }
            res.code = 204; res.end();
        });
}

}  // namespace rest
}  // namespace harpia

#endif  // HARPIA_REST_DATA_3ac5d8b36fc7dcfb70888145147ddfb7
